import {View, Region} from 'marionette'
import LitDomApi from '@mnjs/adapters/dom/lit-html'
import {html, render, type TemplateResult} from 'lit-html'
import {Editor, Extension, isTextSelection} from '@tiptap/core'
import {Selection} from '@tiptap/pm/state'
import {BubbleMenuPlugin} from '@tiptap/extension-bubble-menu'
import {createEditorCoreExtensions} from '@/components/input/editor/editorExtensionsCore'
import {saveEditorDraft, loadEditorDraft, clearEditorDraft} from '@/helpers/editorDraftStorage'
import {isEditorContentEmpty} from '@/helpers/editorContentEmpty'
import inputPrompt from '@/helpers/inputPrompt'
import {eventToShortcutString} from '@/helpers/shortcut'
import {getTopLayerContainer} from '@/helpers/getTopLayerContainer'
import {EditorToolbarView} from './editor-toolbar'
import {nativeEditorSuggestions} from './editor-suggestions'
import {nativeEditorNodes, type EditorNodeContext} from './editor-nodeviews'
import {AvatarTooltipView} from '../../features/task/task-membership-user'
import {EditorLightboxView} from './editor-lightbox'
import {listIcon} from '../task-list/list-ui'
import './editor.scss'
export interface NativeEditorOptions {
 value: string, canWrite: boolean, projectId: number, storageKey: string, placeholder: string,
 context: Omit<EditorNodeContext, 'life' | 'projectId'> & {reportError: (error: unknown) => void},
 upload?: (files: File[] | FileList, signal: AbortSignal) => Promise<string[]>,
 changed: (value: string) => void, save: (submitted: string) => Promise<string | undefined>,
 variant?: string, showSave?: boolean, showEdit?: boolean, editShortcut?: string, enableDiscard?: boolean, bottomActions?: {title: string, action: () => void}[],
}
const marks = ['bold', 'italic', 'underline', 'strike', 'code', 'link']
export const NativeEditorView = View.extend({
	ui: {'content': '[data-content]', 'textBubble': '[data-text-bubble]', 'imageBubble': '[data-image-bubble]', 'save': '[data-save]', 'actions': '[data-edit-actions]', 'wrapper': '.tiptap__wrapper', 'editor': '.tiptap__editor', 'upload': '[data-upload]', toolbarHost: '[data-toolbar]', actionSave: '[data-action-save-item]', editItem: '[data-edit-item]'},
	className() { return `native-editor-surface tiptap ${this.options.variant ?? 'tiptap__task-description'}` },
	initialize(options: NativeEditorOptions) { void options },
	createState() { return {life: new AbortController(), inputLife: new AbortController(), editor: undefined as Editor | undefined, editing: {value: false}, dirty: {value: false}, lastSaved: this.options.value, toolbar: undefined as InstanceType<typeof EditorToolbarView> | undefined, tip: undefined as InstanceType<typeof Region> | undefined, tipHost: undefined as HTMLElement | undefined, lightbox: undefined as InstanceType<typeof Region> | undefined, lightboxHost: undefined as HTMLElement | undefined, menus: [] as HTMLElement[], cancelSuggestions: undefined as (() => void) | undefined, key: undefined as ((event: KeyboardEvent) => void) | undefined} },
	regions: {toolbar: '[data-toolbar]'},
	events: {'click [data-edit]': 'edit', 'click @ui.save': 'saveNow', 'click [data-action-save]': 'saveNow', 'dblclick .tiptap__editor': 'doubleClick', 'click @ui.editor': 'contentClick', 'change @ui.upload': 'uploadChanged', keydown: 'escape'},
	templateContext() { return {content: this.content()} }, template: ({content}: {content: TemplateResult}) => content,
	content() { const t = this.options.context.t; return html`<div class="tiptap__wrapper"><div data-toolbar></div><div data-text-bubble><div class="editor-bubble__wrapper">${marks.map(mark => html`<button type="button" class="base-button base-button--type-button editor-bubble__button" data-mark=${mark} @mouseenter=${(event: MouseEvent) => this.tip(event.currentTarget as HTMLElement, t(`input.editor.${mark === 'strike' ? 'strikethrough' : mark}`))} @mouseleave=${() => this.hideTip()} aria-label=${t(`input.editor.${mark === 'strike' ? 'strikethrough' : mark}`)} @click=${(event: MouseEvent) => this.mark(mark, event)}>${listIcon(mark === 'strike' ? 'strikethrough' : mark)}</button>`)}</div></div><div data-image-bubble><div class="editor-bubble__wrapper"><button type="button" class="base-button base-button--type-button editor-bubble__button editor-bubble__button--text" @click=${(event: MouseEvent) => this.alt(event)}>${t('input.editor.altText')}</button></div></div><div class="tiptap__editor" data-content></div></div><input type="file" id="tiptap__image-upload" class="is-hidden" data-upload><ul class="tiptap__editor-actions d-print-none" data-edit-actions><li data-action-save-item><button type="button" class="base-button base-button--type-button done-edit" data-action-save>${t('misc.save')}</button></li><li data-edit-item><button type="button" class="base-button base-button--type-button done-edit" data-edit>${t('input.editor.edit')}</button></li>${(this.options.bottomActions ?? []).map(action => html`<li><button type="button" class="base-button base-button--type-button" @click=${action.action}>${action.title}</button></li>`)}</ul><button type="button" data-cy="saveEditor" class="base-button base-button--type-button button is-outlined has-no-shadow mbs-4" data-save><span>${t('misc.save')}</span></button>` },
	onRender() {
		const state = this.getState(), context: EditorNodeContext = {...this.options.context, projectId: () => this.options.projectId, life: state.life.signal}
		const suggestions = nativeEditorSuggestions(context), nodes = nativeEditorNodes(context, suggestions.mentions)
		state.cancelSuggestions = suggestions.cancel
		const extensions = createEditorCoreExtensions({adapters: {...nodes, commands: suggestions.commands, emoji: suggestions.emoji}, t: context.t, isEditing: state.editing, isEditEnabled: () => this.options.canWrite, placeholder: () => this.options.placeholder, contentHasChanged: state.dirty, bubbleSave: () => { void this.saveNow() }, getEditor: () => this.live(), uploadCallback: () => this.options.upload ? files => this.options.upload!(files, state.inputLife.signal) : undefined, uploadAndInsertFiles: files => { void this.uploadFiles(files) }})
		// Commit document navigation to ProseMirror state before the next input.
		// Native DOM End selection can be restored to the stale edit-entry selection.
		extensions.push(Extension.create({name: 'documentNavigation', addKeyboardShortcuts() {
			const move = (end: boolean) => this.editor.commands.command(({tr, dispatch}) => { if (dispatch) tr.setSelection(end ? Selection.atEnd(tr.doc) : Selection.atStart(tr.doc)).scrollIntoView(); return true })
			return {'Mod-End': () => move(true), 'Mod-Home': () => move(false)}
		}}))
		extensions.push(nodes.mention, Extension.create({name: 'escapeKey', addKeyboardShortcuts: () => ({Escape: () => { if (this.options.enableDiscard === false) return false; this.discard(); return true }})}))
		state.editor = new Editor({element: (this.getUI('content')![0] as HTMLElement)!, content: this.options.value, extensions, editable: false, parseOptions: {preserveWhitespace: true}, editorProps: {attributes: {class: 'tiptap', 'aria-label': this.options.placeholder || context.t('input.editor.label')}}, onUpdate: () => this.changed(), onSelectionUpdate: () => this.refreshControls(), onTransaction: () => this.refreshControls()})
		const editor = state.editor
		state.toolbar = new EditorToolbarView({editor, t: context.t, image: event => this.image(event), link: event => { void this.link(event) }, tip: (element, text) => this.tip(element, text), hideTip: () => this.hideTip()}); this.showChildView('toolbar', state.toolbar)
		const textBubble = (this.getUI('textBubble')![0] as HTMLElement)!, imageBubble = (this.getUI('imageBubble')![0] as HTMLElement)!
		textBubble.remove(); imageBubble.remove(); state.menus = [textBubble, imageBubble]
		editor.registerPlugin(BubbleMenuPlugin({pluginKey: 'bubbleMenu', editor, element: textBubble, options: {onShow: () => this.refreshControls()}, shouldShow: ({view, element, state: documentState, from, to}) => state.editing.value && (view.hasFocus() || element.contains(document.activeElement)) && from !== to && !(isTextSelection(documentState.selection) && !documentState.doc.textBetween(from, to).length) && !editor.isActive('image') && !editor.isActive('taskLink')}))
		editor.registerPlugin(BubbleMenuPlugin({pluginKey: 'imageBubbleMenu', editor, element: imageBubble, shouldShow: () => state.editing.value && editor.isActive('image')}))
		const draft = loadEditorDraft(this.options.storageKey)
		state.editing.value = isEditorContentEmpty(this.options.value) && this.options.canWrite
		if (draft && isEditorContentEmpty(this.options.value) && this.options.canWrite) { editor.commands.setContent(draft, {emitUpdate: false, parseOptions: {preserveWhitespace: true}}); state.editing.value = true; this.changed() }
		this.refreshMode()
		state.key = event => { const target = event.target as HTMLElement; if (! (this.options.editShortcut ?? 'KeyE') || eventToShortcutString(event) !== (this.options.editShortcut ?? 'KeyE') || !this.options.canWrite || target.matches('input,textarea,[contenteditable="true"]') || target.closest('.ProseMirror') || target.shadowRoot?.activeElement) return; this.edit() }; document.addEventListener('keydown', state.key)
	},
	live() { const state = this.getState(); return !state.life.signal.aborted && state.editor && !state.editor.isDestroyed ? state.editor : undefined },
	changed() { const editor = this.live(); if (!editor) return; const value = editor.getHTML(); if (value === '<p></p>' && !this.options.value) return; this.getState().dirty.value = value !== this.getState().lastSaved; saveEditorDraft(this.options.storageKey, value); this.options.value = value; this.options.changed(value); this.refreshControls() },
	refreshControls() { const state = this.getState(), editor = this.live(); if (!editor) return; state.toolbar?.refresh(); const save = (this.getUI('save')![0] as HTMLButtonElement); if (save) save.disabled = !state.dirty.value; state.menus.flatMap(menu => Array.from(menu.querySelectorAll<HTMLButtonElement>('[data-mark]'))).forEach(button => { const active = editor.isActive(button.dataset.mark!); button.classList.toggle('is-active', active); if (button.dataset.mark !== 'link') button.setAttribute('aria-pressed', String(active)) }) },
	refreshActions() { const list = (this.getUI('actions')![0] as HTMLElement)!; list.querySelectorAll('li:not([data-edit-item]):not([data-action-save-item])').forEach(item => item.remove()); for (const action of this.options.bottomActions ?? []) { const li = document.createElement('li'); render(html`<button type="button" class="base-button base-button--type-button" @click=${action.action}>${action.title}</button>`, li); list.append(li) }; this.refreshMode() },
	refreshMode() { const state = this.getState(), editing = state.editing.value && this.options.canWrite; state.editing.value = editing; state.menus.forEach(menu => { menu.style.display = editing ? '' : 'none' }); const editor = this.live(); if (editor && editor.isEditable !== editing) editor.setEditable(editing, false); (this.getUI('wrapper')![0] as HTMLElement)?.classList.toggle('tiptap__wrapper-is-editing', editing); (this.getUI('editor')![0] as HTMLElement)?.classList.toggle('tiptap__editor-is-edit-enabled', editing); for (const [name, show] of [['toolbarHost', editing], ['save', editing && this.options.showSave !== false && !this.options.bottomActions?.length], ['actionSave', editing && this.options.showSave !== false && Boolean(this.options.bottomActions?.length)], ['editItem', !editing && this.options.showEdit !== false && (this.options.canWrite || Boolean(this.options.bottomActions?.length))], ['actions', Boolean(this.options.bottomActions?.length) || (!editing && this.options.canWrite)]] as const) { const element = this.getUI(name)![0] as HTMLElement | undefined; if (element) element.hidden = !show }; this.refreshControls() },
	edit() { if (!this.options.canWrite) return; this.getState().editing.value = true; this.refreshMode(); this.live()?.view.focus() },
	discard() { const state = this.getState(); this.live()?.commands.setContent(state.lastSaved, {emitUpdate: false, parseOptions: {preserveWhitespace: true}}); state.dirty.value = false; state.editing.value = false; clearEditorDraft(this.options.storageKey); this.options.changed(state.lastSaved); this.refreshMode() },
	async saveNow() { const state = this.getState(), editor = this.live(), signal = state.inputLife.signal, submitted = editor?.getHTML(); if (!editor || !this.options.canWrite) return; try { const acknowledged = await this.options.save(submitted!); if (signal.aborted || !this.options.canWrite || this.live() !== editor || acknowledged !== submitted || submitted !== editor.getHTML()) return; this.acceptSaved(acknowledged!); state.editing.value = false; this.refreshMode() } catch (error) { if (!signal.aborted && this.live() === editor && this.options.canWrite && (error as Error).name !== 'AbortError' && (error as {code?: string}).code !== 'ERR_CANCELED') this.options.context.reportError(error) } },
	setReplyContent(value: string) { this.live()?.commands.setContent(value, {emitUpdate: false, parseOptions: {preserveWhitespace: true}}); this.getState().editing.value = true; this.changed(); this.refreshMode(); this.live()?.commands.focus('end') },
	resetContent() { this.live()?.commands.setContent('', {emitUpdate: false}); this.options.value = ''; this.getState().lastSaved = ''; this.getState().dirty.value = false; clearEditorDraft(this.options.storageKey); this.getState().editing.value = true; this.refreshMode() },
	acceptSaved(value: string) { const state = this.getState(); state.lastSaved = value; if (this.live()?.getHTML() === value) { state.dirty.value = false; clearEditorDraft(this.options.storageKey); this.refreshControls() } },
	updateInputs(value: string, canWrite: boolean, projectId: number) { const state = this.getState(), projectChanged = this.options.projectId !== projectId; this.options.value = value; this.options.canWrite = canWrite; this.options.projectId = projectId; if (!state.dirty.value) { state.lastSaved = value; if (this.live()?.getHTML() !== value) this.live()?.commands.setContent(value, {emitUpdate: false, parseOptions: {preserveWhitespace: true}}) }; if (!canWrite || projectChanged) { state.cancelSuggestions?.(); state.inputLife.abort(); state.inputLife = new AbortController(); this.hideTip() }; this.refreshMode() },
	escape(event: KeyboardEvent) { if (this.options.enableDiscard !== false && event.key === 'Escape' && (event.target as HTMLElement).closest('.ProseMirror')) event.stopPropagation() },
	doubleClick(event: MouseEvent) { if (event.target instanceof HTMLImageElement && event.target.dataset.src !== undefined && event.target.src.startsWith('blob:')) return; this.edit() },
	contentClick(event: MouseEvent) { if (this.getState().editing.value) { const editor = this.live(); if (editor && !editor.view.hasFocus()) editor.view.focus(); return }; const target = event.target; if (target instanceof HTMLImageElement && target.dataset.src !== undefined && target.src.startsWith('blob:')) this.lightbox(target.src, target.alt); if (target instanceof HTMLElement && target.tagName === 'P' && target.closest('li[data-type="taskItem"]')) target.closest('li')?.querySelector<HTMLInputElement>('input[type=checkbox]')?.click() },
	mark(mark: string, event: MouseEvent) { if (mark === 'link') { void this.link(event); return }; const editor = this.live(); if (!editor) return; const chain = editor.chain().focus(); (chain as unknown as Record<string, () => typeof chain>)[`toggle${mark[0].toUpperCase() + mark.slice(1)}`]().run() },
	async link(event: MouseEvent) { const editor = this.live(), signal = this.getState().inputLife.signal; if (!editor || !this.options.canWrite) return; const value = await inputPrompt((event.currentTarget as HTMLElement).getBoundingClientRect(), this.options.context.t('input.editor.urlPlaceholder'), editor.getAttributes('link').href || '', editor, signal); if (value === null || signal.aborted || !this.live()) return; const chain = editor.chain().focus().extendMarkRange('link'); if (!value) chain.unsetLink().run(); else chain.setLink({href: value, target: '_blank'}).run() },
	async image(event: Event) { if(this.options.upload){(this.getUI('upload')![0] as HTMLInputElement)?.click();return};const editor=this.live(),signal=this.getState().inputLife.signal;if(!editor||!this.options.canWrite)return;const url=await inputPrompt((event.currentTarget as HTMLElement).getBoundingClientRect(),this.options.context.t('input.editor.urlPlaceholder'),'',editor,signal);if(url&&!signal.aborted&&this.live())this.live()!.chain().focus().setImage({src:url}).run() },
	uploadChanged() { const input = (this.getUI('upload')![0] as HTMLInputElement)!; if (input.files?.length) void this.uploadFiles(input.files); input.value = '' },
	async uploadFiles(files: File[] | FileList) { const state = this.getState(), signal = state.inputLife.signal; if (!this.options.canWrite || signal.aborted) return; try { if(!this.options.upload)throw new Error('Can\'t add files here');const urls = await this.options.upload(files, signal); if (signal.aborted || !this.options.canWrite || !this.live()) return; for (const url of urls) { if (this.live()!.isEmpty) this.live()!.chain().focus().insertContent('<p>UPLOAD_PLACEHOLDER</p>').run(); this.live()!.chain().focus().setImage({src: url}).run() }; this.live()!.commands.setContent(this.live()!.getHTML().replace('<p>UPLOAD_PLACEHOLDER</p>', ''), {emitUpdate: false, parseOptions: {preserveWhitespace: true}}); this.changed(); if (urls.length === 1) { let position = -1; this.live()!.state.doc.descendants((node, pos) => { if (node.type.name === 'image' && (node.attrs.src === urls[0] || node.attrs['data-src'] === urls[0])) position = pos }); if (position >= 0) { this.live()!.chain().setNodeSelection(position).run(); await Promise.resolve(); const node = this.live()?.view.nodeDOM(position) as HTMLElement | null; await this.promptAlt(node?.getBoundingClientRect() ?? new DOMRect(), '', signal); if (signal.aborted || !this.options.canWrite || !this.live()) return; this.live()?.chain().setTextSelection(position + 1).run() } } } catch (error) { if (!signal.aborted && this.live()) this.options.context.reportError(error) } },
	async promptAlt(rect: DOMRect, previous: string, requestSignal?: AbortSignal) { const signal = requestSignal ?? this.getState().inputLife.signal, editor = this.live(); if (!editor || signal.aborted || !this.options.canWrite) return; const alt = await inputPrompt(rect, this.options.context.t('input.editor.altTextPlaceholder'), previous, editor, signal); if (alt !== null && !signal.aborted && this.options.canWrite && this.live() === editor) editor.chain().focus().updateAttributes('image', {alt}).run() },
	alt(event: MouseEvent) { return this.promptAlt((event.currentTarget as HTMLElement).getBoundingClientRect(), this.live()?.getAttributes('image').alt || '') },
	tip(trigger: HTMLElement, text: string) { this.hideTip(); const state = this.getState(), host = document.createElement('div'); getTopLayerContainer(this.el).append(host); state.tipHost = host; state.tip = new Region({el: host}); state.tip.show(new AvatarTooltipView({trigger, text})) },
	hideTip() { const state = this.getState(); state.tip?.destroy(); state.tipHost?.remove(); state.tip = undefined; state.tipHost = undefined },
	lightbox(url: string, alt: string) { const state = this.getState(); const close = () => { state.lightbox?.destroy(); state.lightboxHost?.remove(); state.lightbox = undefined; state.lightboxHost = undefined }; close(); const host = document.createElement('div'); host.className = 'native-editor-surface'; document.body.append(host); state.lightboxHost = host; state.lightbox = new Region({el: host}); state.lightbox.show(new EditorLightboxView({url, alt, t: this.options.context.t, close})) },
	onBeforeDestroy() { const state = this.getState(); state.life.abort(); state.inputLife.abort(); if (state.key) document.removeEventListener('keydown', state.key); this.hideTip(); state.lightbox?.destroy(); state.lightboxHost?.remove(); state.editor?.destroy() },
}).setDomApi(LitDomApi)
