import { afterEach, expect, it, vi } from 'vitest';
import { Collection } from '@mnjs/data';
import { NavigationView } from './navigation';
import {LogoView} from '@/shared/logo'
import { SessionApplication } from './session';
import UserModel from '@/models/user';
import ProjectModel from '@/models/project';
import ProjectService from '@/services/project';
const owners: {
    destroy: () => unknown;
}[] = [];
afterEach(() => { owners.splice(0).forEach(owner => owner.destroy()); vi.restoreAllMocks(); document.body.replaceChildren(); localStorage.clear(); });
function mount(projects: ProjectModel[]) { const session = new SessionApplication(); session.getState().set({ user: new UserModel({ id: 1 }), transition: 1 }); owners.push(session); const collection = new Collection(projects.map(project => ({ id: project.id, project }))), view = new NavigationView({ session, projects: collection, navigate: vi.fn() }); owners.push(view); view.render(); document.body.append(view.el); return { view, collection }; }
it('readonly projects have no favorite reorder or settings controls', () => { const { view } = mount([new ProjectModel({ id: 1, maxPermission: 0, title: 'Readonly' })]); expect(view.el.querySelector('[data-favorite]')).toBeNull(); expect(view.el.querySelector('.handle')).toBeNull(); expect(view.el.querySelector('[data-project-menu-host]')).toBeNull(); });
it('failed favorite keeps the previous accepted value and shows recovery feedback', async () => { vi.spyOn(ProjectService.prototype, 'update').mockRejectedValue(new Error('fixture unavailable')); const { view, collection } = mount([new ProjectModel({ id: 1, maxPermission: 2 })]); await view.save(new ProjectModel({ id: 1, maxPermission: 2, isFavorite: true })); expect((collection.get(1)!.get('project') as ProjectModel).isFavorite).toBe(false); expect(view.el.querySelector('[role=alert]')?.textContent).toContain('fixture unavailable'); expect(view.getState().busy.size).toBe(0); });
it('destroy prevents an ignored-abort project update from entering the catalog', async () => { let resolve!: (project: ProjectModel) => void, signal: AbortSignal | undefined; vi.spyOn(ProjectService.prototype, 'update').mockImplementation((_project, request) => { signal = request; return new Promise(ready => resolve = ready); }); const { view, collection } = mount([new ProjectModel({ id: 1, maxPermission: 2 })]); const pending = view.save(new ProjectModel({ id: 1, maxPermission: 2, isFavorite: true })); view.destroy(); expect(signal?.aborted).toBe(true); resolve(new ProjectModel({ id: 1, isFavorite: true })); await pending; expect((collection.get(1)!.get('project') as ProjectModel).isFavorite).toBe(false); });
it('ordering preserves inaccessible parent ownership and refuses readonly targets', async () => { const update = vi.spyOn(ProjectService.prototype, 'update').mockImplementation(async (project) => project); const { view } = mount([new ProjectModel({ id: 1, maxPermission: 2, parentProjectId: 99 }), new ProjectModel({ id: 2, maxPermission: 0 })]); await view.move(1, 2); expect(update).not.toHaveBeenCalled(); await view.move(1, 0); expect(update.mock.calls[0][0].parentProjectId).toBe(99); });
it('serialized sidebar width writes preserve a later drag until it is accepted',async()=>{let resolve!:(settings:import('@/modelTypes/IUserSettings').IUserSettings)=>void;const {default:UserSettingsService}=await import('@/services/userSettings');const write=vi.spyOn(UserSettingsService.prototype,'update').mockImplementationOnce(()=>new Promise(ready=>resolve=ready)).mockImplementation(async settings=>settings);const {view}=mount([]);view.onAttach();view.getState().width=370;const first=view.saveWidth();await Promise.resolve();view.getState().width=430;const second=view.saveWidth();expect(write).toHaveBeenCalledTimes(1);resolve(write.mock.calls[0][0]);await first;expect(view.getState().width).toBe(430);await second;expect(write.mock.calls.map(call=>call[0].frontendSettings.sidebarWidth)).toEqual([370,430]);expect(view.getState().width).toBe(430)})

it('catalog and route publication retain the logo View, and navigation teardown owns it', () => { const {view}=mount([]); const logo=view.getChildView('logo') as InstanceType<typeof LogoView>; view.publish(); view.updateRoute('/projects',0); expect(view.getChildView('logo')).toBe(logo); view.destroy(); expect(logo.isDestroyed()).toBe(true) })
