import {test,expect} from './fixtures'
import {TeamFactory} from '../../frontend/tests/factories/team'
import {TeamMemberFactory} from '../../frontend/tests/factories/team_member'
import {UserFactory} from '../../frontend/tests/factories/user'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {LabelFactory} from '../../frontend/tests/factories/labels'
import {LabelTaskFactory} from '../../frontend/tests/factories/label_task'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
async function headers(page){return {Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('token'))}`}}
async function team(page,apiContext,id=1){const response=await apiContext.get(`teams/${id}`,{headers:await headers(page)});expect(response.ok()).toBe(true);return response.json()}
async function labels(page,apiContext){const response=await apiContext.get('../v2/labels?per_page=1000',{headers:await headers(page)});expect(response.ok()).toBe(true);return (await response.json()).items}
const editor=page=>page.locator('.column.is-4').filter({has:page.getByText('Edit Label',{exact:true})})
const editLabel=(page,title:string)=>page.locator('.labels-list .tag').filter({hasText:title}).getByRole('button',{name:'Edit Label',exact:true}).click()
const confirm=page=>page.getByRole('dialog').last().getByRole('button',{name:'Do it!',exact:true}).click()
async function chooseUser(page){const input=page.getByRole('combobox');await input.fill('organization-user');await input.press('ArrowLeft');await expect(page.getByRole('option').filter({hasText:'Organization User'})).toBeVisible();await input.press('ArrowDown');await page.keyboard.press('Enter')}
test.beforeEach(async({authenticatedPage:page})=>{void page;await UserFactory.create(1,{id:2,username:'organization-user',name:'Organization User'},false);await TeamFactory.create(1,{id:1,name:'Organization team'});await TeamMemberFactory.create(1,{id:1,team_id:1,user_id:1,admin:true});await ProjectFactory.create(1,{title:'Organization project'});await createDefaultViews(1);await TaskFactory.create(2,{title:(id:number)=>id===1?'Labeled task':'Plain task'});await LabelFactory.create(1,{title:'Owned label',description:'',hex_color:'1973ff'});await LabelTaskFactory.create(1,{label_id:1,task_id:1})})
for(const width of [1440,390])test(`team directory creation metadata and public setting persist ${width}`,async({authenticatedPage:page,apiContext},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/teams');await expect(page.locator('ul.teams')).toContainText('Organization team');await page.getByRole('link',{name:'Create a team',exact:true}).first().click();await page.locator('#teamName').fill('Created organization team');await page.getByText('Make the team publicly discoverable.',{exact:false}).click();await page.locator('#teamName').press('Enter');await expect(page).toHaveURL(/\/teams\/\d+\/edit$/);const id=Number(new URL(page.url()).pathname.split('/')[2]);expect(await team(page,apiContext,id)).toMatchObject({name:'Created organization team',is_public:true});expect((await team(page,apiContext,id)).members).toEqual(expect.arrayContaining([expect.objectContaining({username:'migration-reviewer',admin:true})]));await page.getByLabel('Team Name',{exact:true}).fill('Updated organization team');await page.locator('.tiptap__editor .ProseMirror').fill('Organization description');await Promise.all([page.waitForResponse(response=>response.url().endsWith(`/api/v1/teams/${id}`)&&response.request().method()==='POST'),page.getByRole('button',{name:'Save',exact:true}).click()]);expect(await team(page,apiContext,id)).toMatchObject({name:'Updated organization team',is_public:true});expect((await team(page,apiContext,id)).description).toContain('Organization description');await page.reload();await expect(page.getByLabel('Team Name',{exact:true})).toHaveValue('Updated organization team');if(width > 769) await expect(page.getByLabel('Team Name',{exact:true})).toBeFocused();else await expect(page.getByLabel('Team Name',{exact:true})).not.toBeFocused();await expect.poll(()=>page.locator('.fancy-checkbox input:checked + svg polyline').evaluate(element=>Number.parseFloat(getComputedStyle(element).strokeDashoffset))).toBe(42);await info.attach(`team-edit-${width}`,{body:await page.screenshot(),contentType:'image/png'})
})
test('team member add toggle remove and team delete persist with cancellation',async({authenticatedPage:page,apiContext},info)=>{
 await page.goto('/teams/1/edit');await chooseUser(page);await page.getByRole('button',{name:'Add to team',exact:true}).click();await expect(page.locator('table')).toContainText('Organization User');expect((await team(page,apiContext)).members.find(member=>member.username==='organization-user').admin).toBe(false);await page.getByRole('button',{name:'Make Admin',exact:true}).click();await expect(page.getByRole('button',{name:'Make Member',exact:true})).toBeVisible();expect((await team(page,apiContext)).members.find(member=>member.username==='organization-user').admin).toBe(true);await page.getByRole('button',{name:'Make Member',exact:true}).click();await expect(page.getByRole('button',{name:'Make Admin',exact:true})).toBeVisible();expect((await team(page,apiContext)).members.find(member=>member.username==='organization-user').admin).toBe(false);await page.getByRole('button',{name:'Remove a user from the team',exact:true}).click();await page.getByRole('dialog').last().getByRole('button',{name:'Cancel',exact:true}).click();expect((await team(page,apiContext)).members).toHaveLength(2);await page.getByRole('button',{name:'Remove a user from the team',exact:true}).click();await confirm(page);await expect(page.locator('table')).not.toContainText('Organization User');expect((await team(page,apiContext)).members).toHaveLength(1);await page.getByRole('button',{name:'Delete the team',exact:true}).click();await info.attach('team-delete',{body:await page.screenshot(),contentType:'image/png'});await confirm(page);await expect(page).toHaveURL(/\/teams$/);const response=await apiContext.get('teams/1',{headers:await headers(page)});expect(response.status()).toBe(403);const directory=await apiContext.get('teams',{headers:await headers(page)});expect(directory.ok()).toBe(true);expect((await directory.json()).some(item=>item.id===1)).toBe(false)
})
test('nonadmin member inspects members but cannot mutate and can leave actual team',async({authenticatedPage:page,apiContext,currentUser})=>{
 await TeamMemberFactory.create(2,{id:(id:number)=>id,team_id:1,user_id:(id:number)=>id,admin:(id:number)=>id===2});await page.goto('/teams/1/edit');await expect(page.locator('table')).toContainText('Organization User');await expect(page.getByLabel('Team Name',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Add to team',exact:true})).toHaveCount(0);const forbidden=await apiContext.post('teams/1',{headers:await headers(page),data:{name:'Denied update'}});expect(forbidden.status()).toBe(403);await page.getByRole('button',{name:'Leave team',exact:true}).click();await page.getByRole('dialog').last().getByRole('button',{name:'Cancel',exact:true}).click();expect((await team(page,apiContext)).members.some(member=>member.id===currentUser.id)).toBe(true);await page.getByRole('button',{name:'Leave team',exact:true}).click();await confirm(page);await expect(page).toHaveURL(/\/$/);const denied=await apiContext.get('teams/1',{headers:await headers(page)});expect(denied.status()).toBe(403)
})
test('team rejected writes retain metadata draft and accepted member permission',async({authenticatedPage:page,apiContext})=>{
 await TeamMemberFactory.create(2,{id:(id:number)=>id,team_id:1,user_id:(id:number)=>id,admin:(id:number)=>id===1});await page.goto('/teams/1/edit');const name=page.getByLabel('Team Name',{exact:true});await name.fill('Retained team draft');let failed=false;await page.route('**/api/v1/teams/1',route=>{if(route.request().method()==='POST'&&!failed){failed=true;return route.fulfill({status:503,json:{message:'Fixture team unavailable'}})}return route.continue()});await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Fixture'}).first()).toContainText('Fixture team unavailable');await expect(name).toHaveValue('Retained team draft');expect((await team(page,apiContext)).name).toBe('Organization team');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:'Save',exact:true})).toBeEnabled();expect((await team(page,apiContext)).name).toBe('Retained team draft');await page.route('**/api/v1/teams/1/members/organization-user/admin',route=>route.fulfill({status:503,json:{message:'Fixture admin unavailable'}}));await page.getByRole('button',{name:'Make Admin',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Fixture'}).first()).toContainText('Fixture admin unavailable');await expect(page.getByRole('button',{name:'Make Admin',exact:true})).toBeVisible();expect((await team(page,apiContext)).members.find(member=>member.username==='organization-user').admin).toBe(false)
})
for(const width of [1440,390])test(`label create color metadata filter navigation and deletion persist ${width}`,async({authenticatedPage:page,apiContext},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/labels');await expect(page.locator('.labels-list')).toContainText('Owned label');const banner=page.getByRole('button',{name:'Close banner',exact:true});if(await banner.isVisible())await banner.click();await page.getByRole('link',{name:'New label',exact:true}).click();await page.locator('#labelTitle').fill('Created label');await page.locator('dialog input[type=color]').fill('#00db60');await page.locator('#labelTitle').press('Enter');await expect(page).toHaveURL(/\/labels$/);await expect(page.locator('.labels-list')).toContainText('Created label');const created=(await labels(page,apiContext)).find(label=>label.title==='Created label');expect(created.hex_color).toBe('00db60');await editLabel(page,'Created label');await editor(page).getByLabel('Title',{exact:true}).fill('Renamed label');await editor(page).locator('.tiptap__editor .ProseMirror').fill('Label description');await editor(page).getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.labels-list')).toContainText('Renamed label');const renamed=(await labels(page,apiContext)).find(label=>label.id===created.id);expect(renamed).toMatchObject({title:'Renamed label',hex_color:'00db60'});expect(renamed.description).toContain('Label description');await info.attach(`labels-${width}`,{body:await page.screenshot(),contentType:'image/png'});await page.locator('.labels-list .tag').filter({hasText:'Owned label'}).locator('span').first().click();await expect(page).toHaveURL(/\?labels=1$/);await expect(page.locator('.tasks')).toContainText('Labeled task');await expect(page.locator('.tasks')).not.toContainText('Plain task');await page.goto('/labels');await editLabel(page,'Owned label');await editor(page).getByRole('button',{name:'Delete this label',exact:true}).click();await page.getByRole('dialog').last().getByRole('button',{name:'Cancel',exact:true}).click();expect((await labels(page,apiContext)).some(label=>label.id===1)).toBe(true);await editor(page).getByRole('button',{name:'Delete this label',exact:true}).click();await confirm(page);await expect(page.locator('.labels-list')).not.toContainText('Owned label');expect((await labels(page,apiContext)).some(label=>label.id===1)).toBe(false);const task=await apiContext.get('tasks/1',{headers:await headers(page)});expect(task.ok()).toBe(true);expect((await task.json()).labels??[]).toEqual([])
})
test('another creators visible label has no edit control and backend denies writes',async({authenticatedPage:page,apiContext})=>{
 await LabelFactory.create(1,{id:2,title:'Other label',created_by_id:2,hex_color:'ff4136'},false);await LabelTaskFactory.create(1,{id:2,label_id:2,task_id:1},false);await page.goto('/labels');const label=page.locator('.labels-list .tag').filter({hasText:'Other label'});await expect(label).toBeVisible();await expect(label.getByRole('button',{name:'Edit Label',exact:true})).toHaveCount(0);for(const method of ['put','delete']){const denied=await apiContext[method]('../v2/labels/2',{headers:await headers(page),data:method==='put'?{title:'Denied label'}:undefined});expect(denied.status()).toBe(403)}expect((await labels(page,apiContext)).find(label=>label.id===2).title).toBe('Other label')
})
test('label rejected save retains focused draft and retry updates real label',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/labels');await editLabel(page,'Owned label');const title=editor(page).getByLabel('Title',{exact:true});await title.fill('Retained label draft');let failed=false;await page.route('**/api/v2/labels/1',route=>{if(!failed&&route.request().method()==='PUT'){failed=true;return route.fulfill({status:503,json:{message:'Fixture label unavailable'}})}return route.continue()});await editor(page).getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Fixture'}).first()).toContainText('Fixture label unavailable');await expect(title).toHaveValue('Retained label draft');expect((await labels(page,apiContext))[0].title).toBe('Owned label');await title.focus();await title.press('Enter');await expect(page.locator('.labels-list')).toContainText('Retained label draft');expect((await labels(page,apiContext))[0].title).toBe('Retained label draft')
})
test('delayed team save retains later focused draft and navigation loads separate team',async({authenticatedPage:page,apiContext})=>{
 await TeamFactory.create(1,{id:2,name:'Second team'},false);await TeamMemberFactory.create(1,{id:2,team_id:2,user_id:1,admin:true},false);await page.goto('/teams/1/edit');const name=page.getByLabel('Team Name',{exact:true});await name.fill('Submitted team');let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve);await page.route('**/api/v1/teams/1',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{})});await page.getByRole('button',{name:'Save',exact:true}).click();await started;await name.fill('Later team draft');await name.focus();release();await expect(page.getByRole('button',{name:'Save',exact:true})).toBeEnabled();await expect(name).toHaveValue('Later team draft');await expect(name).toBeFocused();expect((await team(page,apiContext)).name).toBe('Submitted team');await page.evaluate(()=>{history.pushState({},'','/teams/2/edit');window.dispatchEvent(new PopStateEvent('popstate'))});await expect(page.getByLabel('Team Name',{exact:true})).toHaveValue('Second team');await expect(page.getByLabel('Team Name',{exact:true})).not.toHaveValue('Submitted team')
})
test('stopping team edit during accepted write keeps next team and notices isolated',async({authenticatedPage:page,apiContext})=>{
 await TeamFactory.create(1,{id:2,name:'Second team'},false);await TeamMemberFactory.create(1,{id:2,team_id:2,user_id:1,admin:true},false);await page.goto('/teams/1/edit');await page.getByLabel('Team Name',{exact:true}).fill('Accepted old team');let release!:()=>void,ready!:()=>void,finished!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve),done=new Promise<void>(resolve=>finished=resolve);await page.route('**/api/v1/teams/1',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{});finished()});await page.getByRole('button',{name:'Save',exact:true}).click();await started;await page.evaluate(()=>{history.pushState({},'','/teams/2/edit');window.dispatchEvent(new PopStateEvent('popstate'))});await expect(page.getByLabel('Team Name',{exact:true})).toHaveValue('Second team');release();await done;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await expect(page.getByLabel('Team Name',{exact:true})).toHaveValue('Second team');await expect(page.getByRole('alert').filter({hasText:'The team was successfully'})).toHaveCount(0);expect((await team(page,apiContext)).name).toBe('Accepted old team')
})
test('late startup label catalog cannot resurrect renamed metadata',async({authenticatedPage:page,apiContext})=>{
 let first=true,release!:()=>void,ready!:()=>void,finished!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve),done=new Promise<void>(resolve=>finished=resolve);await page.route('**/api/v2/labels?*',async route=>{if(!first){await route.continue();return}first=false;const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{});finished()});await page.goto('/labels');await started;await editLabel(page,'Owned label');await editor(page).getByLabel('Title',{exact:true}).fill('Accepted catalog label');await editor(page).getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.labels-list')).toContainText('Accepted catalog label');release();await done;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await expect(page.locator('.labels-list')).toContainText('Accepted catalog label');await expect(page.locator('.labels-list')).not.toContainText('Owned label');expect((await labels(page,apiContext))[0].title).toBe('Accepted catalog label')
})

for(const width of [1440,390])for(const [path,link,id] of [['/teams','Create a team','teamName'],['/labels','New label','labelTitle']])test(`creation dialog preserves reference close focus and Escape cleans up ${path} ${width}`,async({authenticatedPage:page})=>{
 await page.setViewportSize({width,height:900});await page.goto(path);await page.getByRole('link',{name:link,exact:true}).first().click();await expect(page.locator(`#${id}`)).toBeVisible();await expect(page.getByRole('button',{name:width > 768 ? 'Close dialog' : 'Close',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page).toHaveURL(new RegExp(`${path}$`));await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('link',{name:link,exact:true}).first()).toBeFocused()
})
