import {test,expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {SavedFilterFactory} from '../../frontend/tests/factories/saved_filter'
import {UserFactory} from '../../frontend/tests/factories/user'
import {UserProjectFactory} from '../../frontend/tests/factories/users_project'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
const submit=page=>page.locator('dialog').getByRole('button',{name:/^(Create|Save|Do it!)$/})
const title=page=>page.locator('dialog input').filter({visible:true}).first()
async function auth(page){return {Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('token'))}`}}
async function project(page,apiContext,id=1){const response=await apiContext.get(`projects/${id}`,{headers:await auth(page)});expect(response.ok()).toBe(true);return response.json()}
async function preferences(apiContext,userToken,settings){const headers={Authorization:`Bearer ${userToken}`},current=await apiContext.get('user',{headers});expect(current.ok()).toBe(true);const initial=(await current.json()).settings;const response=await apiContext.post('user/settings/general',{headers,data:{...initial,language:'en',timezone:'UTC',...settings,frontend_settings:{...initial.frontend_settings,...settings.frontend_settings}}});expect(response.ok()).toBe(true)}
test.beforeEach(async({authenticatedPage:page})=>{void page;await ProjectFactory.create(2,{title:(id:number)=>id===1?'Management parent':'Management child',parent_project_id:(id:number)=>id===1?0:1});await createDefaultViews(1);await createDefaultViews(2,5)})
for(const width of [1440,390])test(`home default project quick add pending tasks recent history and preference reload ${width}`,async({authenticatedPage:page,apiContext,userToken},info)=>{
 await page.setViewportSize({width,height:900});await TaskFactory.create(2,{title:(id:number)=>id===1?'Pending overview':'Completed overview',done:(id:number)=>id===2});await preferences(apiContext,userToken,{default_project_id:2});await page.goto('/');await expect(page.locator('.tasks')).toContainText('Pending overview');await expect(page.locator('.tasks')).not.toContainText('Completed overview');await page.getByPlaceholder('Add a task…').fill('Home default consumer');await page.getByPlaceholder('Add a task…').press('Enter');await expect(page.locator('.tasks')).toContainText('Home default consumer');const tasks=await apiContext.get('projects/2/tasks',{headers:await auth(page)});expect(tasks.ok()).toBe(true);expect((await tasks.json()).some(task=>task.title==='Home default consumer')).toBe(true);await page.goto('/projects/1/1');await expect(page.locator('.list-view')).toBeVisible();await page.goto('/');await expect(page.locator('.project-grid')).toContainText('Management parent');await info.attach(`home-${width}`,{body:await page.screenshot(),contentType:'image/png'});await preferences(apiContext,userToken,{frontend_settings:{show_last_viewed:false}});await page.reload();await expect(page.getByText('Last viewed',{exact:true})).not.toBeVisible()
})
test('project directory creates a child with actual views and reloads navigation',async({authenticatedPage:page,apiContext},info)=>{
 await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management child');await page.locator('.action-buttons').getByRole('link',{name:'New project',exact:true}).click();await expect(page.locator('dialog')).toBeVisible();await page.locator('input[name=projectTitle]').fill('Created project');const parent=page.getByRole('combobox',{name:/Parent Project|Type to search for a project/}).first();await parent.fill('Management parent');await parent.press('ArrowLeft');await expect(page.getByRole('option',{name:/Management parent/})).toBeVisible();await parent.press('ArrowDown');await page.keyboard.press('Enter');await submit(page).click();await expect(page).toHaveURL(/\/projects\/\d+\/\d+$/);const id=Number(new URL(page.url()).pathname.split('/')[2]);const created=await project(page,apiContext,id);expect(created).toMatchObject({title:'Created project',parent_project_id:1});expect(created.views.length).toBe(4);await expect(page.locator('.project-title-wrapper')).toContainText('Created project');await page.reload();await expect(page.locator('.project-title-wrapper')).toContainText('Created project');await info.attach('created-project',{body:await page.screenshot(),contentType:'image/png'})
})
test('edit fields persist through actual backend and archive toggle filters directory',async({authenticatedPage:page,apiContext},info)=>{
 await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management parent');await page.goto('/projects/1/settings/edit');await expect(page.locator('dialog')).toBeVisible();await title(page).fill('Renamed parent');await page.getByLabel('Project Identifier',{exact:true}).fill('REVIEW');await page.locator('dialog .tiptap__editor .ProseMirror').click();await page.locator('dialog .tiptap__editor .ProseMirror').fill('Project description');await submit(page).click();await expect(page.locator('dialog')).not.toBeVisible();const edited=await project(page,apiContext);expect(edited.title).toBe('Renamed parent');expect(edited.identifier).toBe('REVIEW');expect(edited.description).toContain('Project description');await page.goto('/projects/1/settings/archive');await page.getByRole('button',{name:'Do it!',exact:true}).click();await expect(page.locator('dialog')).not.toBeVisible();expect((await project(page,apiContext)).is_archived).toBe(true);await page.goto('/projects');await expect(page.locator('.project-grid')).not.toContainText('Renamed parent');await page.getByText('Show Archived',{exact:true}).click();await expect(page.getByLabel('Show Archived')).toBeChecked();await expect(page.locator('.project-grid')).toContainText('Renamed parent');await info.attach('archived-project-directory',{body:await page.screenshot(),contentType:'image/png'});await page.goto('/projects/1/settings/archive');await page.getByRole('button',{name:'Do it!',exact:true}).click();await expect(page.locator('dialog')).not.toBeVisible();expect((await project(page,apiContext)).is_archived).toBe(false)
})
test('delete cancel preserves data then actual delete removes descendants and tasks',async({authenticatedPage:page,apiContext},info)=>{
 await TaskFactory.create(2,{project_id:(id:number)=>id,title:'Delete fixture task'});await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management parent');await page.goto('/projects/1/settings/delete');await expect(page.locator('dialog')).toContainText('2 tasks');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('dialog')).not.toBeVisible();expect((await project(page,apiContext)).title).toBe('Management parent');await page.goto('/projects/1/settings/delete');await info.attach('delete-confirmation',{body:await page.screenshot(),contentType:'image/png'});await page.getByRole('button',{name:'Do it!',exact:true}).click();await expect(page).toHaveURL(/\/$/);for(const id of [1,2]){const response=await apiContext.get(`projects/${id}`,{headers:await auth(page)});expect(response.status()).toBe(404)}await expect(page.locator('.menu-container')).not.toContainText('Management parent');await expect(page.locator('.menu-container')).not.toContainText('Management child')
})
test('failed edit retains focused draft and retry saves actual data',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management parent');await page.goto('/projects/1/settings/edit');await title(page).fill('Retained edit');await title(page).focus();let blocked=false;await page.route('**/api/v1/projects/1',async route=>{if(route.request().method()==='POST'&&!blocked){blocked=true;await route.fulfill({status:503,json:{message:'Fixture project write failed'}})}else await route.continue()});await submit(page).click();await expect(page.getByRole('alert')).toContainText('Fixture project write failed');await expect(title(page)).toHaveValue('Retained edit');expect((await project(page,apiContext)).title).toBe('Management parent');await title(page).focus();await title(page).press('Enter');await expect(page.locator('dialog')).not.toBeVisible();expect((await project(page,apiContext)).title).toBe('Retained edit')
})
test('overview saved filter preference uses actual saved project tasks',async({authenticatedPage:page,apiContext,userToken})=>{
 await TaskFactory.create(2,{title:(id:number)=>id===1?'Saved matching task':'Unmatched task',project_id:(id:number)=>id});await SavedFilterFactory.create(1,{filters:'{"filter":"project = 2","filter_include_nulls":false,"s":""}'});await preferences(apiContext,userToken,{frontend_settings:{filter_id_used_on_overview:-2}});await page.goto('/');await expect(page.locator('.tasks')).toContainText('Unmatched task');await expect(page.locator('.tasks')).not.toContainText('Saved matching task')
})
test('read only project cannot update archive or delete through actual backend',async({authenticatedPage:page,apiContext,currentUser})=>{
 await UserFactory.create(1,{id:2,username:'management-owner'},false);await ProjectFactory.create(1,{id:3,title:'Read only project',owner_id:2},false);await UserProjectFactory.create(1,{id:1,project_id:3,user_id:currentUser.id,permission:0});await page.goto('/projects');const headers=await auth(page);for(const method of ['post','delete']){const response=await apiContext[method]('projects/3',{headers,data:method==='post'?{title:'Forbidden update',is_archived:true}:undefined});expect(response.status()).toBe(403)}expect((await project(page,apiContext,3)).is_archived).toBe(false)
})
test('overview failed load retry preserves quick add draft and actual request',async({authenticatedPage:page})=>{
 await TaskFactory.create(1,{title:'Retry overview task'});let failed=false;await page.route('**/api/v1/tasks?**',async route=>{if(!failed&&route.request().method()==='GET'){failed=true;await route.fulfill({status:503,json:{message:'Fixture overview unavailable'}})}else await route.continue()});await page.goto('/');await page.getByPlaceholder('Add a task…').fill('Retained home draft');await expect(page.getByRole('alert')).toContainText('Fixture overview unavailable');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.tasks')).toContainText('Retry overview task');await expect(page.getByPlaceholder('Add a task…')).toHaveValue('Retained home draft')
})
test('editing during project save preserves the later native draft and focus',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management parent');await page.goto('/projects/1/settings/edit');let ready!:()=>void,release!:()=>void;const begun=new Promise<void>(resolve=>ready=resolve),gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/v1/projects/1',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response})});await title(page).fill('Submitted project');await submit(page).click();await begun;await title(page).fill('Later project draft');await title(page).focus();release();await expect(submit(page)).toBeEnabled();await expect(title(page)).toHaveValue('Later project draft');await expect(title(page)).toBeFocused();expect((await project(page,apiContext)).title).toBe('Submitted project');await page.unroute('**/api/v1/projects/1');await title(page).press('Enter');await expect(page.locator('dialog')).not.toBeVisible();expect((await project(page,apiContext)).title).toBe('Later project draft')
})
test('canceling delayed project write cannot publish into a later dialog',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Management parent');await page.goto('/projects/1/settings/edit');let ready!:()=>void,release!:()=>void;const begun=new Promise<void>(resolve=>ready=resolve),gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/v1/projects/1',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{})});await title(page).fill('Canceled publication');await submit(page).click();await begun;await page.keyboard.press('Escape');await expect(page.locator('dialog')).not.toBeVisible();await page.goto('/projects/2/settings/edit');await title(page).fill('Later dialog draft');await title(page).focus();release();await expect(title(page)).toHaveValue('Later dialog draft');await expect(title(page)).toBeFocused();expect((await project(page,apiContext,2)).title).toBe('Management child');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('dialog')).not.toBeVisible()
})
