import {test,expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {UserFactory} from '../../frontend/tests/factories/user'
import {TeamFactory} from '../../frontend/tests/factories/team'
import {TeamMemberFactory} from '../../frontend/tests/factories/team_member'
import {UserProjectFactory} from '../../frontend/tests/factories/users_project'
import {TeamProjectFactory} from '../../frontend/tests/factories/team_project'
import {LinkShareFactory} from '../../frontend/tests/factories/link_sharing'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
const panel=(page,heading:string)=>page.getByRole('heading',{name:heading==='Share Links'?/^Share Links/:heading,exact:heading!=='Share Links'}).locator('..')
const users=page=>panel(page,'Shared with these users'),teams=page=>panel(page,'Shared with these teams'),links=page=>panel(page,'Share Links')
async function headers(page){return {Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('token'))}`}}
async function access(page,apiContext,type:string){const response=await apiContext.get(`projects/1/${type}`,{headers:await headers(page)});expect(response.ok()).toBe(true);return response.json()}
async function open(page,id=1){await page.goto('/projects');await expect(page.locator('.project-grid')).toContainText('Sharing project');await page.goto(`/projects/${id}/settings/share`);await expect(page.getByText('Share this project',{exact:true})).toBeVisible()}
async function choose(section,name:string,displayName=name){const input=section.getByRole('combobox');await input.fill(name);await input.press('ArrowLeft');await expect(section.getByRole('option').filter({hasText:displayName}).first()).toBeVisible();await input.press('ArrowDown');await input.press('Enter')}
async function confirm(page){await page.getByRole('button',{name:'Do it!',exact:true}).click()}
test.beforeEach(async({authenticatedPage:page})=>{void page;await ProjectFactory.create(2,{title:(id:number)=>id===1?'Sharing project':'Second project'});await createDefaultViews(1);await createDefaultViews(2,5);await UserFactory.create(2,{id:(id:number)=>id+1,username:(id:number)=>`collaborator-${id+1}`,name:(id:number)=>`Collaborator ${id+1}`},false);await TeamFactory.create(1,{id:1,name:'Sharing team'});await TeamMemberFactory.create(1,{id:1,team_id:1,user_id:1,admin:true});await UserProjectFactory.create(0);await TeamProjectFactory.create(0);await LinkShareFactory.create(0)})
test('user access add permission update cancel and removal persist on real backend',async({authenticatedPage:page,apiContext},info)=>{
 await open(page);await choose(users(page),'collaborator-2','Collaborator 2');await users(page).getByRole('button',{name:'Share',exact:true}).click();await expect(users(page).locator('table')).toContainText('Collaborator 2');expect((await access(page,apiContext,'users')).find(user=>user.username==='collaborator-2').permission).toBe(0);await users(page).getByLabel('Permission for Collaborator 2').selectOption('1');await expect(users(page).locator('.type')).toContainText('Read & write');expect((await access(page,apiContext,'users')).find(user=>user.username==='collaborator-2').permission).toBe(1);await page.reload();await expect(users(page).getByLabel('Permission for Collaborator 2')).toHaveValue('1');await users(page).getByRole('button',{name:'Remove this user',exact:true}).click();await page.getByRole('dialog').last().getByRole('button',{name:'Cancel',exact:true}).click();expect((await access(page,apiContext,'users')).some(user=>user.username==='collaborator-2')).toBe(true);await users(page).getByRole('button',{name:'Remove this user',exact:true}).click();await info.attach('user-removal',{body:await page.screenshot(),contentType:'image/png'});await confirm(page);await expect(users(page).locator('table')).toHaveCount(0);expect((await access(page,apiContext,'users')).some(user=>user.username==='collaborator-2')).toBe(false)
})
test('team access add admin permission and removal persist on real backend',async({authenticatedPage:page,apiContext})=>{
 await open(page);await choose(teams(page),'Sharing team');await teams(page).getByRole('button',{name:'Share',exact:true}).click();await expect(teams(page).locator('table')).toContainText('Sharing team');expect((await access(page,apiContext,'teams'))[0].permission).toBe(0);await teams(page).getByLabel('Permission for Sharing team').selectOption('2');await expect(teams(page).locator('.type')).toContainText('Admin');expect((await access(page,apiContext,'teams'))[0].permission).toBe(2);await page.reload();await expect(teams(page).getByLabel('Permission for Sharing team')).toHaveValue('2');await teams(page).getByRole('button',{name:'Remove this team',exact:true}).click();await confirm(page);await expect(teams(page).locator('table')).toHaveCount(0);expect(await access(page,apiContext,'teams')).toEqual([])
})
for(const width of [1440,390])test(`password link create view URL authenticate and revoke ${width}`,async({authenticatedPage:page,apiContext},info)=>{
 await page.setViewportSize({width,height:900});await open(page);await links(page).getByRole('button',{name:'Create a link share',exact:true}).click();await page.getByLabel('Name (optional)',{exact:true}).fill('Fixture link');await page.getByLabel('Password (optional)',{exact:true}).fill('fixture-password');await page.getByLabel('Permission',{exact:true}).selectOption('1');await links(page).getByRole('button',{name:'Share',exact:true}).click();await expect(links(page).locator('table')).toContainText('Fixture link');const shares=await access(page,apiContext,'shares');expect(shares).toHaveLength(1);expect(shares[0]).toMatchObject({name:'Fixture link',permission:1,sharing_type:2});await links(page).getByLabel('View',{exact:true}).selectOption('3');const url=links(page).locator('input[readonly]');await expect(url).toHaveValue(new RegExp(`/share/${shares[0].hash}/auth\\?view=3$`));await links(page).locator('table tbody tr').first().getByRole('button').first().click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(await url.inputValue());const wrong=await apiContext.post(`shares/${shares[0].hash}/auth`,{data:{password:'wrong'}});expect(wrong.status()).toBe(403);const auth=await apiContext.post(`shares/${shares[0].hash}/auth`,{data:{password:'fixture-password'}});expect(auth.ok()).toBe(true);const token=(await auth.json()).token;const shared=await apiContext.get('projects/1',{headers:{Authorization:`Bearer ${token}`}});expect(shared.ok()).toBe(true);expect(Number(shared.headers()['x-max-permission'])).toBe(1);await info.attach(`sharing-${width}`,{body:await page.screenshot(),contentType:'image/png'});await links(page).getByRole('button',{name:'Remove a link share',exact:true}).click();await page.getByRole('dialog').last().getByRole('button',{name:'Cancel',exact:true}).click();expect(await access(page,apiContext,'shares')).toHaveLength(1);await links(page).getByRole('button',{name:'Remove a link share',exact:true}).click();await confirm(page);await expect(links(page).locator('table')).toHaveCount(0);expect(await access(page,apiContext,'shares')).toEqual([]);const revoked=await apiContext.post(`shares/${shares[0].hash}/auth`,{data:{password:'fixture-password'}});expect(revoked.ok()).toBe(false)
})
test('nonadmin access is visible but management and link reads are hidden and backend denies writes',async({authenticatedPage:page,apiContext,currentUser})=>{
 await ProjectFactory.create(1,{id:3,title:'Nonadmin sharing',owner_id:2},false);await createDefaultViews(3,9);await UserProjectFactory.create(2,{id:(id:number)=>id,project_id:3,user_id:(id:number)=>id===1?currentUser.id:3,permission:0});await TeamProjectFactory.create(1,{project_id:3});let linkReads=0;page.on('request',request=>{if(/\/projects\/3\/shares/.test(request.url()))linkReads++});await open(page,3);await expect(users(page).locator('table')).toContainText('Collaborator 3');await expect(teams(page).locator('table')).toContainText('Sharing team');await expect(page.getByRole('combobox')).toHaveCount(0);await expect(page.getByRole('button',{name:'Share',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Share Links',exact:true})).toHaveCount(0);expect(linkReads).toBe(0);for(const type of ['users','teams','shares']){const denied=await apiContext.put(`projects/3/${type}`,{headers:await headers(page),data:type==='users'?{username:'collaborator-2',permission:2}:type==='teams'?{team_id:1,permission:2}:{name:'denied',permission:2}});expect(denied.status()).toBe(403)}
})
test('failed user permission keeps accepted value and retry persists',async({authenticatedPage:page,apiContext})=>{
 await UserProjectFactory.create(1,{project_id:1,user_id:2,permission:0});await open(page);let blocked=false;await page.route('**/api/v1/projects/1/users/collaborator-2',route=>{if(!blocked&&route.request().method()==='POST'){blocked=true;return route.fulfill({status:503,json:{message:'Fixture permission unavailable'}})}return route.continue()});const select=users(page).getByLabel('Permission for Collaborator 2');await expect(select).toHaveValue('0');await select.selectOption('1');await expect(page.getByRole('alert')).toContainText('Fixture permission unavailable');await expect(select).toHaveValue('0');expect((await access(page,apiContext,'users')).find(user=>user.username==='collaborator-2').permission).toBe(0);await select.selectOption('2');await expect(users(page).locator('.type')).toContainText('Admin');expect((await access(page,apiContext,'users')).find(user=>user.username==='collaborator-2').permission).toBe(2)
})
test('link failed write preserves draft and retry creates exactly once',async({authenticatedPage:page,apiContext})=>{
 await open(page);await links(page).getByRole('button',{name:'Create a link share',exact:true}).click();const name=page.getByLabel('Name (optional)',{exact:true});await name.fill('Retained link');await page.getByLabel('Password (optional)',{exact:true}).fill('retained-password');let blocked=false;await page.route('**/api/v1/projects/1/shares',route=>{if(!blocked&&route.request().method()==='PUT'){blocked=true;return route.fulfill({status:503,json:{message:'Fixture link unavailable'}})}return route.continue()});await links(page).getByRole('button',{name:'Share',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Fixture link unavailable');await expect(name).toHaveValue('Retained link');expect(await access(page,apiContext,'shares')).toEqual([]);await links(page).getByRole('button',{name:'Share',exact:true}).click();await expect(links(page).locator('table')).toContainText('Retained link');expect(await access(page,apiContext,'shares')).toHaveLength(1)
})
test('late accepted link write retains later focused draft',async({authenticatedPage:page,apiContext})=>{
 await open(page);await links(page).getByRole('button',{name:'Create a link share',exact:true}).click();const name=page.getByLabel('Name (optional)',{exact:true});await name.fill('Submitted link');let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve);await page.route('**/api/v1/projects/1/shares',async route=>{if(route.request().method()!=='PUT'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{})});await links(page).getByRole('button',{name:'Share',exact:true}).click();await started;await name.fill('Later link draft');await name.focus();release();await expect(links(page).locator('table')).toContainText('Submitted link');await expect(name).toHaveValue('Later link draft');await expect(name).toBeFocused();expect((await access(page,apiContext,'shares'))[0].name).toBe('Submitted link');await page.unroute('**/api/v1/projects/1/shares');await page.keyboard.press('Escape');await expect(page.getByText('Share this project',{exact:true})).not.toBeVisible();await page.goto('/projects/2/settings/share');await expect(page.getByText('Share this project',{exact:true})).toBeVisible();await expect(links(page).locator('table')).toHaveCount(0)
})
test('access read error recovery keeps unsaved link draft',async({authenticatedPage:page})=>{
 let failed=false;await page.route('**/api/v1/projects/1/users?**',route=>{if(!failed){failed=true;return route.fulfill({status:503,json:{message:'Fixture access unavailable'}})}return route.continue()});await open(page);await expect(users(page).getByRole('alert')).toContainText('Fixture access unavailable');await links(page).getByRole('button',{name:'Create a link share',exact:true}).click();const name=page.getByLabel('Name (optional)',{exact:true});await name.fill('Independent draft');await users(page).getByRole('button',{name:'Retry',exact:true}).click();await expect(users(page).getByRole('alert')).not.toBeVisible();await expect(name).toHaveValue('Independent draft')
})
test('late search cannot replace the current user query or selected access target',async({authenticatedPage:page,apiContext})=>{
 await open(page);let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve);await page.route('**/api/v1/users?**',async route=>{if(new URL(route.request().url()).searchParams.get('s')!=='collaborator-2'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{})});const input=users(page).getByRole('combobox');await input.fill('collaborator-2');await input.press('ArrowLeft');await started;await input.fill('collaborator-3');await input.press('ArrowLeft');await users(page).getByRole('option').filter({hasText:'Collaborator 3'}).first().click();await input.focus();release();await page.unroute('**/api/v1/users?**');await expect(input).toBeFocused();await users(page).getByRole('button',{name:'Share',exact:true}).click();await expect(users(page).locator('table')).toContainText('Collaborator 3');const shared=await access(page,apiContext,'users');expect(shared.map(user=>user.username)).toEqual(['collaborator-3'])
})
test('leaving accepted delayed link create cannot publish into a different sharing dialog',async({authenticatedPage:page,apiContext})=>{
 await open(page);await links(page).getByRole('button',{name:'Create a link share',exact:true}).click();await page.getByLabel('Name (optional)',{exact:true}).fill('Canceled publication');let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve);await page.route('**/api/v1/projects/1/shares',async route=>{if(route.request().method()!=='PUT'){await route.continue();return}const response=await route.fetch();ready();await gate;await route.fulfill({response}).catch(()=>{})});await links(page).getByRole('button',{name:'Share',exact:true}).click();await started;await page.evaluate(()=>{history.pushState({},'','/projects/2/settings/share');window.dispatchEvent(new PopStateEvent('popstate'))});await expect(page).toHaveURL(/\/projects\/2\/settings\/share$/);const create=links(page).getByRole('button',{name:'Create a link share',exact:true});if(await create.isVisible())await create.click();const name=page.getByLabel('Name (optional)',{exact:true});await name.fill('Second project draft');await name.focus();release();await page.unroute('**/api/v1/projects/1/shares');await page.waitForLoadState('networkidle');await expect(name).toHaveValue('Second project draft');await expect(name).toBeFocused();await expect(links(page).locator('table')).toHaveCount(0);expect((await access(page,apiContext,'shares'))[0].name).toBe('Canceled publication');const second=await apiContext.get('projects/2/shares',{headers:await headers(page)});expect(second.ok()).toBe(true);expect(await second.json()).toEqual([])
})
test('sharing menu opens over live project and Escape restores project DOM and scroll',async({authenticatedPage:page},info)=>{
 await page.goto('/projects/1/1');await expect(page.locator('.list-view')).toBeVisible();const project=await page.locator('.list-view').elementHandle();await page.locator('.project-title-wrapper').getByRole('button',{name:'Open project settings menu',exact:true}).click();await page.getByRole('link',{name:'Share',exact:true}).click();await expect(page.getByText('Share this project',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page).toHaveURL(/\/projects\/1\/1$/);await expect(page.getByText('Share this project',{exact:true})).toHaveCount(0);expect(await page.locator('.list-view').evaluate((node,previous)=>node===previous,project)).toBe(true);expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');await expect(page.locator('.project-title-wrapper').getByRole('button',{name:'Open project settings menu',exact:true})).toBeFocused();await info.attach('sharing-menu-return',{body:await page.screenshot(),contentType:'image/png'})
})
