import {test, expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {ProjectViewFactory} from '../../frontend/tests/factories/project_view'
const destination = '/projects/1/2?dateFrom=2026-10-01&dateTo=2026-10-20'
test.beforeEach(async ({authenticatedPage: page}) => {
	void page
	await ProjectFactory.create(1, {title: 'Gantt checkpoint'})
	await ProjectViewFactory.create(4, {project_id: 1, title: (id: number) => ['List', 'Gantt', 'Table', 'Kanban'][id - 1], view_kind: (id: number) => id - 1, bucket_configuration_mode: (id: number) => id === 4 ? 1 : 0})
	await TaskFactory.create(1, {id: 1, title: 'Scheduled task', start_date: '2026-10-05T00:00:00Z', end_date: '2026-10-08T23:59:59Z'})
	await TaskFactory.create(1, {id: 2, title: 'Start only', start_date: '2026-10-06T00:00:00Z'}, false)
	await TaskFactory.create(1, {id: 3, title: 'Dateless task'}, false)
})
test('Gantt deep link, date query, dateless toggle and reload', async ({authenticatedPage: page}, info) => {
	const requests: string[] = []
	page.on('request', request => {if (/\/views\/2\/tasks\?/.test(request.url())) requests.push(request.url())})
	await page.goto(destination)
	await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
	await expect(page.getByRole('slider', {name: 'Task: Dateless task', exact: true})).toHaveCount(0)
	const toggle = page.getByRole('checkbox', {name: /tasks without date/i})
	await toggle.focus(); await page.keyboard.press('Space')
	await expect(page.getByRole('slider', {name: 'Task: Dateless task', exact: true})).toBeVisible()
	await page.reload(); await expect(toggle).toBeChecked()
	await expect(page.getByRole('slider', {name: 'Task: Dateless task', exact: true})).toBeVisible()
	const query = new URL(requests.at(-1)!).searchParams
	expect(query.get('filter')).toContain('start_date >= "2026-10-01"')
	expect(query.get('filter_include_nulls')).toBe('true')
	expect(query.getAll('sort_by[]')).toEqual(['start_date', 'done', 'id'])
	await info.attach('gantt-api', {body: JSON.stringify(requests), contentType: 'application/json'})
	await expect(page.locator('.gantt-container')).not.toHaveClass(/is-loading/)
	await info.attach('gantt-desktop', {body: await page.screenshot(), contentType: 'image/png'})
	await page.setViewportSize({width: 390, height: 844})
	await info.attach('gantt-mobile', {body: await page.screenshot(), contentType: 'image/png'})
})
test('Gantt keyboard move and resize preserve focus and persist', async ({authenticatedPage: page}, info) => {
	await page.goto(destination)
	const bar = page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})
	await bar.focus()
	const moved = page.waitForRequest(request => /\/tasks\/1$/.test(request.url()) && request.method() === 'POST')
	await page.keyboard.press('ArrowRight')
	const move = (await moved).postDataJSON()
	expect(Date.parse(move.start_date)).toBe(Date.parse('2026-10-06T00:00:00Z')); expect(Date.parse(move.end_date)).toBe(Date.parse('2026-10-09T23:59:59.999Z'))
	await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse(move.start_date)))
	await expect(bar).toBeFocused()
	const resized = page.waitForRequest(request => /\/tasks\/1$/.test(request.url()) && request.method() === 'POST')
	await page.keyboard.press('Shift+ArrowRight')
	const resize = (await resized).postDataJSON()
	expect(resize.start_date).toBe(move.start_date); expect(Date.parse(resize.end_date)).toBe(Date.parse('2026-10-10T23:59:59.999Z'))
	await page.reload(); await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse(move.start_date)))
	await expect(bar).toHaveAttribute('aria-valuetext', /10\/10\/2026/)
	await info.attach('gantt-date-writes', {body: JSON.stringify([move, resize]), contentType: 'application/json'})
})
test('Gantt partial endpoint movement does not invent an end date', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	const bar = page.getByRole('slider', {name: 'Task: Start only', exact: true})
	await bar.focus()
	const pending = page.waitForRequest(request => /\/tasks\/2$/.test(request.url()) && request.method() === 'POST')
	await page.keyboard.press('ArrowRight')
	const body = (await pending).postDataJSON()
	expect(Date.parse(body.start_date)).toBe(Date.parse('2026-10-07T00:00:00Z')); expect(body.end_date).toBeNull()
	await page.reload(); await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse(body.start_date)))
})
test('Gantt task modal closes back onto retained range and focused bar', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	const bar = page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})
	await bar.click(); await bar.press('Enter')
	await expect(page.getByRole('dialog')).toBeVisible()
	await page.getByRole('dialog').getByRole('button', {name: 'Close dialog', exact: true}).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(bar).toBeFocused()
	expect(new URL(page.url()).searchParams.get('dateFrom')).toBe('2026-10-01')
})
test('Gantt failed load retries through original dateless control', async ({authenticatedPage: page}) => {
	let fail = true
	await page.route('**/projects/1/views/2/tasks?**', route => fail ? route.fulfill({status: 500, contentType: 'application/json', body: JSON.stringify({message: 'Fixture Gantt failure'})}) : route.continue())
	await page.goto(destination)
	await expect(page.getByText('Fixture Gantt failure', {exact: true})).toBeVisible()
	fail = false
	const toggle = page.getByRole('checkbox', {name: /tasks without date/i})
	await toggle.focus(); await page.keyboard.press('Space')
	await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
})
test('Gantt pointer move and end resize publish whole-day changes', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	const bar = page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})
	await expect(bar).toBeVisible()
	const day = (await page.locator('.timeunit').first().boundingBox())!.width
	const rect = bar.locator('.gantt-bar'), box = (await rect.boundingBox())!
	const pending = page.waitForResponse(response => /\/tasks\/1$/.test(response.url()) && response.request().method() === 'POST')
	await page.mouse.move(box.x + box.width / 2, box.y + 16); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + day, box.y + 16, {steps: 4}); await page.mouse.up()
	const moved = (await pending).request().postDataJSON()
	expect(Date.parse(moved.start_date)).toBe(Date.parse('2026-10-06T00:00:00Z'))
	await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse(moved.start_date)))
	const edge = (await bar.locator('.gantt-resize-right').boundingBox())!
	const resized = page.waitForResponse(response => /\/tasks\/1$/.test(response.url()) && response.request().method() === 'POST')
	await page.mouse.move(edge.x + edge.width / 2, edge.y + 16); await page.mouse.down(); await page.mouse.move(edge.x + edge.width / 2 + day, edge.y + 16, {steps: 4}); await page.mouse.up()
	expect(Date.parse((await resized).request().postDataJSON().end_date)).toBe(Date.parse('2026-10-10T23:59:59.999Z'))
	await page.reload(); await expect(bar).toHaveAttribute('aria-valuetext', /10\/10\/2026/)
})
test('Gantt create uses original form and seven-day default dates', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
	await page.getByRole('button', {name: 'Create a task', exact: true}).click()
	const input = page.locator('.add-new-task input')
	await expect(input).toBeFocused(); await input.fill('Gantt-created task')
	const pending = page.waitForResponse(response => /\/projects\/1\/tasks$/.test(response.url()) && response.request().method() === 'PUT')
	await input.press('Enter')
	const body = (await pending).request().postDataJSON()
	expect(body.title).toBe('Gantt-created task')
	const start = new Date(body.start_date), end = new Date(body.end_date)
	expect(start.getUTCHours()).toBe(0); expect(end.getUTCHours()).toBe(23)
	expect(Math.round((end.getTime() - start.getTime()) / 86400000)).toBe(8)
	await expect(page.getByRole('slider', {name: 'Task: Gantt-created task', exact: true})).toBeVisible()
	await page.reload(); await expect(page.getByRole('slider', {name: 'Task: Gantt-created task', exact: true})).toBeVisible()
})
test('Gantt rejected date write retries from persisted state', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	const bar = page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})
	await expect(bar).toBeVisible()
	let fail = true
	await page.route('**/tasks/1', route => route.request().method() === 'POST' && fail ? route.fulfill({status: 500, contentType: 'application/json', body: JSON.stringify({message: 'Fixture date failure'})}) : route.continue())
	await bar.focus(); await page.keyboard.press('ArrowRight')
	await expect(page.getByText('Fixture date failure', {exact: true})).toBeVisible()
	await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse('2026-10-05T00:00:00Z')))
	fail = false
	const saved = page.waitForResponse(response => /\/tasks\/1$/.test(response.url()) && response.request().method() === 'POST')
	await bar.focus(); await page.keyboard.press('ArrowRight'); await saved
	await page.reload(); await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse('2026-10-06T00:00:00Z')))
})
test('Gantt delayed query shows loading and cannot publish after navigation', async ({authenticatedPage: page}) => {
	const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
	let release!: () => void, started!: () => void
	const delayed = new Promise<void>(resolve => {release = resolve}), ready = new Promise<void>(resolve => {started = resolve})
	await page.route('**/projects/1/views/2/tasks?**', async route => {const response = await route.fetch(); started(); await delayed; await route.fulfill({response}).catch(() => {})})
	await page.goto(destination); await ready
	await expect(page.locator('.gantt-container')).toHaveClass(/is-loading/)
	const tabs = page.locator('.switch-view-button')
	await tabs.filter({hasText: /^Table$/}).click()
	await expect(page.getByRole('table')).toBeVisible()
	release(); await expect(page.getByRole('slider')).toHaveCount(0)
	await expect(page.getByRole('table')).toBeVisible(); expect(errors).toEqual([])
})
test('Gantt retrieves all task pages rather than stopping after first fifty', async ({authenticatedPage: page}) => {
	await TaskFactory.create(65, {title: (id: number) => `Gantt row ${id}`, start_date: '2026-10-05T00:00:00Z', end_date: '2026-10-08T23:59:59Z'})
	const pages: string[] = []
	page.on('request', request => {if (/\/views\/2\/tasks\?/.test(request.url())) pages.push(new URL(request.url()).searchParams.get('page')!)})
	await page.goto(destination)
	await expect(page.getByRole('slider')).toHaveCount(65)
	expect(pages).toEqual(['1', '2'])
})
test('Gantt date picker commits a complete range to URL and backend query', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
	await page.locator('.gantt-options input[type=text]').click()
	await page.locator('.flatpickr-calendar.open .flatpickr-day[aria-label="October 2, 2026"]').click()
	await page.locator('.flatpickr-calendar.open .flatpickr-day[aria-label="October 12, 2026"]').click()
	await expect.poll(() => new URL(page.url()).searchParams.get('dateFrom')).toBe('2026-10-02')
	await expect.poll(() => new URL(page.url()).searchParams.get('dateTo')).toBe('2026-10-12')
	await page.reload(); await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
})
test('Gantt modal title publication survives later bar date writes', async ({authenticatedPage: page}) => {
	await page.goto(destination)
	await page.getByRole('slider', {name: 'Task: Scheduled task', exact: true}).dblclick()
	const title = page.locator('.task-view h1.title.input')
	await expect(title).toHaveText('Scheduled task'); await title.fill('Renamed Gantt task'); await title.press('Enter')
	await expect(page.locator('.heading')).toContainText('Saved!')
	await page.getByRole('dialog').getByRole('button', {name: 'Close dialog', exact: true}).click()
	const bar = page.getByRole('slider', {name: 'Task: Renamed Gantt task', exact: true})
	await expect(bar).toBeVisible(); await bar.focus()
	const pending = page.waitForResponse(response => /\/tasks\/1$/.test(response.url()) && response.request().method() === 'POST')
	await bar.press('ArrowRight'); expect((await pending).request().postDataJSON().title).toBe('Renamed Gantt task')
	await page.reload(); await expect(bar).toBeVisible()
})
test('Gantt hierarchy collapse retains parent and reroutes dependency arrows', async ({authenticatedPage: page}) => {
	const {TaskRelationFactory} = await import('../../frontend/tests/factories/task_relation')
	await TaskRelationFactory.create(1, {task_id: 1, other_task_id: 2, relation_kind: 'subtask'})
	await TaskRelationFactory.create(1, {id: 2, task_id: 2, other_task_id: 1, relation_kind: 'parenttask'}, false)
	await TaskRelationFactory.create(1, {id: 3, task_id: 2, other_task_id: 3, relation_kind: 'blocking'}, false)
	await TaskRelationFactory.create(1, {id: 4, task_id: 3, other_task_id: 2, relation_kind: 'blocked'}, false)
	await page.goto(destination + '&showTasksWithoutDates=true')
	await expect(page.getByRole('slider')).toHaveCount(3)
	await expect(page.locator('.gantt-relation-arrows .gantt-arrow')).toHaveCount(1)
	const collapse = page.getByRole('button', {name: 'Collapse group: Scheduled task', exact: true})
	await collapse.focus(); await collapse.press('Enter')
	await expect(page.getByRole('slider')).toHaveCount(2)
	await expect(page.getByRole('slider', {name: 'Task: Start only', exact: true})).toHaveCount(0)
	await expect(page.locator('.gantt-relation-arrows .gantt-arrow')).toHaveCount(1)
	await page.getByRole('button', {name: 'Expand group: Scheduled task', exact: true}).press('Enter')
	await expect(page.getByRole('slider')).toHaveCount(3)
})
test('Gantt actual read-only membership exposes dates without creation or writes', async ({authenticatedPage: page, currentUser}) => {
	const {UserFactory} = await import('../../frontend/tests/factories/user')
	const {UserProjectFactory} = await import('../../frontend/tests/factories/users_project')
	await UserFactory.create(1, {id: 201, username: 'gantt-owner'}, false)
	await ProjectFactory.create(1, {id: 2, title: 'Readonly Gantt', owner_id: 201}, false)
	await ProjectViewFactory.create(1, {id: 6, project_id: 2, title: 'Gantt', view_kind: 1}, false)
	await UserProjectFactory.create(1, {id: 3, project_id: 2, user_id: currentUser.id, permission: 0}, false)
	await TaskFactory.create(1, {id: 4, project_id: 2, title: 'Readonly dates', created_by_id: 201, start_date: '2026-10-05T00:00:00Z', end_date: '2026-10-08T23:59:59Z'}, false)
	const writes: string[] = []
	page.on('request', request => {if (['POST', 'PUT', 'DELETE'].includes(request.method()) && /\/tasks\/4$/.test(request.url())) writes.push(request.url())})
	await page.goto('/projects/2/6?dateFrom=2026-10-01&dateTo=2026-10-20')
	const bar = page.getByRole('slider', {name: 'Task: Readonly dates', exact: true})
	await bar.focus(); await bar.press('ArrowRight')
	await expect(page.getByRole('button', {name: 'Create a task', exact: true})).toHaveCount(0)
	await expect(bar).toHaveAttribute('aria-valuenow', String(Date.parse('2026-10-05T00:00:00Z')))
	await page.waitForLoadState('networkidle'); expect(writes).toEqual([])
})
test('Gantt pending range selection survives asynchronous task publication', async ({authenticatedPage: page}) => {
	let release!: () => void, started!: () => void
	const delayed = new Promise<void>(resolve => {release = resolve}), ready = new Promise<void>(resolve => {started = resolve})
	await page.route('**/projects/1/views/2/tasks?**', async route => {const response = await route.fetch(); started(); await delayed; await route.fulfill({response}).catch(() => {})})
	await page.goto(destination); await ready
	await page.locator('.gantt-options input[type=text]').click()
	await page.locator('.flatpickr-calendar.open .flatpickr-day[aria-label="October 2, 2026"]').click()
	release(); await expect(page.getByRole('slider', {name: 'Task: Scheduled task', exact: true})).toBeVisible()
	await page.locator('.flatpickr-calendar.open .flatpickr-day[aria-label="October 12, 2026"]').click()
	await expect.poll(() => new URL(page.url()).searchParams.get('dateFrom')).toBe('2026-10-02')
	await expect.poll(() => new URL(page.url()).searchParams.get('dateTo')).toBe('2026-10-12')
})
