import {BucketFactory} from '../../frontend/tests/factories/bucket'
import {TaskBucketFactory} from '../../frontend/tests/factories/task_buckets'
import {LabelFactory} from '../../frontend/tests/factories/labels'
import {LabelTaskFactory} from '../../frontend/tests/factories/label_task'
import {TeamFactory} from '../../frontend/tests/factories/team'
import {TeamMemberFactory} from '../../frontend/tests/factories/team_member'
import {SavedFilterFactory} from '../../frontend/tests/factories/saved_filter'
import {test,expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
test.beforeEach(async()=>{
 await ProjectFactory.create(3,{title:(id:number)=>id===1?'Search project':`Destination ${id}`,hex_color:'1973ff',position:100})
 await createDefaultViews(1);await createDefaultViews(2,5);await createDefaultViews(3,9)
 await TaskFactory.create(2,{title:'Searchable task',project_id:1,description:'Keep this draft'})
})
for(const width of [1440,390])test(`quick actions search keyboard navigation and creation ${width}`,async({authenticatedPage:page,apiContext,userToken},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/projects/1/1')
 await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog'),input=dialog.locator('input').first()
 await expect(input).toBeFocused();await expect(dialog.locator('.active-cmd')).toBeHidden();await expect(dialog.locator('.show-helper-text').first()).toBeHidden();await input.fill('Searchable task');await input.press('End');const task=dialog.getByRole('button').filter({hasText:'Searchable task'}).first();await expect(task).toBeVisible()
 await page.screenshot({path:info.outputPath(`search-${width}.png`)})
 await input.press('ArrowDown');await expect(task).toBeFocused();await task.press('ArrowUp');await expect(input).toBeFocused();await task.click();await expect(page).toHaveURL(/\/tasks\/\d+/)
 await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');await input.fill('New task');await input.press('End');await dialog.getByRole('button',{name:/New task/}).click();await expect(dialog.locator('.active-cmd')).toBeVisible();await expect(dialog.locator('.show-helper-text').first()).toBeVisible();await expect(dialog.locator('.help.has-text-grey-light')).toBeHidden();await input.fill('Created through quick actions +"Search project" !2');await input.press('End');const response=page.waitForResponse(r=>(r.request().method()==='POST'&&/\/api\/v2\/projects\/\d+\/tasks\/bulk/.test(r.url()))||(r.request().method()==='PUT'&&/\/api\/v1\/projects\/\d+\/tasks$/.test(r.url())))
 await input.press('Enter');const payload=await(await response).json(),created=payload.tasks?.[0]??payload;expect(created).toMatchObject({title:'Created through quick actions',project_id:1,priority:2});await expect(page).toHaveURL(new RegExp(`/tasks/${created.id}$`));const persisted=await apiContext.get(`tasks/${created.id}`,{headers:{Authorization:`Bearer ${userToken}`}});expect(await persisted.json()).toMatchObject({title:'Created through quick actions',priority:2})
})
test('quick actions cancels stale search and keeps creation draft on error',async({authenticatedPage:page})=>{
 await page.goto('/projects/1/1');let release!:()=>void
 await page.route('**/tasks?*',async route=>{if(!new URL(route.request().url()).searchParams.get('s')?.includes('held'))return route.continue();await new Promise<void>(ready=>release=ready);await route.fulfill({json:[{id:999,title:'obsolete held task',project_id:1}],headers:{'x-pagination-total-pages':'1'}}).catch(()=>{})})
 await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog'),input=dialog.locator('input').first();await input.fill('held');await input.press('End');await expect.poll(()=>Boolean(release)).toBeTruthy();await input.fill('Searchable task');await input.press('End');await expect(dialog.getByRole('button').filter({hasText:'Searchable task'}).first()).toBeVisible();release();await expect(dialog.getByText('obsolete held task')).toHaveCount(0)
 await input.fill('New team');await input.press('End');await dialog.getByRole('button',{name:/New team/}).click();await page.route('**/teams',route=>route.request().method()==='PUT'?route.fulfill({status:503,json:{message:'team fixture unavailable'}}):route.continue());await input.fill('Retained team draft');await input.press('End');await input.press('Enter');await expect(dialog.getByText('team fixture unavailable')).toBeVisible();await expect(input).toHaveValue('Retained team draft');await input.press('Escape');await expect(dialog).toHaveCount(0)
})
for(const width of [1440,390])test(`task color reset move reload and editor draft ${width}`,async({authenticatedPage:page,apiContext,userToken},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/tasks/1');const actions=page.locator('.task-view .action-buttons,.task-view .native-task-actions').last();await actions.getByRole('button',{name:'Set Color',exact:true}).click();const color=page.locator('.task-view input[type=color]');await color.fill('#ff4136');await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).hex_color}).toBe('ff4136');await expect(color).toHaveValue('#ff4136')
 await page.locator('.task-view h1.title.input').fill('Draft survives move');await actions.getByRole('button',{name:'Move',exact:true}).click();const search=page.locator('.task-view .multiselect input').last();await search.fill('Destination 2');await search.press('End');await page.getByRole('option').filter({hasText:'Destination 2'}).click();await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).project_id}).toBe(2)
 await expect(page.locator('.task-view h1.title.input')).toHaveText('Draft survives move');await page.screenshot({path:info.outputPath(`location-${width}.png`)});await page.reload();await actions.getByRole('button',{name:'Set Color',exact:true}).click();await expect(color).toHaveValue('#ff4136');await page.getByRole('button',{name:'Reset Color',exact:true}).click();await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).hex_color}).toBe('')
})
test('sidebar nested collapse favorite active navigation and width persistence',async({authenticatedPage:page,apiContext,userToken},info)=>{
 await ProjectFactory.create(1,{id:4,title:'Nested child',parent_project_id:1,position:200},false);await createDefaultViews(4,13)
 await page.goto('/projects/1/1');const navigation=page.locator('.menu-container');const projects=navigation.getByRole('navigation',{name:'Projects',exact:true});await expect(projects.getByRole('link',{name:'Nested child',exact:true})).toBeVisible();const toggle=projects.getByRole('button',{name:'Toggle sub-projects',exact:true}).first();await toggle.click();await expect(projects.getByRole('link',{name:'Nested child',exact:true})).toHaveCount(0);await page.reload();await expect(projects.getByRole('link',{name:'Nested child',exact:true})).toHaveCount(0);await toggle.click();await projects.getByRole('link',{name:'Nested child',exact:true}).click();await expect(page).toHaveURL(/\/projects\/4/);await expect(projects.getByRole('link',{name:'Nested child',exact:true})).toHaveClass(/router-link-exact-active/)
 await projects.locator('[data-project-id="4"]').first().getByRole('button',{name:'Mark this project as favorite',exact:true}).click();await expect(navigation.getByRole('navigation',{name:'Favorites',exact:true}).getByRole('link',{name:'Nested child',exact:true})).toBeVisible()
 const handle=navigation.locator('.resize-handle'),box=(await handle.boundingBox())!;await page.mouse.move(box.x+2,box.y+50);await page.mouse.down();await page.mouse.move(370,box.y+50);await page.mouse.up();await expect.poll(async()=>{const response=await apiContext.get('user',{headers:{Authorization:`Bearer ${userToken}`}});return(await response.json()).settings.frontend_settings.sidebar_width}).toBe(370);await page.reload();await expect(navigation).toHaveCSS('width','370px');await page.screenshot({path:info.outputPath('sidebar-1440.png')})
})
test('quick actions project and team creation persists parent and navigates',async({authenticatedPage:page,apiContext,userToken})=>{
 await page.goto('/projects/1/1');await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog'),input=dialog.locator('input').first();await input.fill('New project');await input.press('End');await dialog.getByRole('button',{name:/New project/}).click();await input.fill('Created child');await input.press('End');const createdProject=page.waitForResponse(r=>/\/projects$/.test(r.url())&&r.request().method()==='PUT');await input.press('Enter');const project=await(await createdProject).json();expect(project).toMatchObject({title:'Created child',parent_project_id:1});await expect(dialog).toHaveCount(0);await expect(page).toHaveURL(new RegExp(`/projects/${project.id}(?:/|$)`));expect((await apiContext.get(`projects/${project.id}`,{headers:{Authorization:`Bearer ${userToken}`}})).ok()).toBeTruthy()
 await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');await input.fill('New team');await input.press('End');await dialog.getByRole('button',{name:/New team/}).click();await input.fill('Created team');await input.press('End');const createdTeam=page.waitForResponse(r=>/\/teams$/.test(r.url())&&r.request().method()==='PUT');await input.press('Enter');const team=await(await createdTeam).json();expect(team.name).toBe('Created team');await expect(page).toHaveURL(new RegExp(`/teams/${team.id}/edit$`));expect((await apiContext.get(`teams/${team.id}`,{headers:{Authorization:`Bearer ${userToken}`}})).ok()).toBeTruthy()
})
test('task move retry retains search and color focus survives another field save',async({authenticatedPage:page,apiContext,userToken})=>{
 await page.goto('/tasks/1');const actions=page.locator('.task-view .action-buttons,.task-view .native-task-actions').last();await actions.getByRole('button',{name:'Set Color',exact:true}).click();const color=page.locator('.task-view input[type=color]');await color.focus();await page.locator('.task-view h1.title.input').fill('Updated title');await color.focus();await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).title}).toBe('Updated title');await expect(color).toBeFocused()
 let calls=0;await page.route('**/tasks/1',route=>{if(route.request().method()!=='POST')return route.continue();calls++;return calls===1?route.fulfill({status:503,json:{message:'move unavailable'}}):route.continue()});await actions.getByRole('button',{name:'Move',exact:true}).click();const search=page.locator('.task-view .multiselect input').last();await search.fill('Destination 2');await search.press('End');await page.getByRole('option').filter({hasText:'Destination 2'}).click();await expect(page.getByText('move unavailable').first()).toBeVisible();await expect(search).toHaveValue('Destination 2');await page.getByRole('button',{name:'try again',exact:true}).click();await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).project_id}).toBe(2);expect(calls).toBe(2)
})
test('sidebar project ordering persists from actual pointer drag',async({authenticatedPage:page,apiContext,userToken})=>{
 await page.goto('/projects/1/1');const projects=page.locator('.menu-container').getByRole('navigation',{name:'Projects',exact:true}),first=projects.locator('.list-menu[data-project-id="1"]').first(),third=projects.locator('.list-menu[data-project-id="3"]').first();await first.hover();const start=(await first.locator('.handle').boundingBox())!,target=(await third.locator('.navigation-item').first().boundingBox())!;await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(start.x+start.width/2,target.y+target.height-2,{steps:20});await page.mouse.up();await expect.poll(async()=>{const r=await apiContext.get('projects/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).position}).toBeGreaterThan(100);await page.reload();await expect(projects.locator('a[href="/projects/1"]')).toBeVisible();const hrefs=await projects.getByRole('link').evaluateAll(links=>links.map(link=>link.getAttribute('href')).filter(href=>/^\/projects\/\d+$/.test(href??'')));expect(hrefs.at(-1)).toBe('/projects/1')
})
test('moving a task modal updates its project breadcrumb and underlying source list',async({authenticatedPage:page,apiContext,userToken})=>{
 await BucketFactory.create(1,{id:1,title:'Backlog',project_view_id:4,position:100});await TaskBucketFactory.create(2,{task_id:(id:number)=>id,bucket_id:1,project_view_id:4});await page.goto('/projects/1/4');await page.locator('.kanban .task').filter({hasText:'Searchable task'}).first().click();await expect(page).toHaveURL(/\/tasks\/1/);await expect(page.getByRole('dialog')).toBeVisible();const actions=page.locator('.task-view .action-buttons,.task-view .native-task-actions').last();await actions.getByRole('button',{name:'Move',exact:true}).click();await page.locator('.task-view .multiselect input').last().fill('Destination 2');await page.getByRole('option').filter({hasText:'Destination 2'}).click();await expect.poll(async()=>{const r=await apiContext.get('tasks/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).project_id}).toBe(2);await expect(page.locator('.task-view .subtitle').getByRole('link',{name:'Destination 2',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close dialog',exact:true}).last().click();await expect(page).toHaveURL(/\/projects\/1\/4/);await expect(page.locator('.kanban a[href="/tasks/1"]')).toHaveCount(0);await page.reload();await expect(page.locator('.kanban a[href="/tasks/1"]')).toHaveCount(0)
})
test('search project label and team modes use real API and saved filter favorites persist',async({authenticatedPage:page,apiContext,userToken})=>{
 await LabelFactory.create(1,{title:'Urgent',hex_color:'1973ff'});await LabelTaskFactory.create(1,{task_id:1,label_id:1});await TeamFactory.create(1,{id:1,name:'Search team'});await TeamMemberFactory.create(1,{team_id:1,user_id:1,admin:true});await SavedFilterFactory.create(1,{id:1,title:'Saved Search',filters:JSON.stringify({filter:'done = false',filter_include_nulls:false,s:''})});await page.goto('/projects/1/1');await expect(page.getByRole('button',{name:'Open the search/quick action bar',exact:true})).toBeVisible();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog'),input=dialog.locator('input').first();await input.fill('+"Search project" *Urgent');await input.press('End');const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/tasks')&&new URL(r.url()).searchParams.get('filter')?.includes('labels in 1')===true);const matched=await response;expect(new URL(matched.url()).searchParams.get('filter')).toBe('project = 1 && labels in 1');expect(await matched.json()).toEqual([expect.objectContaining({id:1})]);await expect(dialog.getByRole('button').filter({hasText:'Searchable task'})).toHaveCount(1)
 await input.fill('@"Search team"');await input.press('End');await dialog.getByRole('button',{name:/Search team/}).click();await expect(page).toHaveURL(/\/teams\/1\/edit/);await page.getByRole('link',{name:'Projects',exact:true}).click();const filters=page.locator('.menu-container').getByRole('navigation',{name:'Saved filters',exact:true});await expect(filters.getByRole('link',{name:'Saved Search',exact:true})).toBeVisible();await filters.getByRole('button',{name:'Mark this project as favorite',exact:true}).click();await expect.poll(async()=>{const r=await apiContext.get('filters/1',{headers:{Authorization:`Bearer ${userToken}`}});return(await r.json()).is_favorite}).toBe(true);await page.reload();await expect(page.locator('.menu-container').getByRole('navigation',{name:'Favorites',exact:true}).getByRole('link',{name:'Saved Search',exact:true})).toBeVisible()
})
