import {test, expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
async function capture(page, info, name) {
 const menu=page.locator('.menu-show-button')
 await expect.soft(menu).toHaveAttribute('aria-label',await menu.getAttribute('aria-expanded')==='true'?'Hide the menu':'Show the menu')
 await page.evaluate(async () => {await document.fonts.ready})
 await page.mouse.move(0, 0)
 await info.attach(name, {body: await page.screenshot({fullPage: true, animations: 'disabled'}), contentType: 'image/png'})
 await info.attach(name + '-controls', {body: JSON.stringify(await page.locator('.input-wrapper, input, .removal-button, .section-block, .card-header-title, .card, .card-content, .content, .card-footer, .has-text-centered, .share-heading, th, td, button').evaluateAll(elements => elements.filter(el => el.getBoundingClientRect().width).map(el => {
  const r = el.getBoundingClientRect(), s = getComputedStyle(el)
  return {tag:el.tagName, text:el.getAttribute('aria-label') || el.textContent?.trim(), classes:el.className, rect:{x:r.x,y:r.y,width:r.width,height:r.height}, font:s.font,color:s.color,padding:s.padding,flex:s.flex,marginBlockStart:s.marginBlockStart,marginBlockEnd:s.marginBlockEnd,overflowX:s.overflowX,marginInlineStart:s.marginInlineStart,marginInlineEnd:s.marginInlineEnd,fontWeight:s.fontWeight}
 })), null, 2), contentType:'application/json'})
}
test('general settings search outer and inner geometry clear and section spacing', async ({authenticatedPage: page, apiContext}, info) => {
 await page.goto('/user/settings/general')
 await expect(page.getByLabel('My Name', {exact:true})).toBeVisible()
 await expect(page.getByLabel('My Name',{exact:true})).toHaveAttribute('placeholder','The new name')
 const banner = page.locator('.add-to-home-screen'); if(await banner.isVisible()) await banner.getByRole('button',{name:'Close banner',exact:true}).click()
 const search = page.locator('.multiselect').filter({has:page.locator('input')}).last()
 const clear = search.getByRole('button', {name: 'Clear selection', exact:true})
 await capture(page, info, 'general-search-initial')
 const upcoming=page.locator('.other-menu-items').getByRole('link',{name:'Upcoming',exact:true,includeHidden:true})
 expect.soft(await upcoming.locator('svg[data-prefix=far][data-icon=calendar-days]').count()).toBe(1)
 const help=page.locator('.general-settings p.help').first()
 expect.soft(await help.evaluate(el=>getComputedStyle(el).marginBlockEnd)).toBe(await help.evaluate(el=>getComputedStyle(el).fontSize))
 const sections = page.locator('.section-block + .section-block')
 expect.soft(await sections.first().evaluate(el=>getComputedStyle(el).marginBlockStart)).toBe('24px')
 const input = search.locator('input').first()
 // Source Vue clips the inner field through an inherited 50% rule. Keep the
 // useful native inner width; compare the outlined control, not that bug.
 const outer=await search.locator('.input-wrapper').boundingBox(),nameRect=await page.getByLabel('My Name',{exact:true}).boundingBox()
 expect.soft(Math.abs(outer!.width-nameRect!.width)).toBeLessThanOrEqual(1)
 const timezone = search.locator('input').first(); await timezone.fill('Europe/Berlin'); await timezone.press('ArrowLeft'); await expect(page.getByRole('option', {name:'Europe/Berlin',exact:true})).toBeVisible(); await timezone.press('Enter'); await timezone.press('Tab')
 await expect(clear).toBeVisible()
 await capture(page, info, 'general-search-selected')
 {
  await expect.soft(clear).toBeVisible()
  expect.soft(await clear.evaluate(el=>getComputedStyle(el).color)).toBe(await clear.evaluate(el=>getComputedStyle(document.documentElement).getPropertyValue('--danger').trim()).then(value=>page.evaluate(value=>{const el=document.createElement('span');el.style.color=value;document.body.append(el);const color=getComputedStyle(el).color;el.remove();return color},value)))
  expect.soft(await clear.evaluate(el=>getComputedStyle(el).insetInlineEnd)).toBe('8px')
 }
 const name=page.getByLabel('My Name',{exact:true});await name.fill('Appearance retry draft')
 const card=page.locator('.general-settings').first(),before=await card.boundingBox()
 let fail=true
 await page.route('**/api/v1/user/settings/general',route=>fail?route.fulfill({status:503,json:{message:'Appearance profile unavailable'}}):route.continue())
 const rejected=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/user/settings/general')&&r.request().method()==='POST')
 await page.getByRole('button',{name:'Save',exact:true}).click();expect((await rejected).status()).toBe(503)
 await expect(page.getByText('Appearance profile unavailable',{exact:false})).toBeVisible()
 await expect(name).toHaveValue('Appearance retry draft')
 expect.soft((await card.boundingBox())?.y).toBe(before?.y)
 await capture(page,info,'general-error-draft')
 await name.fill('Appearance retry draft revised'); await name.focus(); await expect(name).toBeFocused()
 fail=false
 const accepted=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/user/settings/general')&&r.request().method()==='POST')
 await page.getByRole('button',{name:'Save',exact:true}).click();expect((await accepted).ok()).toBe(true)
 const token=await page.evaluate(()=>localStorage.getItem('token'))
 const user=await apiContext.get('user',{headers:{Authorization:`Bearer ${token}`}});expect(user.ok()).toBe(true);expect((await user.json()).name).toBe('Appearance retry draft revised')
 await page.reload();await expect(name).toHaveValue('Appearance retry draft revised')

})
test('project share search and link table source appearance', async ({authenticatedPage:page, apiContext, currentUser}, info) => {
 await ProjectFactory.create(1,{title:'Appearance shared project'}); await createDefaultViews(1)
 await page.goto('/projects/1/1')
 await expect(page.locator('.list-view')).toBeVisible()
 await page.locator('.project-title-wrapper').getByRole('button',{name:'Open project settings menu',exact:true}).click()
 await page.getByRole('link',{name:'Share',exact:true}).click()
 await expect(page).toHaveURL(/\/projects\/1\/settings\/share$/)
 const links = page.getByRole('heading',{name:/^Share Links/}).locator('..')
 const create = links.getByRole('button',{name:'Create a link share',exact:true})
 await expect(create).toBeVisible()
 if(page.viewportSize()!.width>768) await expect(page.getByRole('button',{name:'Close dialog',exact:true})).toHaveCSS('color',info.project.use.colorScheme==='dark'?'rgb(249, 250, 251)':'rgb(255, 255, 255)')
 expect.soft(await page.getByRole('dialog').locator('.card').first().evaluate(el=>getComputedStyle(el).boxShadow)).toBe('none')
 expect.soft(await page.getByText('Share this project',{exact:true}).evaluate(el=>getComputedStyle(el).fontWeight)).toBe('700')
 expect.soft(await page.getByText('Share this project',{exact:true}).evaluate(el=>getComputedStyle(el).fontFamily)).toContain('Open Sans')
 const cardContent=page.getByRole('dialog').locator('.card-content').first()
 expect.soft(await cardContent.evaluate(el=>getComputedStyle(el).padding)).toBe('0px')
 expect.soft(await cardContent.locator('.content').evaluate(el=>getComputedStyle(el).marginBlockEnd)).toBe('0px')
 expect.soft(await page.getByRole('dialog').locator('p.has-text-centered').first().evaluate(el=>getComputedStyle(el.parentElement!).overflowX)).toBe('visible')
 expect.soft(await create.evaluate(el=>getComputedStyle(el).marginInlineStart)).toBe('0px')
 expect.soft(await create.evaluate(el=>getComputedStyle(el).marginBlockEnd)).toBe('16px')
 const footer=page.getByRole('dialog').locator('.card-footer')
 expect.soft(await footer.evaluate(el=>getComputedStyle(el).paddingBlockStart)).toBe('20px')
 expect.soft(await footer.getByRole('button',{name:'Cancel',exact:true}).evaluate(el=>getComputedStyle(el).marginInlineEnd)).toBe('0px')
 const userShare=page.getByRole('heading',{name:'Shared with these users',exact:true}).locator('..').getByRole('button',{name:'Share',exact:true})
 expect.soft(await userShare.evaluate(el=>getComputedStyle(el).marginInlineEnd)).toBe('0px')
 if(page.viewportSize()!.width<=768) expect.soft(await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).count()).toBe(1)
 const search = page.getByRole('dialog').locator('.multiselect').first()
 await capture(page,info,'sharing-search-initial')
 expect.soft(await search.locator('input').first().evaluate(el=>getComputedStyle(el).borderTopWidth)).toBe('0px')
 expect.soft(await create.locator('svg[data-icon="plus"]').count()).toBe(1)
 await create.click()
 await page.getByLabel('Name (optional)',{exact:true}).fill('Appearance link')
 const share = links.getByRole('button',{name:'Share',exact:true})
 expect.soft(await share.locator('svg[data-icon="plus"]').count()).toBe(1)
 const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/projects/1/shares')&&r.request().method()==='PUT')
 await share.click(); expect((await response).ok()).toBe(true)
 const row=links.locator('tbody tr').filter({hasText:'Appearance link'}); await expect(row).toBeVisible()
 const notice=page.locator('.global-notification .vue-notification').filter({hasText:'The link share was successfully created.'})
 await expect(notice).toBeVisible()
 expect.soft(await notice.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})).toBe(true)
 await notice.click({trial:true,timeout:1500})
 await capture(page,info,'sharing-link-created')
 await expect.soft(links.getByRole('columnheader',{name:'View',exact:true})).toBeVisible()
 await expect.soft(links.getByRole('columnheader',{name:'Delete',exact:true})).toBeVisible()
 await expect.soft(row.locator('strong')).toContainText(currentUser.name || currentUser.username)
 await expect.soft(row.locator('svg[data-icon="users"]')).toBeVisible()
 const token=await page.evaluate(()=>localStorage.getItem('token'))
 const shares=await apiContext.get('projects/1/shares',{headers:{Authorization:`Bearer ${token}`}});expect(shares.ok()).toBe(true);expect(await shares.json()).toHaveLength(1)
 await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeHidden()
 await expect(notice).toBeVisible()
 await notice.click()
 await expect(notice).toBeHidden()
})
