import {test,expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {Factory} from '../../frontend/tests/support/factory'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
const save=page=>page.getByRole('button',{name:'Save',exact:true})
const result=(page,path:string)=>page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(path)&&r.request().method()==='POST')
async function stored(page,apiContext){const token=await page.evaluate(()=>localStorage.getItem('token'));const response=await apiContext.get('user',{headers:{Authorization:`Bearer ${token}`}});expect(response.ok()).toBe(true);return (await response.json()).settings}
test.beforeEach(async({authenticatedPage:page})=>{void page;await ProjectFactory.create(2,{title:(id:number)=>id===1?'Preferences parent':'Preferences child',parent_project_id:(id:number)=>id===1?0:1});await createDefaultViews(1)})
test('project and timezone search keyboard clear escape preserve other form drafts and persist',async({authenticatedPage:page,apiContext},info)=>{
 await page.goto('/user/settings/general');await page.getByLabel('My Name',{exact:true}).fill('Selector draft')
 const project=page.getByRole('combobox',{name:/Default project|Type to search for a project/}).first();await project.fill('Preferences child');await project.press('ArrowLeft');await expect(page.getByRole('option',{name:/Preferences child/})).toBeVisible();await project.press('ArrowDown');await page.keyboard.press('Enter');await expect(project).toHaveValue('Preferences child');await expect(page.getByLabel('My Name',{exact:true})).toHaveValue('Selector draft')
 const timezone=page.getByRole('combobox',{name:'Time zone',exact:true});await timezone.fill('Europe Berlin');await timezone.press('ArrowLeft');await expect(page.getByRole('option',{name:'Europe/Berlin',exact:true})).toHaveCount(0);await timezone.fill('Europe/Berlin');await timezone.press('ArrowLeft');await expect(page.getByRole('option',{name:'Europe/Berlin',exact:true})).toBeVisible();await timezone.press('Enter');await expect(timezone).toHaveValue('Europe/Berlin');await timezone.press('Escape');await expect(timezone).toHaveAttribute('aria-expanded','false')
 const saved=result(page,'/user/settings/general');await save(page).click();expect((await saved).ok()).toBe(true);expect(await stored(page,apiContext)).toMatchObject({default_project_id:2,timezone:'Europe/Berlin',name:'Selector draft'});await page.reload();await expect(project).toHaveValue('Preferences child');await expect(timezone).toHaveValue('Europe/Berlin');await info.attach('search-selectors',{body:await page.screenshot(),contentType:'image/png'})
 const projectHost=page.locator('.multiselect').filter({has:project});await projectHost.getByRole('button',{name:'Clear selection',exact:true}).click();await expect(project).toHaveValue('');await save(page).click();await expect(page.locator('.global-notification')).toContainText('The settings were successfully updated.');expect((await stored(page,apiContext)).default_project_id??0).toBe(0)
})
test('quick add reminder presets custom edits removal escape and actual created task reminder dates',async({authenticatedPage:page,apiContext},info)=>{
 await page.goto('/user/settings/general');await page.getByLabel('Default due time',{exact:true}).fill('16:45');await page.getByRole('button',{name:'Add a reminder…',exact:true}).click();await page.getByRole('button',{name:'2 hours before Due Date',exact:true}).click();await page.getByRole('button',{name:'Add a reminder…',exact:true}).click();await page.getByRole('button',{name:'Custom',exact:true}).click();await page.locator('.reminder-period input').fill('3');await page.getByLabel('Time unit',{exact:true}).selectOption('hours');await page.getByLabel('Before or after',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('button',{name:'3 hours after Due Date',exact:true})).toBeVisible();
 const saved=result(page,'/user/settings/general');await save(page).click();expect((await saved).ok()).toBe(true);const settings=await stored(page,apiContext);expect(settings.frontend_settings.quick_add_default_reminders.map(r=>r.relative_period)).toEqual([-7200,10800]);await info.attach('quick-add-reminders',{body:await page.screenshot(),contentType:'image/png'});await page.goto('/projects/1/1');const entry=page.getByPlaceholder('Add a task…');await entry.fill('Preferences due tomorrow');const created=result(page,'/projects/1/tasks/bulk');await entry.press('Enter');const write=await created;expect(write.ok()).toBe(true);const token=await page.evaluate(()=>localStorage.getItem('token'));const tasks=await apiContext.get('projects/1/views/1/tasks',{headers:{Authorization:`Bearer ${token}`}});expect(tasks.ok()).toBe(true);const task=(await tasks.json()).find(task=>task.title==='Preferences due');expect(task).toBeTruthy();expect(new Date(task.due_date).getUTCHours()).toBe(16);expect(new Date(task.due_date).getUTCMinutes()).toBe(45);expect(task.reminders.map(r=>r.relative_period)).toEqual([-7200,10800]);expect(task.reminders.map(r=>+new Date(r.reminder)-+new Date(task.due_date))).toEqual([-7200000,10800000])
 await page.goto('/user/settings/general');await page.getByRole('button',{name:'Remove this reminder',exact:true}).first().click();await save(page).click();await expect(page.locator('.global-notification')).toContainText('The settings were successfully updated.');expect((await stored(page,apiContext)).frontend_settings.quick_add_default_reminders.map(r=>r.relative_period)).toEqual([10800]);await page.getByLabel('Quick Add Magic Mode').selectOption('disabled');await expect(page.getByRole('button',{name:'Add a reminder…',exact:true})).not.toBeVisible();await page.getByLabel('Quick Add Magic Mode').selectOption('vikunja');await expect(page.getByRole('button',{name:'3 hours after Due Date',exact:true})).toBeVisible()
})
test('saved date time priority and week start preferences drive list and calendar consumers',async({authenticatedPage:page})=>{
 await TaskFactory.create(2,{title:(id:number)=>`Preference task ${id}`,priority:(id:number)=>id===1?2:4,due_date:'2040-06-17T13:20:00Z'});await Factory.seed('task_positions',[{task_id:1,project_view_id:1,position:65536},{task_id:2,project_view_id:1,position:131072}]);await page.goto('/user/settings/general');await page.getByLabel('Date display format').selectOption('yyyy-mm-dd');await page.getByLabel('Time format').selectOption('12h');await page.getByLabel('Minimum visible task priority').selectOption('4');await page.getByLabel('Week starts on').selectOption('3');await save(page).click();await expect(page.locator('.global-notification')).toContainText('The settings were successfully updated.');await page.goto('/projects/1/1');await expect(page.locator('.dueDate').first()).toContainText('2040-06-17 01:20 PM');await expect(page.locator('.priority-label')).toHaveCount(1);await page.locator('.dueDate').first().click();await expect(page.locator('.flatpickr-weekday').first()).toHaveText('Wed');await expect(page.locator('.flatpickr-am-pm')).toBeVisible();await page.keyboard.press('Escape');await page.goto('/user/settings/general');await page.getByLabel('Time format').selectOption('24h');await save(page).click();await expect(page.locator('.global-notification')).toContainText('The settings were successfully updated.');await page.goto('/projects/1/1');await expect(page.locator('.dueDate').first()).toContainText('2040-06-17 13:20')
})
test('default project view honors preference fallback and then last visited explicit view',async({authenticatedPage:page})=>{
 await page.goto('/user/settings/general');await page.getByLabel('Default view').selectOption('kanban');await save(page).click();await expect(page.locator('.global-notification')).toContainText('The settings were successfully updated.');await page.goto('/projects/1');await expect(page).toHaveURL(/\/projects\/1\/4$/);await expect(page.locator('.kanban')).toBeVisible();await page.goto('/projects/1/1');await expect(page.getByPlaceholder('Add a task…')).toBeVisible();await page.goto('/projects/1');await expect(page).toHaveURL(/\/projects\/1\/1$/);await expect(page.getByPlaceholder('Add a task…')).toBeVisible()
})

test('custom reminder escape preserves the accepted positive reminder',async({authenticatedPage:page})=>{
 await page.goto('/user/settings/general');await page.getByRole('button',{name:'Add a reminder…',exact:true}).click();await page.getByRole('button',{name:'Custom',exact:true}).click();await page.locator('.reminder-period input').fill('3');await page.getByLabel('Time unit',{exact:true}).selectOption('hours');await page.getByLabel('Before or after',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('button',{name:'3 hours after Due Date',exact:true})).toBeVisible();await page.getByRole('button',{name:'3 hours after Due Date',exact:true}).click();await page.getByRole('button',{name:'Custom',exact:true}).click();await page.locator('.reminder-period input').fill('5');await page.locator('.reminder-period input').press('Escape');await expect(page.getByRole('button',{name:'3 hours after Due Date',exact:true})).toBeVisible();await expect(save(page)).toBeVisible()
})
