import {test,expect} from './fixtures'
import {TEST_PASSWORD} from '../../frontend/tests/support/constants'
import {UserFactory} from '../../frontend/tests/factories/user'
const response=(page,path:string,method='POST')=>page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(path)&&r.request().method()===method)
const save=(page)=>page.getByRole('button',{name:'Save',exact:true})
const notification=(page)=>page.locator('.global-notification')
async function user(apiContext,page){const token=await page.evaluate(()=>localStorage.getItem('token'));const result=await apiContext.get('user',{headers:{Authorization:`Bearer ${token}`}});expect(result.ok()).toBe(true);return result.json()}
for(const width of [1440,390])test(`general profile preferences save backend and reload ${width}`,async({authenticatedPage:page,apiContext},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/user/settings');await expect(page).toHaveURL(/\/user\/settings\/general$/)
 if(width===390){const banner=page.locator('.add-to-home-screen');await expect(banner).toBeVisible();await banner.getByRole('button',{name:'Close banner',exact:true}).click();await expect(banner).not.toBeVisible()}
 await expect(save(page)).not.toBeVisible();await page.getByLabel('My Name',{exact:true}).fill('Settings reviewer');await page.getByLabel('Week starts on').selectOption('3');await page.getByLabel('Default due time',{exact:true}).fill('16:45');await page.getByLabel('Always show task count on Kanban buckets',{exact:true}).check();await page.getByLabel('Allow other users to add me as a member to teams or projects when they search for my name',{exact:true}).check();await page.getByLabel('Minimum visible task priority').selectOption('4')
 const saved=response(page,'/user/settings/general');await save(page).click();const result=await saved;expect(result.ok()).toBe(true);expect(result.request().postDataJSON()).toMatchObject({name:'Settings reviewer',week_start:3,discoverable_by_name:true,frontend_settings:{default_due_time:'16:45',minimum_priority:4,always_show_bucket_task_count:true}})
 await expect(notification(page)).toContainText('The settings were successfully updated.');await expect(page.locator('.username-dropdown-trigger')).toContainText('Settings reviewer');await expect(save(page)).not.toBeVisible()
 expect((await user(apiContext,page)).settings).toMatchObject({week_start:3,frontend_settings:{default_due_time:'16:45',minimum_priority:4}})
 await info.attach('general-settings',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await page.reload();await expect(page.getByLabel('My Name',{exact:true})).toHaveValue('Settings reviewer');await expect(page.getByLabel('Week starts on')).toHaveValue('3');await expect(page.getByLabel('Always show task count on Kanban buckets',{exact:true})).toBeChecked()
})
test('general failed save retains draft focus and retries actual backend',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/user/settings/general');const name=page.getByLabel('My Name',{exact:true});await name.fill('Retry profile');let fail=true;await page.route('**/api/v1/user/settings/general',route=>fail?route.fulfill({status:500,json:{message:'Fixture settings unavailable'}}):route.continue())
 await save(page).click();await expect(page.getByText('Fixture settings unavailable',{exact:false})).toBeVisible();await expect(name).toHaveValue('Retry profile');expect((await user(apiContext,page)).name).not.toBe('Retry profile');await expect(save(page)).toBeVisible();await name.focus();await name.pressSequentially(' revised');await expect(name).toBeFocused();fail=false;const saved=response(page,'/user/settings/general');await save(page).click();expect((await saved).ok()).toBe(true);await expect(notification(page)).toContainText('The settings were successfully updated.');expect((await user(apiContext,page)).name).toBe('Retry profile revised')
})
test('appearance persists dark light and system and dynamic reminder controls',async({authenticatedPage:page},info)=>{
 await page.goto('/user/settings/general');const appearance=page.getByLabel('Color Scheme');await appearance.selectOption('dark');await save(page).click();await expect(page.locator('html')).toHaveClass(/dark/);await info.attach('settings-dark',{body:await page.screenshot(),contentType:'image/png'});await page.reload();await expect(page.locator('html')).toHaveClass(/dark/)
 await appearance.selectOption('light');await save(page).click();await expect(page.locator('html')).toHaveClass(/light/);await appearance.selectOption('auto');await save(page).click();await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveClass(/dark/);await page.emulateMedia({colorScheme:'light'});await expect(page.locator('html')).toHaveClass(/light/)
 const overdue=page.getByLabel('Send me a summary of my undone overdue tasks every day',{exact:true}),time=page.getByLabel('Overdue tasks reminder email time',{exact:true});await overdue.uncheck();await expect(time).not.toBeVisible();await overdue.check();await expect(time).toBeVisible();await time.fill('10:30');await save(page).click();await expect(notification(page)).toContainText('The settings were successfully updated.')
})
test('actual password update validates rejects current password and persists new login',async({authenticatedPage:page,apiContext,currentUser})=>{
 await page.goto('/user/settings/password-update');await expect(save(page)).toBeDisabled();await page.locator('#password').fill('tiny');await page.locator('#currentPassword').fill(TEST_PASSWORD);await expect(save(page)).toBeDisabled();await page.locator('#password').fill('PreferencesPassword123');await page.locator('#currentPassword').fill('wrong');const bad=response(page,'/user/password');await save(page).click();expect((await bad).ok()).toBe(false);await expect(page.locator('#password')).toHaveValue('PreferencesPassword123');await expect(page.getByText(/Wrong username or password|Wrong password|The old password does not match/)).toBeVisible()
 await page.locator('#currentPassword').fill(TEST_PASSWORD);const good=response(page,'/user/password');await save(page).click();expect((await good).ok()).toBe(true);await expect(notification(page)).toContainText('The password was successfully updated.');const old=await apiContext.post('login',{data:{username:currentUser.username,password:TEST_PASSWORD}});expect(old.status()).toBe(403);const accepted=await apiContext.post('login',{data:{username:currentUser.username,password:'PreferencesPassword123'}});expect(accepted.ok()).toBe(true)
})
test('actual email update password rejection success and refreshed identity',async({authenticatedPage:page,apiContext,currentUser},info)=>{
 await page.goto('/user/settings/email-update');await page.locator('#newEmail').fill('settings-new@example.com');await page.locator('#currentPasswordEmail').fill('wrong');const bad=response(page,'/user/settings/email','PUT');await save(page).click();expect((await bad).ok()).toBe(false);await expect(page.locator('#newEmail')).toHaveValue('settings-new@example.com')
 await page.locator('#currentPasswordEmail').fill(TEST_PASSWORD);const good=response(page,'/user/settings/email','PUT');await save(page).click();expect((await good).ok()).toBe(true);await expect(notification(page)).toContainText('Your email address was successfully updated.');await expect(page.locator('#newEmail')).toHaveValue('');await expect(page.locator('#currentPasswordEmail')).toHaveValue('');await info.attach('email-updated',{body:await page.screenshot(),contentType:'image/png'})
 const login=await apiContext.post('login',{data:{username:'settings-new@example.com',password:TEST_PASSWORD}});expect(login.ok()).toBe(true);expect((await user(apiContext,page)).username).toBe(currentUser.username);await page.reload();await expect(page.locator('#newEmail')).toBeVisible()
})
test('pending email resend and cancel use actual backend and preserve credential drafts',async({page,apiContext},info)=>{
 const [owner]=await UserFactory.create(1,{username:'pending-settings',pending_email:'pending@example.com'});const {login}=await import('../../frontend/tests/support/authenticateUser');await login(page,apiContext,owner);await page.goto('/user/settings/email-update');await expect(page.getByRole('status').filter({hasText:'pending@example.com'})).toContainText('pending@example.com');await page.locator('#newEmail').fill('draft@example.com');await page.locator('#currentPasswordEmail').fill('draft-password')
 const resend=response(page,'/user/settings/email/resend');await page.getByRole('button',{name:'Resend confirmation email',exact:true}).click();expect((await resend).ok()).toBe(true);await expect(notification(page)).toContainText("We've sent you a new confirmation link.");await expect(page.locator('#newEmail')).toHaveValue('draft@example.com');await info.attach('pending-email',{body:await page.screenshot(),contentType:'image/png'})
 const cancel=response(page,'/user/settings/email','DELETE');await page.getByRole('button',{name:'Cancel change',exact:true}).click();expect((await cancel).ok()).toBe(true);await expect(notification(page)).toContainText('The email change was cancelled.');await expect(page.getByRole('button',{name:'Cancel change',exact:true})).not.toBeVisible();expect((await user(apiContext,page)).pending_email??'').toBe('');await expect(page.locator('#newEmail')).toHaveValue('draft@example.com')
})
test('delayed settings save cannot replace later route drafts or duplicate a request',async({authenticatedPage:page})=>{
 let started!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);let count=0;await page.route('**/api/v1/user/settings/general',async route=>{count++;const result=await route.fetch();started();await gate;await route.fulfill({response:result}).catch(()=>{})})
 await page.goto('/user/settings/general');await page.getByLabel('My Name',{exact:true}).fill('Late settings');await save(page).click();await ready;await expect(save(page)).toBeDisabled();await page.getByRole('link',{name:'Update Your Email Address',exact:true}).click();await page.locator('#newEmail').fill('later-draft@example.com');await page.locator('#newEmail').focus();release();await page.unroute('**/api/v1/user/settings/general');await page.waitForLoadState('networkidle');expect(count).toBe(1);await expect(page).toHaveURL(/email-update$/);await expect(page.locator('#newEmail')).toHaveValue('later-draft@example.com');await expect(page.locator('#newEmail')).toBeFocused();await expect(notification(page)).not.toContainText('The settings were successfully updated.')
})
test('localization and appearance field values persist without dropping unrelated frontend preferences',async({authenticatedPage:page,apiContext,userToken})=>{
 const initial=await apiContext.get('user',{headers:{Authorization:`Bearer ${userToken}`}});expect(initial.ok()).toBe(true);const initialSettings=(await initial.json()).settings
 const seeded=await apiContext.post('user/settings/general',{headers:{Authorization:`Bearer ${userToken}`},data:{...initialSettings,language:'en',timezone:'UTC',frontend_settings:{comment_sort_order:'desc',quick_add_default_reminders:[{relative_period:-3600,relative_to:'due_date',reminder:null}]}}});expect(seeded.ok()).toBe(true)
 await page.goto('/user/settings/general');const before=(await user(apiContext,page)).settings.frontend_settings;await page.getByLabel('Date display format').selectOption('yyyy-mm-dd');await expect(page.getByLabel('Time format')).toBeVisible();await page.getByLabel('Time format').selectOption('12h');await page.getByLabel('Background brightness',{exact:true}).fill('200');await page.getByLabel('Background brightness',{exact:true}).blur();await expect(page.getByLabel('Background brightness',{exact:true})).toHaveValue('100');await page.getByLabel('Language').selectOption('de-DE');const saved=response(page,'/user/settings/general');await save(page).click();expect((await saved).ok()).toBe(true);await expect(page.locator('html')).toHaveAttribute('lang','de-DE');const after=(await user(apiContext,page)).settings;expect(after).toMatchObject({language:'de-DE',frontend_settings:{date_display:'yyyy-mm-dd',time_format:'12h',background_brightness:100,comment_sort_order:before.comment_sort_order,quick_add_default_reminders:before.quick_add_default_reminders}});await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','de-DE');await expect(page.getByLabel('Mein Name',{exact:true})).toBeVisible()
})
test('editing while save is in flight keeps the later draft dirty and focused',async({authenticatedPage:page,apiContext})=>{
 await page.goto('/user/settings/general');let started!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);await page.route('**/api/v1/user/settings/general',async route=>{const result=await route.fetch();started();await gate;await route.fulfill({response:result})})
 const name=page.getByLabel('My Name',{exact:true});await name.fill('First profile');await save(page).click();await ready;await name.fill('Later draft');await name.focus();release();await expect(notification(page)).toContainText('The settings were successfully updated.');await expect(name).toHaveValue('Later draft');await expect(name).toBeFocused();await expect(save(page)).toBeVisible();await expect(save(page)).toBeEnabled();expect((await user(apiContext,page)).name).toBe('First profile');await page.unroute('**/api/v1/user/settings/general');const saved=response(page,'/user/settings/general');await save(page).click();expect((await saved).ok()).toBe(true);expect((await user(apiContext,page)).name).toBe('Later draft')
})
