import {test, expect} from './fixtures'
import {TEST_PASSWORD} from '../../frontend/tests/support/constants'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
import {setupApiUrl} from '../../frontend/tests/support/authenticateUser'

// Identical backend and outcomes for both shipped applications. These journeys
// deliberately use form labels and visible CSS, never native implementation IDs.
const save = page => page.getByRole('button', {name: 'Save', exact: true})
const response = (page, path: string, method: string) => page.waitForResponse(r => new URL(r.url()).pathname.endsWith(path) && r.request().method() === method)
async function headers(page) {return {Authorization: `Bearer ${await page.evaluate(() => localStorage.getItem('token'))}`}}
async function read(page, apiContext, path: string, authorization?: Record<string, string>) {const result = await apiContext.get(path, {headers: authorization ?? await headers(page)}); expect(result.ok()).toBe(true); return result.json()}
async function dismissInstall(page) {
 const banner = page.locator('.add-to-home-screen')
 if (await banner.isVisible()) await banner.getByRole('button', {name: 'Close banner', exact: true}).click()
}
async function creationFocus(page, name) {
 // Paired browser observations establish the rendered focus target. Modal
 // showModal overrides the earlier Vue directive on desktop too. Soft keeps
 // later CRUD evidence on failure without changing the case's pass criterion.
 await expect(name).toBeVisible()
 const target = page.viewportSize()!.width > 768 ? 'Close dialog' : 'Close'
 await expect.soft(page.getByRole('dialog').getByRole('button', {name: target, exact: true}).first()).toBeFocused()
}
async function capture(page, info, name: string) {
 await expect(page.locator('html')).toHaveClass(new RegExp(info.project.use.colorScheme))
 await page.evaluate(async () => {await document.fonts.ready})
 await info.attach(name, {body: await page.screenshot({fullPage: true, animations: 'disabled'}), contentType: 'image/png'})
 await info.attach(name + '-forms', {body: JSON.stringify(await page.locator('input, select, button, h1, h2').evaluateAll(elements => elements.filter(el => el.getBoundingClientRect().width).map(el => {
  const r = el.getBoundingClientRect(), s = getComputedStyle(el)
  const fieldLabels = 'labels' in el ? Array.from((el as HTMLInputElement).labels ?? [], label => label.textContent?.trim()).join(' ') : ''
  return {tag: el.tagName, label: fieldLabels || el.getAttribute('aria-label') || el.textContent?.trim(), id: el.id, rect: {x: r.x, y: r.y, width: r.width, height: r.height}, font: s.font, color: s.color, background: s.backgroundColor}
 })), null, 2), contentType: 'application/json'})
}
test('general settings rejected save retry backend reload and keyboard focus', async ({authenticatedPage: page, apiContext}, info) => {
 await page.goto('/user/settings/general')
 const name = page.getByLabel('My Name', {exact: true})
 await expect(name).toBeVisible(); await dismissInstall(page)
 await name.fill('Device profile'); await page.getByLabel('Week starts on').selectOption('3')
 let fail = true
 await page.route('**/api/v1/user/settings/general', route => fail ? route.fulfill({status: 503, json: {message: 'Fixture profile unavailable'}}) : route.continue())
 const rejected = response(page, '/user/settings/general', 'POST'); await save(page).click(); expect((await rejected).status()).toBe(503)
 await expect(page.getByText('Fixture profile unavailable', {exact: false})).toBeVisible()
 await expect(name).toHaveValue('Device profile'); expect((await read(page, apiContext, 'user')).name).not.toBe('Device profile')
 await name.focus(); await name.pressSequentially(' revised'); await expect(name).toBeFocused()
 await capture(page, info, 'profile-error-draft')
 fail = false
 const accepted = response(page, '/user/settings/general', 'POST'); await save(page).click(); expect((await accepted).ok()).toBe(true)
 await expect.poll(async () => (await read(page, apiContext, 'user')).name).toBe('Device profile revised')
 expect((await read(page, apiContext, 'user')).settings.week_start).toBe(3)
 await page.reload(); await expect(name).toHaveValue('Device profile revised'); await expect(page.getByLabel('Week starts on')).toHaveValue('3')
 await capture(page, info, 'profile-reloaded')
})
test('password and email rejection acceptance persisted credentials and deep reload', async ({authenticatedPage: page, apiContext, currentUser}, info) => {
 await page.goto('/user/settings/password-update')
 await expect(page.locator('#password')).toBeVisible(); await dismissInstall(page)
 await page.locator('#password').fill('DevicePreferences123'); await page.locator('#currentPassword').fill('wrong')
 const rejected = response(page, '/user/password', 'POST'); await save(page).click(); expect((await rejected).ok()).toBe(false)
 await expect(page.locator('#password')).toHaveValue('DevicePreferences123')
 await page.locator('#currentPassword').fill(TEST_PASSWORD)
 const accepted = response(page, '/user/password', 'POST'); await save(page).click(); expect((await accepted).ok()).toBe(true)
 expect((await apiContext.post('login', {data: {username: currentUser.username, password: TEST_PASSWORD}})).status()).toBe(403)
 expect((await apiContext.post('login', {data: {username: currentUser.username, password: 'DevicePreferences123'}})).ok()).toBe(true)
 await page.goto('/user/settings/email-update')
 await page.locator('#newEmail').fill('device-review@example.com'); await page.locator('#currentPasswordEmail').fill('wrong')
 const badEmail = response(page, '/user/settings/email', 'PUT'); await save(page).click(); expect((await badEmail).ok()).toBe(false)
 await expect(page.locator('#newEmail')).toHaveValue('device-review@example.com'); await capture(page, info, 'email-rejected')
 await page.locator('#currentPasswordEmail').fill('DevicePreferences123')
 const goodEmail = response(page, '/user/settings/email', 'PUT'); await save(page).click(); expect((await goodEmail).ok()).toBe(true)
 await expect(page.locator('#newEmail')).toHaveValue('')
 expect((await apiContext.post('login', {data: {username: 'device-review@example.com', password: 'DevicePreferences123'}})).ok()).toBe(true)
 await page.reload(); await expect(page.locator('#newEmail')).toBeVisible(); await capture(page, info, 'email-reloaded')
})
test('project edit archive reload unarchive deletion cancel and actual descendant removal', async ({authenticatedPage: page, apiContext}, info) => {
 await ProjectFactory.create(2, {title: (id: number) => id === 1 ? 'Device parent' : 'Device child', parent_project_id: (id: number) => id === 1 ? 0 : 1})
 await createDefaultViews(1); await createDefaultViews(2, 5); await TaskFactory.create(2, {title: 'Device task', project_id: (id: number) => id})
 await page.goto('/projects'); await expect(page.locator('.project-grid')).toContainText('Device parent')
 await dismissInstall(page)
 const authorization = await headers(page)
 await page.goto('/projects/1/settings/edit'); const dialog = page.getByRole('dialog')
 await dialog.locator('input').filter({visible: true}).first().fill('Device renamed')
 await page.getByLabel('Project Identifier', {exact: true}).fill('DEVICE')
 const updated = response(page, '/projects/1', 'POST'); await dialog.getByRole('button', {name: 'Save', exact: true}).click(); expect((await updated).ok()).toBe(true)
 await expect(dialog).not.toBeVisible()
 expect(await read(page, apiContext, 'projects/1', authorization)).toMatchObject({title: 'Device renamed', identifier: 'DEVICE'})
 await page.goto('/projects/1/settings/archive'); await expect(dialog.getByRole('button', {name: 'Do it!', exact: true})).toBeVisible(); await capture(page, info, 'archive-confirmation')
 await page.getByRole('button', {name: 'Do it!', exact: true}).click()
 await expect(dialog).not.toBeVisible()
 await expect.poll(async () => (await read(page, apiContext, 'projects/1', authorization)).is_archived).toBe(true)
 await page.goto('/projects'); await expect(page.locator('.project-grid')).not.toContainText('Device renamed')
 await page.getByText('Show Archived', {exact: true}).click(); await expect(page.locator('.project-grid')).toContainText('Device renamed')
 await page.reload(); await page.goto('/projects/1/settings/archive'); await page.getByRole('button', {name: 'Do it!', exact: true}).click()
 await expect(dialog).not.toBeVisible()
 await expect.poll(async () => (await read(page, apiContext, 'projects/1', authorization)).is_archived).toBe(false)
 await page.goto('/projects/1/settings/delete'); await expect(dialog).toContainText('2 tasks'); await capture(page, info, 'delete-confirmation')
 await page.getByRole('button', {name: 'Cancel', exact: true}).click(); await expect(dialog).not.toBeVisible(); expect((await read(page, apiContext, 'projects/1', authorization)).title).toBe('Device renamed')
 await page.goto('/projects/1/settings/delete'); const deleted = response(page, '/projects/1', 'DELETE'); await page.getByRole('button', {name: 'Do it!', exact: true}).click(); expect((await deleted).ok()).toBe(true)
 await expect(page).toHaveURL(/\/$/)
 for (const id of [1, 2]) expect((await apiContext.get(`projects/${id}`, {headers: authorization})).status()).toBe(404)
})
test('password share create anonymous rejection authentication reload and revocation', async ({authenticatedPage: page, apiContext, browser}, info) => {
 await ProjectFactory.create(1, {title: 'Device shared project'}); await createDefaultViews(1)
 await TaskFactory.create(1, {title: 'Device shared task'})
 await page.goto('/projects'); await expect(page.locator('.project-grid')).toContainText('Device shared project')
 await dismissInstall(page)
 await page.goto('/projects/1/settings/share')
 const links = page.getByRole('heading', {name: /^Share Links/}).locator('..')
 await links.getByRole('button', {name: 'Create a link share', exact: true}).click()
 await page.getByLabel('Name (optional)', {exact: true}).fill('Device password link')
 await page.getByLabel('Password (optional)', {exact: true}).fill('device-share-password')
 const created = response(page, '/projects/1/shares', 'PUT'); await links.getByRole('button', {name: 'Share', exact: true}).click(); expect((await created).ok()).toBe(true)
 const shares = await read(page, apiContext, 'projects/1/shares'); expect(shares).toHaveLength(1)
 expect(shares[0]).toMatchObject({name: 'Device password link', permission: 0, sharing_type: 2})
 await capture(page, info, 'share-created')
 const anonymous = await browser.newContext({baseURL: info.project.use.baseURL, viewport: page.viewportSize()!, colorScheme: info.project.use.colorScheme, locale: 'en-US', timezoneId: 'UTC', serviceWorkers: 'block'})
 try {
  const visitor = await anonymous.newPage(); await setupApiUrl(visitor)
  await visitor.goto(`/share/${shares[0].hash}/auth`)
  const password = visitor.locator('#linkSharePassword'); await password.fill('wrong-password'); await password.press('Enter')
  await expect(visitor.getByText('The password is invalid.', {exact: true})).toBeVisible(); await expect(password).toHaveValue('wrong-password')
  await capture(visitor, info, 'share-password-rejected')
  await password.fill('device-share-password'); await password.press('Enter')
  await expect(visitor.locator('.tasks')).toContainText('Device shared task')
  expect(await visitor.evaluate(() => localStorage.getItem('token'))).toBeNull()
  await expect(visitor.getByPlaceholder('Add a task…')).toHaveCount(0)
  const challenge = response(visitor, `/shares/${shares[0].hash}/auth`, 'POST')
  await visitor.reload(); expect((await challenge).status()).toBe(412)
  await expect(password).toBeVisible(); await expect(visitor.locator('.tasks')).toHaveCount(0)
  await capture(visitor, info, 'anonymous-share-reload-password-challenge')
  await password.fill('device-share-password')
  const reauthenticated = response(visitor, `/shares/${shares[0].hash}/auth`, 'POST'); await password.press('Enter'); expect((await reauthenticated).ok()).toBe(true)
  await expect(visitor.locator('.tasks')).toContainText('Device shared task'); await capture(visitor, info, 'anonymous-share-reloaded')
  await links.getByRole('button', {name: 'Remove a link share', exact: true}).click()
  await page.getByRole('button', {name: 'Do it!', exact: true}).click()
  await expect.poll(async () => (await read(page, apiContext, 'projects/1/shares')).length).toBe(0)
  expect((await apiContext.post(`shares/${shares[0].hash}/auth`, {data: {password: 'device-share-password'}})).ok()).toBe(false)
  const denied = response(visitor, `/shares/${shares[0].hash}/auth`, 'POST')
  await visitor.goto(`/share/${shares[0].hash}/auth`)
  const deniedResponse = await denied; expect(deniedResponse.ok()).toBe(false)
  const denial = await deniedResponse.json(); expect(typeof denial.message).toBe('string')
  await expect(visitor.getByText(denial.message, {exact: false})).toBeVisible()
  await expect(visitor.locator('.tasks')).toHaveCount(0)
  await capture(visitor, info, 'anonymous-share-revoked')
 } finally {await anonymous.close()}
})
test('team create edit reload delete cancellation and backend removal', async ({authenticatedPage: page, apiContext}, info) => {
 await page.goto('/teams'); const create = page.getByRole('link', {name: 'Create a team', exact: true}).first()
 await expect(create).toBeVisible(); await dismissInstall(page); await create.click()
 const name = page.locator('#teamName'); await creationFocus(page, name); await name.fill('Device created team')
 const accepted = response(page, '/teams', 'PUT'); await name.press('Enter'); expect((await accepted).ok()).toBe(true)
 await expect(page).toHaveURL(/\/teams\/\d+\/edit$/); const id = Number(new URL(page.url()).pathname.split('/')[2])
 expect(await read(page, apiContext, `teams/${id}`)).toMatchObject({name: 'Device created team'})
 const field = page.getByLabel('Team Name', {exact: true}); await field.fill('Device renamed team'); await field.focus(); await expect(field).toBeFocused()
 const updated = response(page, `/teams/${id}`, 'POST'); await save(page).click(); expect((await updated).ok()).toBe(true)
 await page.reload(); await expect(field).toHaveValue('Device renamed team'); await capture(page, info, 'team-reloaded')
 const remove = page.getByRole('button', {name: 'Delete the team', exact: true})
 await remove.click(); await page.getByRole('dialog').getByRole('button', {name: 'Cancel', exact: true}).click()
 expect((await read(page, apiContext, `teams/${id}`)).name).toBe('Device renamed team')
 await remove.click(); const deleted = response(page, `/teams/${id}`, 'DELETE'); await page.getByRole('button', {name: 'Do it!', exact: true}).click(); expect((await deleted).ok()).toBe(true)
 await expect(page).toHaveURL(/\/teams$/); expect((await apiContext.get(`teams/${id}`, {headers: await headers(page)})).status()).toBe(403)
 expect((await read(page, apiContext, 'teams')).some(team => team.id === id)).toBe(false)
})
test('label create edit reload delete cancellation and backend removal', async ({authenticatedPage: page, apiContext}, info) => {
 async function labels() {return (await read(page, apiContext, '../v2/labels?per_page=1000')).items}
 await page.goto('/labels'); const create = page.getByRole('link', {name: 'New label', exact: true}).first()
 await expect(create).toBeVisible(); await dismissInstall(page); await create.click()
 const name = page.locator('#labelTitle'); await creationFocus(page, name); await name.fill('Device created label')
 await page.getByRole('dialog').locator('input[type=color]').fill('#1973ff')
 const accepted = response(page, '/labels', 'POST'); await name.press('Enter'); expect((await accepted).ok()).toBe(true)
 await expect(page.locator('.labels-list')).toContainText('Device created label')
 const created = (await labels()).find(label => label.title === 'Device created label'); expect(created).toMatchObject({hex_color: '1973ff'})
 await page.locator('.labels-list .tag').filter({hasText: 'Device created label'}).getByRole('button', {name: 'Edit Label', exact: true}).click()
 const editor = page.locator('.column.is-4').filter({has: page.getByText('Edit Label', {exact: true})})
 await editor.getByLabel('Title', {exact: true}).fill('Device renamed label')
 const updated = response(page, `/labels/${created.id}`, 'PUT'); await editor.getByRole('button', {name: 'Save', exact: true}).click(); expect((await updated).ok()).toBe(true)
 expect((await labels()).find(label => label.id === created.id)).toMatchObject({title: 'Device renamed label', hex_color: created.hex_color})
 await page.reload(); await expect(page.locator('.labels-list')).toContainText('Device renamed label'); await capture(page, info, 'label-reloaded')
 await page.locator('.labels-list .tag').filter({hasText: 'Device renamed label'}).getByRole('button', {name: 'Edit Label', exact: true}).click()
 const remove = editor.getByRole('button', {name: 'Delete this label', exact: true})
 await remove.click(); await page.getByRole('dialog').getByRole('button', {name: 'Cancel', exact: true}).click()
 expect((await labels()).some(label => label.id === created.id)).toBe(true)
 await remove.click(); const deleted = response(page, `/labels/${created.id}`, 'DELETE'); await page.getByRole('button', {name: 'Do it!', exact: true}).click(); expect((await deleted).ok()).toBe(true)
 await expect(page.locator('.labels-list')).not.toContainText('Device renamed label'); expect((await labels()).some(label => label.id === created.id)).toBe(false)
})
