import {test, expect} from './fixtures'
import {installEditorSelectionTrace} from './editor-selection-trace'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {TaskCommentFactory} from '../../frontend/tests/factories/task_comment'
import {UserFactory} from '../../frontend/tests/factories/user'
import {UserProjectFactory} from '../../frontend/tests/factories/users_project'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
const rows = page => page.locator('.comments .media.comment[id^="comment-"]')
const composer = page => page.locator('.comments .media.comment:not([id]) .ProseMirror')
const commentButton = page => page.getByRole('button', {name: 'Comment', exact: true})
test.beforeEach(async ({currentUser}) => { await ProjectFactory.create(1, {title: 'Comment review', owner_id: currentUser.id}); await createDefaultViews(1); await TaskFactory.create(2, {title: i => i === 1 ? 'Alpha task' : 'Beta task', created_by_id: currentUser.id}); await TaskCommentFactory.create(1, {id: 1, task_id: 1, author_id: currentUser.id, comment: '<p>Original comment</p>', created: '2026-01-01T00:00:00Z', updated: '2026-01-01T00:00:00Z'}) })
for (const width of [1440, 390]) test(`comment create edit discard delete, keyboard and reload ${width}`, async ({authenticatedPage: page}, info) => {
 await page.setViewportSize({width, height: 900}); await page.goto('/tasks/1'); await expect(rows(page)).toHaveCount(1); await page.waitForLoadState('networkidle'); await rows(page).first().scrollIntoViewIfNeeded(); const initialOverflow = await page.evaluate(()=>document.body.style.overflow); await page.screenshot({path:info.outputPath('comments-preview.png'), animations:'disabled'});
 await rows(page).first().locator('.comment-permalink').hover(); await expect(page.locator('.v-popper__popper--shown')).toContainText('Copy permalink to this comment'); await composer(page).click(); await expect(page.locator('.v-popper__popper--shown')).not.toBeVisible(); await composer(page).fill('New comment'); await expect(composer(page)).toBeFocused(); const created = page.waitForResponse(r => /\/tasks\/1\/comments$/.test(new URL(r.url()).pathname) && r.request().method() === 'PUT'); await commentButton(page).click(); expect((await created).request().postDataJSON().comment).toBe('<p>New comment</p>'); await expect(rows(page)).toHaveCount(2); await expect(composer(page)).toHaveText('');
 const row = rows(page).last(); await row.getByRole('button',{name:'Edit',exact:true}).click(); const editor = row.locator('.ProseMirror'); await expect(editor).toBeFocused(); await page.screenshot({path:info.outputPath('comments-edit.png'),animations:'disabled'}); await editor.press('ControlOrMeta+End'); await editor.pressSequentially(' discard'); await editor.press('Escape'); await expect(editor).toHaveText('New comment'); await row.getByRole('button',{name:'Edit',exact:true}).click(); await editor.fill('Edited comment'); const saved = page.waitForResponse(r => /\/tasks\/1\/comments\/\d+$/.test(new URL(r.url()).pathname) && r.request().method() === 'POST'); await row.getByRole('button',{name:'Save',exact:true}).click(); expect((await saved).request().postDataJSON().comment).toBe('<p>Edited comment</p>'); await page.reload(); await expect(rows(page).last()).toContainText('Edited comment'); await rows(page).last().getByRole('button',{name:'Delete',exact:true}).click(); const dialog=page.getByRole('dialog',{name:'Delete this comment'}); await expect(dialog).toBeVisible(); await page.screenshot({path:info.outputPath('comments-delete.png'),animations:'disabled'}); await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint'))); await expect(dialog).toBeVisible(); expect(await dialog.evaluate(el=>el.matches(':modal'))).toBe(false); await page.evaluate(()=>window.dispatchEvent(new Event('afterprint'))); expect(await dialog.evaluate(el=>el.matches(':modal'))).toBe(true); await dialog.getByRole('button',{name:'Cancel',exact:true}).click(); await expect(dialog).toHaveCount(0); await expect(rows(page).last().getByRole('button',{name:'Delete',exact:true})).toBeFocused(); await rows(page).last().getByRole('button',{name:'Delete',exact:true}).click(); await page.getByRole('dialog').getByRole('button',{name:'Do it!',exact:true}).click(); await expect(rows(page)).toHaveCount(1); await expect(page.locator('dialog[open]')).toHaveCount(0); expect(await page.evaluate(()=>document.body.style.overflow)).toBe(initialOverflow); await page.reload(); await expect(rows(page)).toHaveCount(1)
})
test('reply strips mention notifications and preserves quote header, jump and deleted parent', async ({authenticatedPage:page,currentUser},info) => {
 await TaskCommentFactory.create(1,{id:1,task_id:1,author_id:currentUser.id,comment:'<p>Hello <mention-user data-id="quoted-user" data-label="Quoted User">Quoted User</mention-user></p>'}); await page.goto('/tasks/1'); await rows(page).first().getByRole('button',{name:'Reply',exact:true}).click(); const quote=composer(page).locator('blockquote[data-comment-id="1"]'); await expect(quote).toContainText('@Quoted User'); await expect(quote.locator('.mention-user')).toHaveCount(0); await expect(composer(page)).toBeFocused(); await composer(page).press('ControlOrMeta+End'); await composer(page).pressSequentially(' Reply body'); const created=page.waitForResponse(r=>r.request().method()==='PUT'&&/\/comments$/.test(new URL(r.url()).pathname)); await commentButton(page).click(); expect((await created).request().postDataJSON().comment).not.toContain('mention-user'); await expect(rows(page)).toHaveCount(2); const reply=rows(page).last(); await expect(reply.locator('.comment-quote__author')).toContainText('migration-reviewer'); await page.screenshot({path:info.outputPath('comments-reply.png'),animations:'disabled'}); await reply.getByRole('button',{name:'Jump to original comment'}).click(); await expect(rows(page).first()).toHaveClass(/comment-highlight/); await rows(page).first().getByRole('button',{name:'Delete',exact:true}).click(); await page.getByRole('dialog').getByRole('button',{name:'Do it!',exact:true}).click(); await expect(rows(page)).toHaveCount(1); await expect(rows(page).locator('.comment-quote__author--missing')).toContainText('deleted comment'); await page.reload(); await expect(rows(page).locator('.comment-quote__author--missing')).toContainText('deleted comment')
})
test('failed create keeps composer draft through reload and successful retry',async ({authenticatedPage:page})=>{
 await page.goto('/tasks/1'); await composer(page).fill('Retained composer draft'); await page.route('**/api/v1/tasks/1/comments',route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:'{"message":"Fixture rejection"}'}):route.continue()); await commentButton(page).click(); await expect(page.locator('.vue-notification.error')).toContainText('Fixture rejection'); await expect(composer(page)).toHaveText('Retained composer draft'); expect(await page.evaluate(()=>localStorage.getItem('editorDraft-task-comment-1'))).toBe('<p>Retained composer draft</p>'); await page.reload(); await expect(composer(page)).toHaveText('Retained composer draft'); await page.unroute('**/api/v1/tasks/1/comments'); await commentButton(page).click(); await expect(rows(page)).toHaveCount(2); expect(await page.evaluate(()=>localStorage.getItem('editorDraft-task-comment-1'))).toBeNull()
})
test('failed edit keeps row draft and focus mode for retry',async ({authenticatedPage:page})=>{
 await page.goto('/tasks/1'); const row=rows(page).first(); await row.getByRole('button',{name:'Edit',exact:true}).click(); await row.locator('.ProseMirror').fill('Retained edit'); await page.route('**/api/v1/tasks/1/comments/1',route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:'{"message":"Fixture edit rejection"}'}):route.continue()); await row.getByRole('button',{name:'Save',exact:true}).click(); await expect(row.locator('.ProseMirror')).toHaveText('Retained edit'); await expect(row.locator('.ProseMirror')).toHaveAttribute('contenteditable','true'); await expect(page.locator('.vue-notification.error')).toContainText('Fixture edit rejection'); await page.unroute('**/api/v1/tasks/1/comments/1'); await row.getByRole('button',{name:'Save',exact:true}).click(); await page.reload(); await expect(rows(page).first()).toContainText('Retained edit')
})
test('pending create retains a newer composer draft and loading state',async({authenticatedPage:page})=>{
 await page.goto('/tasks/1'); await composer(page).fill('Submitted comment'); let release, seen; const gate=new Promise<void>(r=>{release=r}), requested=new Promise<void>(r=>{seen=r}); await page.route('**/api/v1/tasks/1/comments',async route=>{if(route.request().method()==='PUT'){seen();await gate};await route.continue()}); await commentButton(page).click(); await requested; await expect(page.getByText('Creating comment…',{exact:true})).toBeVisible(); await composer(page).fill('Newer draft'); await expect(commentButton(page)).toBeDisabled(); release(); await expect(rows(page)).toHaveCount(2); await expect(composer(page)).toHaveText('Newer draft'); expect(await page.evaluate(()=>localStorage.getItem('editorDraft-task-comment-1'))).toBe('<p>Newer draft</p>')
})
test('pending comment edit aborts on navigation without stale publication',async({authenticatedPage:page})=>{
 await page.goto('/tasks/1'); const row=rows(page).first(); await row.getByRole('button',{name:'Edit',exact:true}).click(); await row.locator('.ProseMirror').fill('Pending edit'); let release, seen; const gate=new Promise<void>(r=>{release=r}),requested=new Promise<void>(r=>{seen=r}), failures:string[]=[]; page.on('requestfailed',r=>{if(/\/tasks\/1\/comments\/1$/.test(new URL(r.url()).pathname))failures.push(r.failure()?.errorText||'')}); await page.route('**/api/v1/tasks/1/comments/1',async route=>{if(route.request().method()==='POST'){seen();await gate};try{await route.continue()}catch{/* Owner cancellation ends interception. */}}); await row.getByRole('button',{name:'Save',exact:true}).click(); await requested; await expect(row.getByText('Saving…',{exact:true})).toBeVisible(); await page.getByRole('link',{name:'Comment review',exact:true}).first().click(); await expect(page).toHaveURL(/\/projects\/1/); await expect.poll(()=>failures.length).toBe(1); release(); await page.goto('/tasks/2'); await expect(rows(page)).toHaveCount(0); await expect(composer(page)).toHaveText(''); await expect(page.locator('dialog[open]')).toHaveCount(0)
})
test('foreign author and read-only project cannot edit or delete comments',async({authenticatedPage:page,currentUser})=>{
 const [owner]=await UserFactory.create(1,{id:101,username:'comment-owner'},false); await TaskCommentFactory.create(1,{id:2,task_id:1,author_id:owner.id,comment:'Foreign author'},false); await page.goto('/tasks/1'); const foreign=page.locator('#comment-2'); await expect(foreign).toContainText('Foreign author'); await expect(foreign.getByRole('button',{name:'Reply',exact:true})).toBeVisible(); await expect(foreign.getByRole('button',{name:'Edit',exact:true})).toBeVisible(); await foreign.getByRole('button',{name:'Edit',exact:true}).click(); await expect(foreign.locator('.ProseMirror')).toHaveAttribute('contenteditable','false'); await expect(foreign.getByRole('button',{name:'Delete',exact:true})).toHaveCount(0); await ProjectFactory.create(1,{id:2,title:'Read only comments',owner_id:owner.id},false); await UserProjectFactory.create(1,{project_id:2,user_id:currentUser.id,permission:0}); await TaskFactory.create(1,{id:3,project_id:2,created_by_id:owner.id},false); await TaskCommentFactory.create(1,{id:3,task_id:3,author_id:currentUser.id,comment:'Protected comment'},false); const writes:string[]=[];page.on('request',r=>{if(/\/tasks\/3\/comments/.test(new URL(r.url()).pathname)&&r.method()!=='GET')writes.push(r.url())}); await page.goto('/tasks/3'); await expect(rows(page)).toContainText('Protected comment'); await expect(commentButton(page)).toHaveCount(0); await expect(rows(page).getByRole('button',{name:'Edit',exact:true})).toHaveCount(0); await expect(rows(page).getByRole('button',{name:'Reply',exact:true})).toHaveCount(0); await rows(page).locator('.ProseMirror').dblclick(); await page.keyboard.press('e'); await expect(rows(page).locator('.ProseMirror')).toHaveAttribute('contenteditable','false'); expect(writes).toEqual([])
})
test('comment pagination loading and rejected page retry preserve the composer',async({authenticatedPage:page,currentUser,apiContext})=>{
 const config=await (await apiContext.get('info')).json(), size=config.max_items_per_page; await TaskCommentFactory.create(size+1,{task_id:1,author_id:currentUser.id,comment:i=>`Page comment ${i}`,created:i=>new Date(Date.UTC(2026,0,1,0,i)).toISOString()}); await page.goto('/tasks/1'); await expect(rows(page)).toHaveCount(size); await composer(page).fill('Draft during pagination'); let release,seen; const gate=new Promise<void>(r=>{release=r}),requested=new Promise<void>(r=>{seen=r}); await page.route('**/api/v1/tasks/1/comments?*',async route=>{if(new URL(route.request().url()).searchParams.get('page')==='2'){seen();await gate;await route.fulfill({status:500,json:{message:'Page fixture rejection'}})}else await route.continue()}); await page.locator('.comments nav.pagination').getByRole('button',{name:'Goto page 2'}).click(); await requested; await expect(page.getByText('Loading comments…',{exact:true})).toBeVisible(); await expect(composer(page)).toHaveText('Draft during pagination'); release(); await expect(page.locator('.vue-notification.error')).toContainText('Page fixture rejection'); await expect(composer(page)).toHaveText('Draft during pagination'); await page.unroute('**/api/v1/tasks/1/comments?*'); await page.locator('.comments nav.pagination').getByRole('button',{name:'Goto page 2'}).click(); await expect(rows(page)).toHaveCount(1); await expect(rows(page)).toContainText(`Page comment ${size+1}`); await expect(composer(page)).toHaveText('Draft during pagination'); await page.locator('.comments nav.pagination').getByRole('button',{name:'Previous',exact:true}).click(); await expect(rows(page)).toHaveCount(size)
})
test('comment reaction picker adds, reloads and removes using the existing API',async({authenticatedPage:page},info)=>{
 await page.goto('/tasks/1'); const row=rows(page).first(); await row.getByRole('button',{name:'Add your reaction',exact:true}).click(); const picker=row.locator('emoji-picker'); await expect(picker).toBeVisible(); await picker.locator('button[title="grinning face"]').click(); await expect(row.getByRole('button',{name:'😀 1',exact:true})).toBeVisible(); await expect(picker).toHaveCount(0); await page.screenshot({path:info.outputPath('comments-reaction.png'),animations:'disabled'}); await page.reload(); await expect(rows(page).first().getByRole('button',{name:'😀 1',exact:true})).toBeVisible(); await rows(page).first().getByRole('button',{name:'😀 1',exact:true}).click(); await expect(rows(page).first().getByRole('button',{name:'😀 1',exact:true})).toHaveCount(0); await page.reload(); await expect(rows(page).first().getByRole('button',{name:'😀 1',exact:true})).toHaveCount(0)
})
test('comment upload cancelled by navigation cannot insert into another task draft',async({authenticatedPage:page})=>{
 await page.goto('/tasks/1'); let release,seen;const gate=new Promise<void>(r=>{release=r}),requested=new Promise<void>(r=>{seen=r}),failures:string[]=[];page.on('requestfailed',r=>{if(/\/tasks\/1\/attachments$/.test(new URL(r.url()).pathname))failures.push(r.failure()?.errorText||'')});await page.route('**/api/v1/tasks/1/attachments',async route=>{seen();await gate;try{await route.continue()}catch{/* Owner cancellation ends interception. */}});await page.locator('.comments .media.comment:not([id]) [data-upload], .comments .media.comment:not([id]) #tiptap__image-upload').setInputFiles('tests/fixtures/image.jpg');await requested;await page.getByRole('link',{name:'Comment review',exact:true}).first().click();await expect(page).toHaveURL(/\/projects\/1/);await expect.poll(()=>failures.length).toBe(1);release();await page.goto('/tasks/2');await expect(composer(page).locator('img')).toHaveCount(0);await expect(page.getByRole('textbox',{name:'Describe this image'})).toHaveCount(0)
})
for (const replacement of ['browser-fill', 'keyboard']) for (const width of [1440, 390]) test((replacement === 'keyboard' ? 'keyboard ' : '') + 'comment replacement remains exact after discard and re-entry across repeated edits ' + width, async ({authenticatedPage: page}, info) => {
 test.setTimeout(60000); await page.setViewportSize({width, height: 900}); await page.goto('/tasks/1'); const row = rows(page).first(), editor = row.locator('.ProseMirror'); let timeline: unknown[] = [], selectionTimeline: unknown[] = []; const replace = async (value: string) => {if (replacement === 'keyboard') {await editor.press('ControlOrMeta+A'); await editor.pressSequentially(value)} else await editor.fill(value)}
 await page.evaluate(() => {const events: unknown[] = []; Object.assign(window, {replacementEvents: events}); for (const type of ['beforeinput','selectionchange','focusin','focusout']) document.addEventListener(type, event => {const input = event as InputEvent, range = input.getTargetRanges?.()[0], selection = getSelection(); events.push({type,time:performance.now(),inputType:input.inputType,data:input.data,anchor:range?.startOffset,focus:range?.endOffset,text:range?.startContainer.textContent,selected:selection?.toString(),selectionAnchor:selection?.anchorOffset,selectionFocus:selection?.focusOffset,active:(document.activeElement as HTMLElement)?.className})}, true)})
 if (process.env.COMMENT_SELECTION_TRACE === '1') await installEditorSelectionTrace(page)
 try {
  for (let round = 0; round < 12; round++) {
   await row.getByRole('button', {name: 'Edit', exact: true}).click(); await replace('Discarded replacement ' + round); await editor.press('Escape')
   await row.getByRole('button', {name: 'Edit', exact: true}).click(); const text = 'Accepted replacement ' + round; await replace(text); await expect(editor).toHaveText(text)
   const saved = page.waitForResponse(response => /\/tasks\/1\/comments\/1$/.test(new URL(response.url()).pathname) && response.request().method() === 'POST'); await row.getByRole('button', {name: 'Save', exact: true}).click(); expect((await saved).request().postDataJSON().comment).toBe('<p>' + text + '</p>')
  }
  timeline = await page.evaluate(() => (window as unknown as {replacementEvents: unknown[]}).replacementEvents); if (process.env.COMMENT_SELECTION_TRACE === '1') selectionTimeline = await page.evaluate(() => (window as any).editorSelectionTrace ?? []); await page.reload(); await expect(rows(page).first().locator('.ProseMirror')).toHaveText('Accepted replacement 11')
 } finally {if (process.env.COMMENT_SELECTION_TRACE === '1') await info.attach('editor-selection-trace', {body: JSON.stringify(selectionTimeline.length ? selectionTimeline : await page.evaluate(() => (window as any).editorSelectionTrace ?? []), null, 2), contentType: 'application/json'}); await info.attach('replacement-input-events', {body: JSON.stringify(timeline.length ? timeline : await page.evaluate(() => (window as unknown as {replacementEvents?: unknown[]}).replacementEvents ?? []), null, 2), contentType: 'application/json'})}
})
