import {test, expect} from './fixtures'
import {ProjectFactory} from '../../frontend/tests/factories/project'
import {TaskFactory} from '../../frontend/tests/factories/task'
import {createDefaultViews} from '../../frontend/tests/e2e/project/prepareProjects'
test.beforeEach(async () => { await ProjectFactory.create(1, {title: 'Editor review'}); await createDefaultViews(1); await TaskFactory.create(2, {title: index => index === 1 ? 'Alpha task' : 'Beta task', description: index => index === 1 ? '<p>Original description</p>' : '', created: '2026-01-01T00:00:00Z', updated: '2026-01-01T00:00:00Z'}) })
const editor = page => page.locator('.tiptap__task-description .ProseMirror')
const surface = page => page.locator('.tiptap__task-description')
const saving = page => page.waitForResponse(response => /\/api\/v1\/tasks\/1$/.test(new URL(response.url()).pathname) && response.request().method() === 'POST')
for (const width of [1440, 390]) test(`description formatting, keyboard, save payload and reload ${width}`, async ({authenticatedPage: page}, info) => {
 await page.setViewportSize({width, height:900}); await page.goto('/tasks/1'); await expect(editor(page)).toContainText('Original description'); await page.waitForLoadState('networkidle'); await page.screenshot({path:info.outputPath('description-preview.png'), animations:'disabled'})
 await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); await expect(editor(page)).toBeFocused(); await page.screenshot({path:info.outputPath('description-edit.png'), animations:'disabled'}); await editor(page).press('ControlOrMeta+End'); await editor(page).press('Enter'); await surface(page).getByRole('button', {name:'Bold', exact:true}).first().click(); await editor(page).pressSequentially('Bold draft'); const saved = saving(page); await surface(page).getByRole('button', {name:'Save', exact:true}).click(); const response = await saved; expect(response.ok()).toBe(true); expect(response.request().postDataJSON().description).toBe('<p>Original description</p><p><strong>Bold draft</strong></p>'); await expect(editor(page)).toContainText('Bold draft'); await page.reload(); await expect(editor(page)).toContainText('Bold draft')
})
test('description discard, failed save retains draft and retry', async ({authenticatedPage: page}) => {
 await page.goto('/tasks/1'); await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); await editor(page).press('ControlOrMeta+End'); await editor(page).pressSequentially(' discarded'); await editor(page).press('Escape'); await expect(editor(page)).toHaveText('Original description'); await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); await editor(page).press('ControlOrMeta+End'); await editor(page).pressSequentially(' retained'); let failed = false; await page.route('**/api/v1/tasks/1', async route => { if (route.request().method() === 'POST' && !failed) { failed=true; await route.fulfill({status:500, json:{message:'fixture save failed'}}) } else await route.continue() }); await surface(page).getByRole('button', {name:'Save', exact:true}).click(); await expect(page.locator('.vue-notification.error')).toBeVisible(); expect(await page.evaluate(() => localStorage.getItem('editorDraft-task-description-1'))).toContain('retained'); await expect(editor(page)).toContainText('retained'); const saved = saving(page); await surface(page).getByRole('button', {name:'Save', exact:true}).click(); expect((await saved).ok()).toBe(true); await page.reload(); await expect(editor(page)).toContainText('retained')
})
test('toolbar roving focus, link prompt, table and markdown paste', async ({authenticatedPage: page}, info) => {
 await page.goto('/tasks/1'); await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); const toolbar = surface(page).getByRole('toolbar'); await toolbar.getByRole('button', {name:'Heading 1', exact:true}).focus(); await page.keyboard.press('End'); await expect(toolbar.getByRole('button', {name:'Table', exact:true})).toBeFocused(); await page.keyboard.press('Home'); await expect(toolbar.getByRole('button', {name:'Heading 1', exact:true})).toBeFocused(); await editor(page).press('ControlOrMeta+End'); await editor(page).press('ControlOrMeta+Shift+Home'); await toolbar.getByRole('button', {name:'Link', exact:true}).click(); const prompt = page.getByRole('textbox', {name:'URL'}); await expect(prompt).toBeFocused(); await prompt.fill('https://example.org/editor'); await prompt.press('Enter'); await expect(editor(page).locator('a')).toHaveAttribute('href', 'https://example.org/editor'); await page.screenshot({path:info.outputPath('description-link.png'),animations:'disabled'}); await editor(page).press('ControlOrMeta+End'); await editor(page).press('Enter'); await toolbar.getByRole('button', {name:'Table', exact:true}).click(); await toolbar.getByRole('button', {name:'Insert table', exact:true}).click(); await expect(editor(page).locator('table')).toHaveCount(1); const response = saving(page); await surface(page).getByRole('button', {name:'Save', exact:true}).click(); expect((await response).request().postDataJSON().description).toContain('<table')
 await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); await editor(page).press('ControlOrMeta+End'); await editor(page).evaluate(element => { const data = new DataTransfer(); data.setData('text/plain', '**Pasted bold**'); element.dispatchEvent(new ClipboardEvent('paste', {bubbles:true, cancelable:true, clipboardData:data})) }); await expect(editor(page).locator('strong').filter({hasText:'Pasted bold'})).toBeVisible()
})
test('slash and emoji suggestions preserve keyboard choice and serialize', async ({authenticatedPage: page}, info) => {
 await page.goto('/tasks/2'); const prose = editor(page); await prose.click(); await prose.pressSequentially('/head'); await expect(page.locator('.items .item').first()).toContainText('Heading 1'); await page.screenshot({path:info.outputPath('description-slash.png'),animations:'disabled'}); await prose.press('ArrowDown'); await prose.press('Enter'); await prose.pressSequentially('Suggested heading'); await expect(prose.locator('h2')).toHaveText('Suggested heading'); await prose.press('Enter'); await prose.pressSequentially(':smile'); await expect(page.locator('.emoji-items .emoji-item').first()).toBeVisible(); await page.screenshot({path:info.outputPath('description-emoji.png'),animations:'disabled'}); await prose.press('Enter'); await expect(prose).not.toContainText(':smile'); await surface(page).getByRole('button', {name:'Save', exact:true}).click(); await page.reload(); await expect(prose.locator('h2')).toHaveText('Suggested heading')
})
test('pending description save flushes before navigation without replacing newer task', async ({authenticatedPage: page}) => {
 await page.goto('/tasks/1'); await surface(page).getByRole('button', {name:'Edit', exact:true}).click(); await editor(page).press('ControlOrMeta+End'); await editor(page).pressSequentially(' before navigation'); let release; const gate = new Promise<void>(resolve => { release = resolve }); let seen; const requested = new Promise<void>(resolve => { seen = resolve }); await page.route('**/api/v1/tasks/1', async route => { if (route.request().method() === 'POST') { seen(); await gate }; await route.continue() }); await page.getByRole('link', {name:'Editor review',exact:true}).first().click({noWaitAfter:true}); await requested; await expect(page).toHaveURL(/\/tasks\/1$/); await expect(page.getByRole('status').filter({hasText:'Saving'})).toBeVisible(); release(); await expect(page).toHaveURL(/\/projects\/1/); await page.goto('/tasks/1'); await expect(editor(page)).toContainText('before navigation')
})
test('mention NodeView and task-link NodeView retain canonical HTML on save', async ({authenticatedPage: page}, info) => {
 const {UserFactory} = await import('../../frontend/tests/factories/user'); const {UserProjectFactory} = await import('../../frontend/tests/factories/users_project'); await UserFactory.create(1, {id:101, username:'editor-member', name:'Editor Member'}, false); await UserProjectFactory.create(1, {project_id:1,user_id:101}); await page.goto('/tasks/2'); await editor(page).click(); await editor(page).pressSequentially('@editor'); await expect(page.locator('.mention-items .mention-item')).toContainText('Editor Member'); await page.screenshot({path:info.outputPath('description-mention.png'),animations:'disabled'}); await editor(page).press('Enter'); await expect(editor(page).locator('.mention-user')).toContainText('Editor Member'); await editor(page).press('ControlOrMeta+End'); await editor(page).press('Enter'); const href = new URL('/tasks/1', page.url()).href; await editor(page).evaluate((element, href) => { const data = new DataTransfer(); data.setData('text/plain', href); element.dispatchEvent(new ClipboardEvent('paste', {bubbles:true,cancelable:true,clipboardData:data})) },href); await expect(editor(page).locator('.task-link-pill--task')).toContainText('Alpha task'); await page.screenshot({path:info.outputPath('description-nodeviews.png'),animations:'disabled'}); await surface(page).getByRole('button', {name:'Save',exact:true}).click(); await page.reload(); await expect(editor(page).locator('.mention-user')).toContainText('Editor Member'); await expect(editor(page).locator('.task-link-pill--task')).toContainText('Alpha task')
})
test('image upload, alt prompt, lightbox zoom and focus return', async ({authenticatedPage: page}, info) => {
 await page.goto('/tasks/2'); await expect(editor(page)).toBeVisible(); await surface(page).locator('#tiptap__image-upload').setInputFiles('tests/fixtures/image.jpg'); const alt = page.getByRole('textbox',{name:'Describe this image'}); await expect(alt).toBeFocused(); await alt.fill('Fixture image'); await alt.press('Enter'); await expect(editor(page).locator('img[alt="Fixture image"]')).toBeVisible(); await surface(page).getByRole('button',{name:'Save',exact:true}).click(); await expect(surface(page).getByRole('button',{name:'Edit',exact:true})).toBeVisible(); await page.reload(); await expect(editor(page).locator('img[alt="Fixture image"]')).toBeVisible(); await editor(page).locator('img').click(); const lightbox = page.getByRole('dialog',{name:'Image preview'}); await expect(lightbox).toBeVisible(); await expect(lightbox.locator('.image-lightbox__image')).toHaveClass(/is-loaded/); await page.screenshot({path:info.outputPath('description-lightbox.png'),animations:'disabled'}); await lightbox.getByRole('button',{name:'Zoom in',exact:true}).click(); await expect(lightbox.locator('.image-lightbox__level')).toHaveText('140%'); await lightbox.locator('img').focus(); await page.keyboard.press('0'); await expect(lightbox.locator('.image-lightbox__level')).toHaveText('100%'); await page.keyboard.press('Escape'); await expect(lightbox).toHaveCount(0); await expect(page.locator('dialog[open]')).toHaveCount(0); await expect(editor(page).locator('img')).toBeVisible()
})
test('upload pending during navigation is aborted without stale task publication', async ({authenticatedPage: page}) => {
 await page.goto('/tasks/2'); let release; const gate = new Promise<void>(resolve => {release=resolve}); let seen; const requested = new Promise<void>(resolve => {seen=resolve}); const failures: string[]=[]; page.on('requestfailed',request => {if (/\/tasks\/2\/attachments$/.test(new URL(request.url()).pathname)) failures.push(request.failure()?.errorText || '')}); await page.route('**/api/v1/tasks/2/attachments',async route => {seen(); await gate; try {await route.continue()} catch { /* Owner cancellation closes this intercepted request. */ }}); await surface(page).locator('#tiptap__image-upload').setInputFiles('tests/fixtures/image.jpg'); await requested; await page.getByRole('link',{name:'Editor review',exact:true}).first().click(); await expect(page).toHaveURL(/\/projects\/1/); await expect.poll(()=>failures.length).toBe(1); release(); await page.goto('/tasks/1'); await expect(editor(page)).toHaveText('Original description'); await expect(page.locator('input[placeholder="Describe this image"]')).toHaveCount(0)
})
test('read-only description cannot edit, toggle checklist, or send writes',async ({authenticatedPage:page,currentUser}) => {
 const {UserFactory}=await import('../../frontend/tests/factories/user'); const {UserProjectFactory}=await import('../../frontend/tests/factories/users_project'); const [owner]=await UserFactory.create(1,{id:101,username:'editor-owner'},false); await ProjectFactory.create(1,{id:2,title:'Read-only editor',owner_id:owner.id},false); await UserProjectFactory.create(1,{project_id:2,user_id:currentUser.id,permission:0}); await TaskFactory.create(1,{id:3,title:'Read-only task',project_id:2,created_by_id:owner.id,description:'<p>Read-only description</p><ul data-type="taskList"><li data-type="taskItem" data-checked="false"><label><input type="checkbox"><span></span></label><div><p>Protected checkbox</p></div></li></ul>'},false); const writes:string[]=[]; page.on('request',request=>{if(request.method()==='POST'&&/\/tasks\/3$/.test(new URL(request.url()).pathname))writes.push(request.url())}); await page.goto('/tasks/3'); await expect(editor(page)).toContainText('Read-only description'); await expect(surface(page).getByRole('button',{name:'Edit',exact:true})).toHaveCount(0); await editor(page).dblclick(); await page.keyboard.press('e'); await expect(editor(page)).toHaveAttribute('contenteditable','false'); await editor(page).locator('input[type=checkbox]').click(); await expect(editor(page).locator('input[type=checkbox]')).not.toBeChecked(); expect(writes).toEqual([])
})
