import {View} from 'marionette'
import LitDomApi from '@mnjs/adapters/dom/lit-html'
import {html, type TemplateResult} from 'lit-html'
import type {ITask} from '@/modelTypes/ITask'
import {isEditorContentEmpty} from '@/helpers/editorContentEmpty'
import {NativeEditorView, type NativeEditorOptions} from '../../shared/editor/editor'
import {listIcon} from '../../shared/task-list/list-ui'
export interface DescriptionOptions {task: ITask, canWrite: boolean, context: NativeEditorOptions['context'], upload: NativeEditorOptions['upload'], save: (description: string, signal: AbortSignal) => Promise<ITask>, accepted: (task: ITask) => void}
export const TaskDescriptionView = View.extend({
	ui: {'saving': '[data-saving]', 'saved': '[data-saved]', 'status': '[data-status]'},
	className: 'details content description native-task-description',
	initialize(options: DescriptionOptions) { void options },
	regions: {editor: '[data-editor]'},
	createState() { return {life: new AbortController(), value: this.options.task.description, accepted: this.options.task.description, dirty: false, pending: undefined as Promise<void> | undefined, changeTimer: undefined as ReturnType<typeof setTimeout> | undefined, dwellTimer: undefined as ReturnType<typeof setTimeout> | undefined, savedTimer: undefined as ReturnType<typeof setTimeout> | undefined, saving: false, dwelling: false, saved: false, editor: undefined as InstanceType<typeof NativeEditorView> | undefined} },
	templateContext() { return {content: this.content()} }, template: ({content}: {content: TemplateResult}) => content,
	content() { const t = this.options.context.t; return html`<h2 class="task-section-title"><span class="icon is-grey">${listIcon('align-left')}</span> ${t('task.attributes.description')} <span class="is-small is-inline-flex" aria-hidden="true" data-saving hidden><span class="loader is-inline-block mie-2"></span>${t('misc.saving')}</span><span class="is-small has-text-success" aria-hidden="true" data-saved hidden>${listIcon('check')}${t('misc.saved')}</span></h2><span class="is-sr-only" role="status" aria-live="polite" data-status></span><div data-editor></div>` },
	onRender() { const state = this.getState(); state.editor = new NativeEditorView({value: state.value, canWrite: this.options.canWrite, projectId: this.options.task.projectId, storageKey: `task-description-${this.options.task.id}`, placeholder: this.options.context.t('task.description.placeholder'), context: this.options.context, upload: this.options.upload, changed: value => this.changed(value), save: async () => { await this.flush(); return state.accepted }}); this.showChildView('editor', state.editor); this.refreshStatus() },
	changed(value: string) { const state = this.getState(); state.value = value; state.dirty = value !== state.accepted; clearTimeout(state.changeTimer); if (state.dirty) state.changeTimer = setTimeout(() => { void this.flush().catch(error => { if (!state.life.signal.aborted) this.options.context.reportError(error) }) }, 5000); this.el.classList.toggle('d-print-none', isEditorContentEmpty(value)) },
	flush(): Promise<void> { const state = this.getState(); if (state.pending) return state.pending.then(() => state.dirty ? this.flush() : undefined); if (!state.dirty || state.life.signal.aborted) return Promise.resolve(); const submitted = state.value; clearTimeout(state.changeTimer); state.saving = true; state.dwelling = true; state.saved = false; clearTimeout(state.dwellTimer); clearTimeout(state.savedTimer); state.savedTimer = undefined; state.dwellTimer = setTimeout(() => { state.dwelling = false; this.refreshStatus() }, 500); this.refreshStatus(); state.pending = this.options.save(submitted, state.life.signal).then(task => { if (state.life.signal.aborted) return; state.accepted = submitted; state.dirty = state.value !== submitted; state.saved = true; state.editor?.acceptSaved(submitted); this.options.accepted(task) }).catch(error => { if ((error as {response?: {status?: number}})?.response?.status !== 404 && !state.life.signal.aborted) { state.dirty = true; throw error } }).finally(() => { state.pending = undefined; state.saving = false; if (!state.life.signal.aborted) this.refreshStatus() }); return state.pending },
	refreshStatus() { if (this.isDestroyed()) return; const state = this.getState(), saving = state.saving || state.dwelling, saved = !saving && state.saved; const savingEl = (this.getUI('saving')![0] as HTMLElement), savedEl = (this.getUI('saved')![0] as HTMLElement), status = (this.getUI('status')![0] as HTMLElement); if (savingEl) savingEl.hidden = !saving; if (savedEl) savedEl.hidden = !saved; if (status) status.textContent = saving ? this.options.context.t('misc.saving') : saved ? this.options.context.t('misc.saved') : ''; if (saved && !state.savedTimer) state.savedTimer = setTimeout(() => { state.saved = false; state.savedTimer = undefined; this.refreshStatus() }, 2000) },
	updateInputs(task: ITask, canWrite: boolean) { const state = this.getState(); this.options.task = task; this.options.canWrite = canWrite; if (!state.dirty && !state.pending) state.value = state.accepted = task.description; state.editor?.updateInputs(state.value, canWrite, task.projectId) },
	onBeforeDestroy() { const state = this.getState(); state.life.abort(); clearTimeout(state.changeTimer); clearTimeout(state.dwellTimer); clearTimeout(state.savedTimer) },
}).setDomApi(LitDomApi)
