import {AUTH_TYPES} from '@/modelTypes/IUser'
import {View, CollectionView, Region, type ViewConfiguration} from 'marionette'
import {Collection, DataApi, type Model} from '@mnjs/data'
import LitDomApi from '@mnjs/adapters/dom/lit-html'
import {html, render, type TemplateResult} from 'lit-html'
import {klona} from 'klona'
import TaskCommentModel from '@/models/taskComment'
import type {ITaskComment} from '@/modelTypes/ITaskComment'
import type {IUser} from '@/modelTypes/IUser'
import {getDisplayName} from '@/models/user'
import {isEditorContentEmpty} from '@/helpers/editorContentEmpty'
import {NativeEditorView, type NativeEditorOptions} from '../../shared/editor/editor'
import {getTopLayerContainer} from '@/helpers/getTopLayerContainer'
import {AvatarTooltipView} from './task-membership-user'
import {EditorAvatarView} from '../../shared/editor/editor-avatar'
import {listIcon, button} from '../../shared/task-list/list-ui'
import './task-comments.scss'
import {ReactionsView} from './reactions'
export interface CommentsInputs {taskId: number, projectId: number, canWrite: boolean, user: IUser, initialComments?: ITaskComment[]}
export interface CommentsContext {
 editor: NativeEditorOptions['context'], displayDate: (date: Date) => string, upload: NativeEditorOptions['upload'], order: 'asc' | 'desc', maxItems: number,
 load: (taskId: number, order: 'asc' | 'desc', page: number, signal: AbortSignal) => Promise<{comments: ITaskComment[], pages: number}>,
 create: (comment: ITaskComment, signal: AbortSignal) => Promise<ITaskComment>, update: (comment: ITaskComment, signal: AbortSignal) => Promise<ITaskComment>, remove: (comment: ITaskComment, signal: AbortSignal) => Promise<unknown>,
 reaction: (id: number, value: string, remove: boolean, signal: AbortSignal) => Promise<unknown>,
 sort: (order: 'asc' | 'desc', signal: AbortSignal) => Promise<void>, copy: (id: number) => void, success: (key: string) => void,
}
interface Options extends CommentsInputs {context: CommentsContext}
interface Owner {options: Options, getState: () => {comments: ITaskComment[]}, signal: (caller: AbortSignal) => AbortSignal, accept: (comment: ITaskComment) => void, publish: (comments: ITaskComment[]) => void, editorContext: () => NativeEditorOptions['context'], reply: (parent: ITaskComment) => void, confirmDelete: (comment: ITaskComment) => void, tip: (trigger: HTMLElement, text: string) => void, hideTip: () => void}
interface RowOptions extends ViewConfiguration {model: Model, owner: Owner}
const CommentRowView = View.extend({
	ui: {'status': '[data-status]', 'edited': '[data-edited]'},
	initialize(options: RowOptions) { void options }, className: 'media comment', regions: {avatar: '[data-avatar]', mobileAvatar: '[data-mobile-avatar]', editor: '[data-editor]', reactions: '[data-reactions]'},
	attributes() { return {id: `comment-${this.options.model.id}`} },
	createState() { const comment = this.options.model.get('comment') as ITaskComment; return {life: new AbortController(), value: comment.comment, accepted: comment.comment, pending: undefined as Promise<void> | undefined, timer: undefined as ReturnType<typeof setTimeout> | undefined, savedTimer: undefined as ReturnType<typeof setTimeout> | undefined, editor: undefined as InstanceType<typeof NativeEditorView> | undefined, reactions: undefined as InstanceType<typeof ReactionsView> | undefined} },
	templateContext() { return {content: this.content()} }, template: ({content}: {content: TemplateResult}) => content,
	content() { const c = this.comment(), t = this.options.owner.options.context.editor.t; return html`<figure class="media-left is-hidden-mobile"><span data-avatar style="display:contents"></span><figcaption class="is-sr-only">${t('misc.avatarOfUser', {user: getDisplayName(c.author)})}</figcaption></figure><div class="media-content"><div class="comment-info"><span data-mobile-avatar style="display:contents"></span><strong>${getDisplayName(c.author)}</strong><span class="has-text-grey" @mouseenter=${(event: MouseEvent) => this.options.owner.tip(event.currentTarget as HTMLElement, this.options.owner.options.context.editor.displayDate(c.created))} @mouseleave=${() => this.options.owner.hideTip()}>${this.options.owner.options.context.displayDate(c.created)}</span><span data-edited @mouseenter=${(event: MouseEvent) => this.options.owner.tip(event.currentTarget as HTMLElement, this.options.owner.options.context.editor.displayDate(this.comment().updated))} @mouseleave=${() => this.options.owner.hideTip()}></span><a href=${`#comment-${c.id}`} class="comment-permalink" title=${t('task.comment.permalink')} @mouseenter=${(event: MouseEvent) => this.options.owner.tip(event.currentTarget as HTMLElement, t('task.comment.permalink'))} @mouseleave=${() => this.options.owner.hideTip()} @click=${(event: MouseEvent) => { event.preventDefault(); event.stopPropagation(); this.options.owner.options.context.copy(c.id) }}><span class="is-sr-only">${t('task.comment.permalink')}</span>${listIcon('link')}</a><span data-status role="status"></span></div><div data-editor></div><div data-reactions style="display:contents"></div></div>` },
	comment() { return this.options.model.get('comment') as ITaskComment },
	writable() { const owner = this.options.owner; return owner.options.canWrite && owner.options.user.type !== AUTH_TYPES.LINK_SHARE && owner.options.user.id === this.comment().author.id },
	onRender() { const state = this.getState(), c = this.comment(), owner = this.options.owner, ctx = owner.options.context; this.showChildView('avatar', new EditorAvatarView({user: c.author, size: 48, context: ctx.editor, imageClass: 'image is-avatar'})); this.showChildView('mobileAvatar', new EditorAvatarView({user: c.author, size: 20, context: ctx.editor, imageClass: 'image is-avatar d-print-none'})); state.editor = new NativeEditorView({variant: '', value: state.value, canWrite: this.writable(), showEdit: owner.options.user.type !== AUTH_TYPES.LINK_SHARE, projectId: owner.options.projectId, storageKey: '', placeholder: '', context: owner.editorContext(), upload: ctx.upload, editShortcut: '', enableDiscard: true, bottomActions: this.actions(), changed: value => this.changed(value), save: async () => { await this.flush(); return state.accepted }}); this.showChildView('editor', state.editor); state.reactions = new ReactionsView({user: () => owner.options.user, canWrite: () => owner.options.canWrite, reactions: () => this.comment().reactions, t: ctx.editor.t, reportError: ctx.editor.reportError, tip: (trigger, text) => owner.tip(trigger, text), hideTip: () => owner.hideTip(), transport: (value, remove, signal) => ctx.reaction(c.id, value, remove, owner.signal(signal)), accepted: reactions => owner.accept({...this.comment(), reactions})}); this.showChildView('reactions', state.reactions); this.metadata() },
	actions() { const owner = this.options.owner, t = owner.options.context.editor.t; return owner.options.canWrite ? [{title: t('task.comment.reply'), action: () => owner.reply(this.comment())}, ...(this.writable() ? [{title: t('misc.delete'), action: () => owner.confirmDelete(this.comment())}] : [])] : [] },
	changed(value: string) { const state = this.getState(); state.value = value; clearTimeout(state.timer); if (value !== state.accepted) state.timer = setTimeout(() => void this.flush().catch(error => { if (!state.life.signal.aborted && this.writable() && (error as Error).name !== 'AbortError') this.options.owner.options.context.editor.reportError(error) }), 5000) },
	flush(): Promise<void> { const state = this.getState(), owner = this.options.owner; clearTimeout(state.timer); if (state.pending) return state.pending.then(() => state.value !== state.accepted ? this.flush() : undefined); if (!this.writable() || state.life.signal.aborted || state.value === state.accepted || !state.value) return Promise.resolve(); const submitted = state.value, signal = owner.signal(state.life.signal); this.status('misc.saving', true); state.pending = owner.options.context.update(new TaskCommentModel({...this.comment(), taskId: owner.options.taskId, comment: submitted}), signal).then(comment => { signal.throwIfAborted(); state.accepted = submitted; state.editor?.acceptSaved(submitted); owner.accept(comment); this.status('misc.saved'); clearTimeout(state.savedTimer); state.savedTimer = setTimeout(() => this.status(''), 2000) }).catch(error => { if (signal.aborted) throw signal.reason; throw error }).finally(() => { state.pending = undefined; if (!this.isDestroyed() && state.value !== state.accepted) this.status('') }); return state.pending },
	status(key: string, loading = false) { if (this.isDestroyed()) return; const element = (this.getUI('status')![0] as HTMLElement)!; element.className = loading ? 'is-inline-flex' : 'has-text-success'; element.replaceChildren(); if (loading) { const loader = document.createElement('span'); loader.className = 'loader is-inline-block mie-2'; element.append(loader) }; if (key) element.append(this.options.owner.options.context.editor.t(key)) },
	metadata() { const c = this.comment(), el = (this.getUI('edited')![0] as HTMLElement)!; el.textContent = +new Date(c.created) === +new Date(c.updated) ? '' : `· ${this.options.owner.options.context.editor.t('task.comment.edited', {date: this.options.owner.options.context.displayDate(c.updated)})}`; el.hidden = +new Date(c.created) === +new Date(c.updated)  },
	updateInputs() { const state = this.getState(), owner = this.options.owner; if (state.value === state.accepted && !state.pending) state.value = state.accepted = this.comment().comment; state.editor!.options.bottomActions = this.actions(); state.editor?.updateInputs(state.value, this.writable(), owner.options.projectId); state.editor?.refreshActions(); if (state.reactions) { state.reactions.updateInputs() }; this.metadata() },
	onBeforeDestroy() { const state = this.getState(); state.life.abort(); clearTimeout(state.timer); clearTimeout(state.savedTimer) },
}).setDomApi(LitDomApi).setDataApi(DataApi)
const CommentsRowsView = CollectionView.extend({
	initialize(options: Omit<RowOptions, 'model'> & {collection: Collection}) { void options }, attributes: {style: 'display:contents'}, childView: CommentRowView, viewComparator: 'order',
	childViewOptions() { return {owner: this.options.owner} },
	publish(comments: ITaskComment[]) { const collection = this.options.collection, ids = new Set(comments.map(c => c.id)); collection.remove(collection.models.filter(model => !ids.has(Number(model.id)))); comments.forEach((comment, order) => { const model = collection.get(comment.id); if (model) model.set({comment, order}); else collection.add({id: comment.id, comment, order}) }); for (const child of this.children.toArray()) child.updateInputs(); this.sort() },
}).setDataApi(DataApi)
const CommentDeleteView = View.extend({
	ui: {'confirm': '.actions button:last-child', 'cancel': '.actions button:first-child'},
	initialize(options: {owner: Owner, comment: ITaskComment, close: () => void}) { void options }, tagName: 'dialog', className: 'modal-dialog default',
	attributes() { return {'aria-label': this.options.owner.options.context.editor.t('task.comment.delete')} },
	createState() { return {focus: document.activeElement, overflow: document.body.style.overflow, life: new AbortController(), timer: undefined as ReturnType<typeof setTimeout> | undefined, wasModalBeforePrint: false, busy: false} },
	templateContext() { return {content: this.content()} }, template: ({content}: {content: TemplateResult}) => content,
	content() { const t = this.options.owner.options.context.editor.t; return html`<div class="modal-container" @mousedown=${(event: MouseEvent) => { if (event.target === event.currentTarget) this.close() }}><button type="button" class="base-button base-button--type-button close d-print-none" aria-label=${t('misc.closeDialog')} @click=${() => this.close()}>${listIcon('times')}</button><div class="modal-content"><div class="modal-header">${t('task.comment.delete')}</div><div class="content"><p>${t('task.comment.deleteText1')}<br><strong class="has-text-white">${t('misc.cannotBeUndone')}</strong></p></div><div class="actions">${button(t('misc.cancel'), () => this.close(), 'tertiary')}${button(t('misc.doit'), () => void this.remove())}</div></div></div>` },
	events: {cancel: 'cancel'}, cancel(event: Event) { event.preventDefault(); this.close() },
	onAttach() { const state = this.getState(); window.addEventListener('beforeprint', () => { const dialog = this.el as HTMLDialogElement; if (dialog.matches(':modal')) { state.wasModalBeforePrint = true; dialog.close(); dialog.show() } }, {signal: state.life.signal}); window.addEventListener('afterprint', () => { const dialog = this.el as HTMLDialogElement; if (state.wasModalBeforePrint && dialog.open) { state.wasModalBeforePrint = false; dialog.close(); dialog.showModal() } }, {signal: state.life.signal}); document.body.style.overflow = 'hidden'; (this.el as HTMLDialogElement).showModal(); (this.getUI('confirm')![0] as HTMLButtonElement)?.setAttribute('data-cy', 'modalPrimary'); (this.getUI('confirm')![0] as HTMLButtonElement)?.classList.add('has-no-shadow'); (this.getUI('cancel')![0] as HTMLButtonElement)?.classList.add('has-text-danger') },
	close() { const state = this.getState(); if (state.timer) return; this.el.setAttribute('data-closing', ''); state.timer = setTimeout(this.options.close, 150) },
	async remove() { const state = this.getState(), owner = this.options.owner; if (state.busy || !owner.options.canWrite || owner.options.user.id !== this.options.comment.author.id) return; state.busy = true; const signal = owner.signal(state.life.signal); try { await owner.options.context.remove(new TaskCommentModel({...this.options.comment, taskId: owner.options.taskId}), signal); signal.throwIfAborted(); owner.publish(owner.getState().comments.filter(c => c.id !== this.options.comment.id)); owner.options.context.success('task.comment.deleteSuccess'); this.close() } catch (error) { if (!signal.aborted) owner.options.context.editor.reportError(error) } finally { state.busy = false } },
	onBeforeDestroy() { const state = this.getState(); state.life.abort(); clearTimeout(state.timer); (this.el as HTMLDialogElement).close(); document.body.style.overflow = state.overflow; if (state.focus instanceof HTMLElement && state.focus.isConnected) state.focus.focus() },
}).setDomApi(LitDomApi)
export const TaskCommentsView = View.extend({
	ui: {'loading': '[data-loading]', 'creating': '[data-creating]', 'heading': 'h2', 'sort': '[data-sort]', 'composerHost': '[data-new-comment]', 'add': '[data-add]', 'paginationHost': '[data-pagination]'},
	initialize(options: Options) { void options }, className: 'content details comments-container native-comments native-editor-surface',
	regions: {rows: '[data-rows]', composer: '[data-composer]', avatar: '[data-composer-avatar]'},
	createState() { return {life: new AbortController(), requests: new AbortController(), lookup: undefined as AbortController | undefined, comments: [] as ITaskComment[], page: 1, pages: 0, order: this.options.context.order, value: '', creating: false, loading: false, rows: undefined as {publish: (comments: ITaskComment[]) => void} | undefined, composer: undefined as InstanceType<typeof NativeEditorView> | undefined, dialog: undefined as InstanceType<typeof Region> | undefined, dialogHost: undefined as HTMLElement | undefined, observers: new Set<() => void>(), highlight: undefined as ReturnType<typeof setTimeout> | undefined, raf: 0, tip: undefined as InstanceType<typeof Region> | undefined, tipHost: undefined as HTMLElement | undefined, tipTrigger: undefined as HTMLElement | undefined, tipTimer: undefined as ReturnType<typeof setTimeout> | undefined} },
	templateContext() { return {content: this.content()} }, template: ({content}: {content: TemplateResult}) => content,
	content() { const t = this.options.context.editor.t; return html`<h2 class="comments-heading task-section-title"><span><span class="icon is-grey">${listIcon('comments', true)}</span> ${t('task.comment.title')}</span><button type="button" class="base-button base-button--type-button comment-sort-button" data-sort @click=${() => void this.toggleSort()}></button></h2><div class="comments"><span class="is-flex is-align-items-center mbs-4 mbe-4 mis-2" data-loading hidden><span class="loader is-inline-block mie-2"></span>${t('task.comment.loading')}</span><div data-rows style="display:contents"></div><div data-pagination style="display:contents"></div><div class="media comment d-print-none" data-new-comment><figure class="media-left is-hidden-mobile"><span data-composer-avatar style="display:contents"></span><figcaption class="is-sr-only">${t('misc.avatarOfUser', {user: getDisplayName(this.options.user)})}</figcaption></figure><div class="media-content"><div class="form"><span class="is-inline-flex" data-creating hidden><span class="loader is-inline-block mie-2"></span>${t('task.comment.creating')}</span><div class="field"><div data-composer></div></div><div class="field"><button type="button" class="base-button base-button--type-button button is-primary" style="--button-white-space:break-spaces" data-add @click=${() => void this.create().catch(error => { if (!this.isDestroyed() && (error as Error).name !== 'AbortError') this.options.context.editor.reportError(error) })}><span>${t('task.comment.comment')}</span></button></div></div></div></div></div>` },
	onRender() { const state = this.getState(), ctx = this.options.context; const rows = new CommentsRowsView({owner: this, collection: new Collection()}); state.rows = rows; this.showChildView('rows', rows); this.showChildView('avatar', new EditorAvatarView({user: this.options.user, size: 48, context: ctx.editor, imageClass: 'image is-avatar'})); state.composer = new NativeEditorView({variant: '', value: '', canWrite: this.options.canWrite, projectId: this.options.projectId, storageKey: `task-comment-${this.options.taskId}`, placeholder: ctx.editor.t('task.comment.placeholder'), context: this.editorContext(), upload: ctx.upload, showSave: false, editShortcut: '', enableDiscard: false, changed: value => { state.value = value; this.refresh() }, save: async () => { await this.create(); return undefined }}); this.showChildView('composer', state.composer); this.refresh(); const initial = this.options.initialComments; if (state.order === 'asc' && initial && initial.length < ctx.maxItems) this.publish(initial); else void this.load() },
	signal(caller: AbortSignal) { return AbortSignal.any([this.getState().life.signal, this.getState().requests.signal, caller]) },
	editorContext(): NativeEditorOptions['context'] { const state = this.getState(); return {...this.options.context.editor, comments: {find: id => state.comments.find(c => c.id === id), observe: changed => { state.observers.add(changed); return () => state.observers.delete(changed) }, jump: id => this.jump(id)}} },
	publish(comments: ITaskComment[]) { if (this.isDestroyed()) return; const state = this.getState(); state.comments = klona(comments); state.rows?.publish(state.comments); if (state.tipTrigger && !state.tipTrigger.isConnected) this.hideTip(); for (const changed of state.observers) changed(); this.refresh() },
	accept(comment: ITaskComment) { const state = this.getState(); this.publish(state.comments.map(c => c.id === comment.id ? comment : c)) },
	async load() { const state = this.getState(); state.lookup?.abort(); state.lookup = new AbortController(); const signal = this.signal(state.lookup.signal); state.loading = true; this.refresh(); try { const result = await this.options.context.load(this.options.taskId, state.order, state.page, signal); signal.throwIfAborted(); state.pages = result.pages; this.publish(result.comments) } catch (error) { if (!signal.aborted) this.options.context.editor.reportError(error) } finally { if (!signal.aborted) { state.loading = false; this.refresh() } } },
	async toggleSort() { const state = this.getState(), order = state.order === 'asc' ? 'desc' : 'asc', signal = this.signal(state.life.signal); try { await this.options.context.sort(order, signal); signal.throwIfAborted(); state.order = order; if (state.pages > 1) { state.page = 1; await this.load() } else this.publish([...state.comments].reverse()); this.refresh() } catch (error) { if (!signal.aborted) this.options.context.editor.reportError(error) } },
	async create() { const state = this.getState(); if (!this.options.canWrite || state.creating || isEditorContentEmpty(state.value)) return; const submitted = state.value, signal = this.signal(state.life.signal); state.creating = true; this.refresh(); try { const comment = await this.options.context.create(new TaskCommentModel({taskId: this.options.taskId, comment: submitted}), signal); signal.throwIfAborted(); if (state.order === 'desc' && state.page > 1) { state.page = 1; await this.load() } else this.publish(state.order === 'desc' ? [comment, ...state.comments] : [...state.comments, comment]); if (state.value === submitted) { state.value = ''; state.composer?.resetContent() }; if (state.order === 'desc') this.el.scrollIntoView({behavior: 'smooth', block: 'start', inline: 'nearest'}); this.options.context.success('task.comment.addedSuccess') } catch (error) { if (signal.aborted) throw signal.reason; throw error } finally { state.creating = false; if (!this.isDestroyed()) this.refresh() } },
	reply(parent: ITaskComment) { if (!this.options.canWrite) return; const doc = new DOMParser().parseFromString(`<div>${parent.comment ?? ''}</div>`, 'text/html'); doc.querySelectorAll('mention-user').forEach(el => { const label = (el.getAttribute('data-label') ?? el.textContent ?? '').trim(); el.replaceWith(label ? `@${label.replace(/^@+/, '')}` : '') }); this.getState().composer?.setReplyContent(`<blockquote data-comment-id="${parent.id}">${doc.body.firstElementChild?.innerHTML ?? ''}</blockquote><p></p>`) },
	jump(id: number) { const state = this.getState(), comment = this.el.querySelector<HTMLElement>(`#comment-${id}`); if (!comment) return; clearTimeout(state.highlight); cancelAnimationFrame(state.raf); comment.scrollIntoView({behavior: 'smooth', block: 'center'}); comment.classList.remove('comment-highlight'); state.raf = requestAnimationFrame(() => { comment.classList.add('comment-highlight'); state.highlight = setTimeout(() => comment.classList.remove('comment-highlight'), 1500) }) },
	tip(trigger: HTMLElement, text: string) { this.hideTip(); const state = this.getState(); state.tipTrigger = trigger; state.tipTimer = setTimeout(() => { if (this.isDestroyed() || !trigger.isConnected) return; const host = document.createElement('div'); getTopLayerContainer(this.el).append(host); state.tipHost = host; state.tip = new Region({el: host}); state.tip.show(new AvatarTooltipView({trigger, text})) }, 200) },
	hideTip() { const state = this.getState(); clearTimeout(state.tipTimer); state.tip?.destroy(); state.tipHost?.remove(); state.tip = undefined; state.tipHost = undefined; state.tipTrigger = undefined },
	confirmDelete(comment: ITaskComment) { this.hideTip(); this.closeDialog(); const state = this.getState(), host = document.createElement('div'); host.className = 'native-editor-surface'; document.body.append(host); state.dialogHost = host; state.dialog = new Region({el: host}); state.dialog.show(new CommentDeleteView({owner: this, comment, close: () => this.closeDialog()})) },
	closeDialog() { const state = this.getState(); state.dialog?.destroy(); state.dialogHost?.remove(); state.dialog = undefined; state.dialogHost = undefined },
	refresh() { if (this.isDestroyed()) return; const state = this.getState(), t = this.options.context.editor.t; (this.getUI('loading')![0] as HTMLElement)!.hidden = !state.loading; (this.getUI('creating')![0] as HTMLElement)!.hidden = !state.creating; const heading = (this.getUI('heading')![0] as HTMLElement)!; heading.hidden = !this.options.canWrite && !state.comments.length; heading.classList.toggle('d-print-none', !state.comments.length); const sort = (this.getUI('sort')![0] as HTMLButtonElement)!; sort.hidden = !state.comments.length; render(html`${listIcon(state.order === 'asc' ? 'arrow-down-short-wide' : 'arrow-up-short-wide')}${t(state.order === 'asc' ? 'task.comment.sortOldestFirst' : 'task.comment.sortNewestFirst')}`, sort); const composer = (this.getUI('composerHost')![0] as HTMLElement)!; composer.hidden = !this.options.canWrite; composer.classList.toggle('new-comment-top', state.order === 'desc'); composer.style.marginBlockStart = state.comments.length && state.pages <= 1 ? '.5rem' : ''; const add = (this.getUI('add')![0] as HTMLButtonElement)!; add.disabled = state.creating || isEditorContentEmpty(state.value); add.classList.toggle('is-loading', state.creating); state.composer?.el.classList.toggle('is-loading', state.creating || state.loading); this.pagination() },
	pagination() { const state = this.getState(), host = (this.getUI('paginationHost')![0] as HTMLElement)!, t = this.options.context.editor.t; host.replaceChildren(); if (state.pages <= 1) return; const nav = document.createElement('nav'); nav.className = 'pagination is-centered p-4'; nav.setAttribute('aria-label', 'pagination'); const make = (page: number, label: string, css: string) => { const element = document.createElement('button'); element.type = 'button'; element.className = `base-button base-button--type-button ${css}`; element.textContent = label; element.disabled = page < 1 || page > state.pages; if (css === 'pagination-link') element.setAttribute('aria-label', `Goto page ${page}`); element.onclick = () => { state.page = page; this.el.scrollIntoView({behavior: 'smooth', block: 'start', inline: 'nearest'}); void this.load() }; return element }; nav.append(make(state.page - 1, t('misc.previous'), 'pagination-previous'), make(state.page + 1, t('misc.next'), 'pagination-next')); const ul = document.createElement('ul'); ul.className = 'pagination-list'; for (let i = 1; i <= state.pages; i++) { if (i > 1 && i < state.pages && Math.abs(i - state.page) > 1) { if (ul.lastElementChild?.textContent !== '…') { const li = document.createElement('li'); li.innerHTML = '<span class="pagination-ellipsis">…</span>'; ul.append(li) }; continue }; const li = document.createElement('li'), item = make(i, String(i), 'pagination-link'); item.classList.toggle('is-current', i === state.page); li.append(item); ul.append(li) }; nav.append(ul); host.append(nav) },
	updateInputs(inputs: CommentsInputs) { const state = this.getState(); if (inputs.taskId !== this.options.taskId || (inputs.user.id !== this.options.user.id || inputs.user.type !== this.options.user.type)) { this.destroy(); return }; if (inputs.taskId !== this.options.taskId || (inputs.user.id !== this.options.user.id || inputs.user.type !== this.options.user.type) || inputs.canWrite !== this.options.canWrite) { state.requests.abort(); state.requests = new AbortController(); state.loading = false; this.closeDialog() }; Object.assign(this.options, inputs); state.rows?.publish(state.comments); state.composer?.updateInputs(state.value, inputs.canWrite, inputs.projectId); this.refresh() },
	onBeforeDestroy() { const state = this.getState(); state.life.abort(); state.requests.abort(); state.lookup?.abort(); clearTimeout(state.highlight); cancelAnimationFrame(state.raf); state.observers.clear(); this.hideTip(); this.closeDialog() },
}).setDomApi(LitDomApi)
