name: ci

env:
  DO_NOT_TRACK: 1

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  # main merges use a unique run_id so they don't cancel each other
  # other branches or PRs share a group to auto-cancel old runs
  group: ${{ github.ref == 'refs/heads/main' &&
    format('{0}-{1}', github.workflow, github.run_id) ||
    format('{0}-{1}', github.workflow, github.event.pull_request.number || github.ref) }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
